### ISSUE TITLE
hyperref default colors

### ISSUE THREAD

**Issue by jowens** [borisveytsman/acmart#1]
I dislike the hyperref default colors for links. In particular I don't like the citation links (green)—take a look at page 2 of sample-acmsmall.pdf—I find that very difficult to read on the screen, and when printed on a black and white printer, the green is light enough to make the text too light to read on paper. In general fully saturated colors are a bad idea, period.

The hyperref package lets you set all colors as extensions, so it's straightforward to include different colors in the class file.

I am happy to suggest colors for the different link types (there's some nice work in the Siggraph community at least, probably CHI as well), but want to hear the opinions of others. In general I would like colors that are a) dark enough to print well on b/w printers and b) not fully saturated.

**Comment by borisveytsman** [comment]
It makes a lot of sense to use ACM brand colors.

There is ACM identiry guide:
http://identitystandards.acm.org/identitystandards.pdf.  Section 2.14
lists the palette

What about 

linkcolor: ACM Dark Purple
citecolor: ACM Green (very dark)
filecolor: ACM Dark Blue
urlcolor:  ACM Dark Blue

-- 
Good luck

-Boris

Nostalgia is living life in the past lane.

**Comment by borisveytsman** [comment]
Let me push the suggestions past our editors.

-Craig
�
Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org
http://member.acm.org/~rodkin 
�
Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service


-----Original Message-----
From: Boris Veytsman [mailto:borisv@lk.net] 
Sent: Friday, April 15, 2016 2:13 PM
To: borisveytsman/acmart
Cc: Craig Rodkin
Subject: hyperref default colors


It makes a lot of sense to use ACM brand colors.

There is ACM identiry guide:
http://identitystandards.acm.org/identitystandards.pdf.  Section 2.14 lists the palette

What about 

linkcolor: ACM Dark Purple
citecolor: ACM Green (very dark)
filecolor: ACM Dark Blue
urlcolor:  ACM Dark Blue

--
Good luck

-Boris

Nostalgia is living life in the past lane.

**Comment by borisveytsman** [comment]
I hope to have an answer for you on Monday.

-Craig
�
Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org
http://member.acm.org/~rodkin 
�
Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service


-----Original Message-----
From: Craig Rodkin 
Sent: Friday, April 15, 2016 2:15 PM
To: 'Boris Veytsman'; borisveytsman/acmart
Subject: RE: hyperref default colors

Let me push the suggestions past our editors.

-Craig
�
Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org
http://member.acm.org/~rodkin 
�
Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service


-----Original Message-----
From: Boris Veytsman [mailto:borisv@lk.net] 
Sent: Friday, April 15, 2016 2:13 PM
To: borisveytsman/acmart
Cc: Craig Rodkin
Subject: hyperref default colors


It makes a lot of sense to use ACM brand colors.

There is ACM identiry guide:
http://identitystandards.acm.org/identitystandards.pdf.  Section 2.14 lists the palette

What about 

linkcolor: ACM Dark Purple
citecolor: ACM Green (very dark)
filecolor: ACM Dark Blue
urlcolor:  ACM Dark Blue

--
Good luck

-Boris

Nostalgia is living life in the past lane.

**Comment by jowens** [comment]
ACM palette colors seem perfectly cromulent to me. We should do a test print with them after they're in the style, just to make sure they look OK b/w and color on paper.

**Comment by borisveytsman** [comment]
These are *screen* colors.  The print version (compiled with
screen=false option) is b/w.  

-- 
Good luck

-Boris

Avec!

**Comment by jowens** [comment]
Sure, but in practice, most users will compile only one version and will post that version to the DL and to their own repositories. That version is probably the default version with screen=true. So, even though it would be ideal if only screen=false versions ever made it through a b/w printer, in practice, most papers will be printed from a screen=true version, so we should try to make it look decent.

**Comment by borisveytsman** [comment]
I agree that many users will print out the papers of their choice.
However, chances are, these users have might color printers.  So we
should carefull think about use cases

I think dark blue is ok even for b/w printers.  What about other ones?

-- 
Good luck

-Boris

When the government bureau's remedies don't match your problem, you modify
the problem, not the remedy.

**Comment by borisveytsman** [comment]
Boris, is it possible to send screen shots of the points of color options. We are having a hard time visualizing where the color options are on any particular page. Thanks

- Craig

Craig Rodkin
ACM - Publications Operations Manager


Boris Veytsman <borisv@lk.net> wrote:


It makes a lot of sense to use ACM brand colors.

There is ACM identiry guide:
http://identitystandards.acm.org/identitystandards.pdf.  Section 2.14
lists the palette

What about

linkcolor: ACM Dark Purple
citecolor: ACM Green (very dark)
filecolor: ACM Dark Blue
urlcolor:  ACM Dark Blue

--
Good luck

-Boris

Nostalgia is living life in the past lane.

**Comment by jowens** [comment]
My guess is that any fairly dark colors, such as those you've selected, will look good printed on both b/w and color printers (better than 00ff00, that's for sure). Check in the ones you've picked, with Craig's approval, and we can test them and find out!

**Comment by Craig-Rodkin** [comment]
Hi,
We reviewed the colors with ACM Senior Editors and have 2 changes to your suggested colors:

For citations, use the ACM Purple
For Footnotes, use ACM Red

Thanks

**Comment by borisveytsman** [comment]
Done
