### ISSUE TITLE
Pre-submission author's draft mode

### ISSUE THREAD

**Issue by jthywiss** [borisveytsman/acmart#101]
It would be nice to have a pre-submission author's draft mode.  This would be similar to `manuscript`, but be in the correct format (`acmlarge`, `sigplan`, etc.).  Like `manuscript`, this mode would:

- Set the copyright permission to "Unpublished working draft. Not for distribution."
- Set a footer with "DRAFT built \<date> \<time>".
- Suppress printing of reprint data (ISBN/ISSN & price) after copyright.

Unlike `manuscript`, though:

- The format would match the intended publication venue's format.
- The permissions block would not claim that the document had been "submitted to ACM".

Side-note: It may be a cleaner design to explicitly keep format and a article life cycle stage as distinct attributes.  (The NISO recommended nomenclature for journal article stages is: Author’s Original, Submitted Manuscript Under Review, Accepted Manuscript, Proof, Version of Record. [[NISO-RP-8-2008](http://www.niso.org/publications/rp/RP-8-2008.pdf)])

### Some implementation fragments to copy:

If pre-submission author's draft mode is set:

    \setcopyright{rightsretained}
    \def\@copyrightpermission{Unpublished working draft. Not for distribution.}

Override fancy page style footer with:

        \fancyfoot[RO,LE]{\footnotesize {\colorbox{ACMOrange}{\color{white} DRAFT built \today~\currenttime}}}%

**Comment by MatthewFluet** [comment]
Related (closed) issue: #8.
