### ISSUE TITLE
DOI URL update

### ISSUE THREAD

**Issue by jthywiss** [borisveytsman/acmart#102]
The International DOI Foundation now prefers just `doi.org` to `dx.doi.org` when referring to the DOI system Proxy Server.  The server also now supports TLS.

So, change all references to `http://dx.doi.org/` to `https://doi.org/`.

**Comment by krono** [comment]
This is only true for CrossRef up to now.

**Comment by jthywiss** [comment]
It looks like it's all DOIs now: http://www.doi.org/doi_handbook/3_Resolution.html#3.7.3

**Comment by krono** [comment]
That's good to know, thanks

**Comment by borisveytsman** [comment]
We discussed this with ACM folks when the new format was in the plans at CrossRef.  As soon as ACM greenlights this, I will change to the new format.
