### ISSUE TITLE
misunderstanding regarding installation

### ISSUE THREAD

**Issue by MrWanter** [borisveytsman/acmart#111]
Hi!
I'm new to use the package, as regarding the installation instruction in the user's guide, it says ` 1,Run latex on acmart.ins. This will produce the file acmart.cls. 2,Put the file acmart.cls and the bibligoraphy files *.bst to the places where L ATEX
can find them, 3 Update the database of file names. ` 
but the problem is I just download the package and open a sample tex file and compile it, it works, no need to do any such installation steps, where I'm wrong of? can any one help me, thanks very much!

**Comment by MatthewFluet** [comment]
You are probably picking up the version of `acmart` on CTAN (http://ctan.org/pkg/acmart) provided by your TeX distribution; for example, MacTeX defaults to installing/updating many packages, including `acmart`.

**Comment by borisveytsman** [comment]
Yes, in most cases you should *not* install acmart yourself.  Probably I should stress this even more in the documentation.
