### ISSUE TITLE
Can't use with biblatex

### ISSUE THREAD

**Issue by larseggert** [borisveytsman/acmart#114]
Doing
```
\documentclass[sigconf, natbib=false]{acmart}
\usepackage[backend=biber, style=trad-abbrv]{biblatex}
```
results in:
```
(/usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/blx-dm.def)

! LaTeX Error: Command \citename already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.9791 ...d*{\citename}{\blx@citexpunct{citename}}
```

**Comment by larseggert** [comment]
A workaround seems to be:
```
--- /usr/local/texlive//2016/texmf-dist/tex/latex/acmart/acmart.cls	2017-03-10 00:01:06.000000000 +0100
+++ acmart.cls	2017-03-13 10:46:27.000000000 +0100
@@ -424,8 +424,8 @@
      {\begingroup\NAT@swafalse
        \let\NAT@ctype\@ne\NAT@partrue\NAT@fullfalse\NAT@open\NAT@citetp}%
   \providecommand\newblock{}%
-\else
-  \providecommand\citename[1]{#1}
+%\else
+%  \providecommand\citename[1]{#1}
 \fi
 \def\shortcite#1{\ifNAT@numbers\cite{#1}\else\citeyear{#1}\fi}
 \def\bibliographystyle#1{%
```

**Comment by borisveytsman** [comment]
I am afraid the problem is not just disabling `\citename`.  The bigger problem is that official ACM bibtex styles create special tags used by metadata tools during publication.  Adding biblatex compatibility means writing similar ACM biblatex package.

I will discuss with ACM people whether they want this

**Comment by larseggert** [comment]
At least getting rid of the `\citename` lets me use biblatex at all with the new template. Whether that removes any ACM metadata is something I'll worry about after the paper is accepted...

But I do think that having the ACM template force people to use `natbib` is not really a great solution, give that it's apparently not being maintained and has seen the last update in 2010.

**Comment by borisveytsman** [comment]
@larseggert please test.  Works for me

**Comment by larseggert** [comment]
Works here, too

**Comment by ncardozo** [comment]
@borisveytsman The fix works for me too, though the first time i try to run bibtex I get a "command \bibhang already defined" Do you know what this problem may be? (If i keep on running it a couple of times it eventually displays the bibliography correctly}

**Comment by drt24** [comment]
@ncardozo Do you have something like `\documentclass[sigconf,natbib=false]{acmart}` ? With that set I only seem to need `\let\citename\relax` and (before the documentclass) `\newcommand{\citestyle}[1]{}` to make it work with the version of acmart currently used by Overleaf.

**Comment by drt24** [comment]
For the record: style=trad-abbrv does not produce references in anything close to the ACM reference style. I am working on something that approximates it but in the meantime using biblatex with acmart will produce incorrect results.
