### ISSUE TITLE
@online entry cannot be used

### ISSUE THREAD

**Issue by MrWanter** [borisveytsman/acmart#121]
Hi! I'm new to use the template, there is an `@online` entry as the user's guide `acmart.pdf` stated, but when I add it to the `.bib`, and reference it in the `.tex`, it cannot work as other entries, the compiler raised `citation undefined`,  can anyone help me? Thanks !
BTW, I just copy the example 
```
@online{Thornburg01,
author = "Harry Thornburg",
year = "2001",
title = "Introduction to Bayesian Statistics",
url = "http://ccrma.stanford.edu/˜jos/bayes/bayes.html",
month = mar,
lastaccessed = "March 2, 2005",
}
```
in the `acmart.pdf`, and ref it,

**Comment by borisveytsman** [comment]
Your problem is the character `˜` in the URL.  It is not real tilde (`~`), but rather unicode character 	0x2DC (small tilde).  Change it to the real tilde, and everything will work.

**Comment by MrWanter** [comment]
Thank you, I change it to something else:
```
@online{Thornburg01,
author = "Harry Thornburg",
year = "2001",
title = "Introduction to Bayesian Statistics",
url = "https://github.com/borisveytsman/acmart/issues/121",
month = mar,
lastaccessed = "March 2, 2005",
}
```
but after compile, it still raise the problem

**Comment by MrWanter** [comment]
Sorry, there is just other problem block the compilation, after solve that, it works, thank you.
