### ISSUE TITLE
Author names: mixed case versus upper case

### ISSUE THREAD

**Issue by adamsmd** [borisveytsman/acmart#123]
Currently author names are upper cased in the `manuscript`, `acmsmall`, `acmlarge`, and `acmtog` styles due to a call to `\MakeUppercase` in `\@mkauthors@i`.  However, there are several names for which capitalization is important (examples given below).  In these cases, there is no way to determine the proper capitalization using only the upper cased form.  Upper casing thus removes information that someone citing an ACM paper might need.

Instead of upper casing, I would like to propose moving to something that does not erase that information.  For example, a "small caps" font instead of upper casing, or just normal mixed case.  Anything that preserves the capitalization information would suffice.

Obviously the ACM will need to be consulted to see what they think. Either you could contact them, or if you prefer, I can contact them directly if you point me at the appropriate person to contact.

Examples:

- Whether an author spells his name as `Van Horn` or `van Horn`.  These are different names and in some styles get sorted differently by BibTeX.  (This is not the case for the ACM BibTeX style, but a non-ACM publication may be citing such an author.)

- The names `Machamer` (German) and `MacHamer` (hypothetical Gaelic name).  Without capitalization or external knowledge, it is impossible to determine which is correct.

- The Irish name `de hÍde` (Irish form of [1]) versus `de Híde` (hypothetical).  Without capitalization or external knowledge, it is impossible to determine which is correct.

- Chinese given names such as `ZhaoRan`.  When romanizing Chinese names the first letter of each Chinese character often upper cased [2]. (This is one of many conventions for romanizing Chinese names, so not all names are like this.)

[1] https://en.wikipedia.org/wiki/Douglas_Hyde
[2] ZhaoRan Xu and Dan H. Nicolson: Don't Abbreviate Chinese Names. *Taxon* Vol. 41, No. 3 (Aug., 1992), pp. 499-504. Published by: International Association for Plant Taxonomy (IAPT). DOI: 10.2307/1222820. Stable URL: http://www.jstor.org/stable/1222820

**Comment by borisveytsman** [comment]
Thanks, I will contact ACM

**Comment by borisveytsman** [comment]
Here is the opinion of ACM.  

Right now ACM publications include "reference format" with the proper capitalization of authors' names.  Given that this information is present, it is probably fine to have authors' names in the beginning of the paper uppercased.

Note that paper metadata also has proper capitalization:  look at PDF document properties.

**Comment by adamsmd** [comment]
Thank you for looking into this.  I had overlooked the "reference format", which does seem to address my concerns, so I'm closing the issue.
