### ISSUE TITLE
How to add subfigure to the template

### ISSUE THREAD

**Issue by MrWanter** [borisveytsman/acmart#124]
Hi! I'm new to use the template, I tried to use `\begin{subfigure}` command, but the command is not recognized by the template, then I add `\usepackage{graphicx} \usepackage{subfigure} ` to the file, but still cannot recognize the command. And I didn't find instructions in the User's Guide setion of `acmart.pdf` , can anyone tell me how to add subfigures to the template? Thanks!

**Comment by borisveytsman** [comment]
`\subfigure` is a command, not an environment.

```
\documentclass{acmart}
\usepackage{subfigure}
\begin{document}
\begin{figure}
  \subfigure{First}{\includegraphics[width=1in]{tiger}}
  \subfigure{Secondq}{\includegraphics[width=1in]{tiger}}
  \caption{This is the fist figure}
  \label{fig:fig}
\end{figure}
\end{document}
```

**Comment by rionda** [comment]
As a side note, the subfigure package is deprecated. The package subfig or the even more recent package subcaption should probably be used.

**Comment by MatthewFluet** [comment]
Indeed, the `acmart` documentation suggests `subcaption`: https://github.com/borisveytsman/acmart/blob/master/acmart.dtx#L1346

**Comment by borisveytsman** [comment]
Thanks!

Ok, I think this can be closed...

**Comment by MrWanter** [comment]
Thank you all, and sorry for the delayed responce
