### ISSUE TITLE
Document transitive closure of used packages

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#13]
I'm not sure the degree to which the `amsart.pdf` will be the final documentation for the consolidated class, but, since there are a lot of internal changes from `sig-alternate.cls` and `sigplanconf.cls` (the two predecessors that I'm most familiar with), it would help to have a concise list of the packages that get loaded in the "User's Guide" section; I know that they are there implicitly in the "Implementation" section, but they are spread out and not where a user should need to go for this information.

For example, I needed to discover that the `newtxmath` package was being loaded in order to understand what was changing the `\forall` and `\exists` glyphs (and that alternates were available).

**Comment by borisveytsman** [comment]
Done

**Comment by MatthewFluet** [comment]
Thanks.  I think this will also help with the customization discussion.
