### ISSUE TITLE
BibTeX: `articleno` vs `eid`

### ISSUE THREAD

**Issue by adamsmd** [borisveytsman/acmart#133]
Quite a few BibTeX styles support an `eid` field that looks similar to ACM's `articleno` field.  The documentation is thin, so I'm not sure if they actually serve the same purpose as each other or if there is some important distinction.  If they are the same, it might be good to use `eid` (which is widely used [1]) instead of `articleno` (which is used only by ACM [2]).  (Of course, with appropriate backwards compatibility and deprecation warnings).

[1] On my system, `grep -R eid /usr/share/texlive/texmf-dist/bibtex/bst/` turns up around ~100 `.bst` files using `eid`. [3]

[2] On my system, `grep -R articleno /usr/share/texlive/texmf-dist/bibtex/bst/` turns up only the ACM `.bst` file. [3]

[3] My apologies for how unscientific these measurements are.

**Comment by k4rtik** [comment]
It seems for the lack of support of `eid` and `articleno`, a lot of established journals use (overload) the `pages` field with the same information. Some examples:
1. IOP: https://iopscience.iop.org/article/10.1088/1367-2630/13/4/043016
2. Quantum: https://quantum-journal.org/papers/q-2019-03-25-130/
3. J. Math. Phy.: https://aip.scitation.org/doi/10.1063/1.2203431
4. Phys. Rev. Let.: https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.111.090505
5. Phys. Rev. A: https://journals.aps.org/pra/abstract/10.1103/PhysRevA.71.062323

Do we know if `articleno`/`eid` is compatible with `pages`? I personally prefer `eid`, but then the information is lost if the style doesn't support that field.
