### ISSUE TITLE
compile error on Texstudio

### ISSUE THREAD

**Issue by liudonglei** [borisveytsman/acmart#134]
in file acmart.cls line 378: Package kvsetkeys Error: Undefined key `hidelinks'. \hypersetup{hidelinks}

**Comment by borisveytsman** [comment]
Can you please post the log?

**Comment by liudonglei** [comment]
sorry, there are the log.   
In TeXstudio 2.10.2  
Process started: xelatex.exe -synctex=1 -interaction=nonstopmode "sample-sigconf".tex
-----------------------------------------------------
line 413: Package kvsetkeys Error: Undefined key `hidelinks'. \hypersetup{hidelinks}
: You don't seem to be using pdftex.
line 578: You do not have zi4 package installed. Please upgrade your TeX
line 581: You do not have newtxmath package installed. Please upgrade your TeX
: Unused global option(s): [sigconf].
: No file sample-sigconf.aux.
: Rerun to get /PageLabels entry.
line 156: Underfull \hbox (badness 1057) in paragraph
line 156: Reference `TotPages' on page 1 undefined
line 156: Overfull \hbox (1.56439pt too wide) in paragraph
line 156: Overfull \hbox (3.20192pt too wide) in paragraph
: Underfull \vbox (badness 8189) has occurred while \output is active []
line 50: Citation `Lamport:LaTeX' on page 2 undefined
line 58: Font shape `OT1/cmss/m/it' in size <9> not available(Font) Font shape `OT1/cmss/m/sl' tried instead
line 65: Citation `Lamport:LaTeX' on page 2 undefined
line 101: Citation `bowman:reasoning' on page 2 undefined
line 101: Citation `clark:pct' on page 2 undefined
line 101: Citation `braams:babel' on page 2 undefined
line 101: Citation `herlihy:methodology' on page 2 undefined
line 102: Citation `clark:pct' on page 2 undefined
line 103: Citation `Lamport:LaTeX' on page 2 undefined
line 103: Citation `salas:calculus' on page 2 undefined
line 109: Citation `Lamport:LaTeX' on page 2 undefined
line 120: Citation `Lamport:LaTeX' on page 2 undefined
line 140: Reference `tab:freq' on page 2 undefined
line 164: Reference `tab:commands' on page 2 undefined
line 184: Citation `Fear05' on page 2 undefined
line 268: Citation `Amsthm15' on page 3 undefined
line 264: Overfull \hbox (5.8488pt too wide) in paragraph
line 286: Overfull \hbox (14.46077pt too wide) detected
line 4: Overfull \hbox (11.41887pt too wide) in paragraph
: No file sample-sigconf.bbl.
: There were undefined citations.
: There were undefined references.
: Label(s) may have changed. Rerun to get cross-references right.

**Comment by liudonglei** [comment]
sorry, there are the log.
In TeXstudio 2.10.2
Process started: xelatex.exe -synctex=1 -interaction=nonstopmode "sample-sigconf".tex

line 413: Package kvsetkeys Error: Undefined key hidelinks'. \hypersetup{hidelinks} : You don't seem to be using pdftex. 

line 578: You do not have zi4 package installed. Please upgrade your TeX 
line 581: You do not have newtxmath package installed. Please upgrade your TeX : Unused global option(s): [sigconf]. : No file sample-sigconf.aux. : Rerun to get /PageLabels entry. 
line 156: Underfull \hbox (badness 1057) in paragraph line 156: ReferenceTotPages' on page 1 undefined
line 156: Overfull \hbox (1.56439pt too wide) in paragraph
line 156: Overfull \hbox (3.20192pt too wide) in paragraph
: Underfull \vbox (badness 8189) has occurred while \output is active []
line 50: Citation Lamport:LaTeX' on page 2 undefined 
line 58: Font shapeOT1/cmss/m/it' in size <9> not available(Font) Font shape OT1/cmss/m/sl' tried instead 
line 65: CitationLamport:LaTeX' on page 2 undefined
line 101: Citation bowman:reasoning' on page 2 undefined 
line 101: Citationclark:pct' on page 2 undefined
line 101: Citation braams:babel' on page 2 undefined 
line 101: Citationherlihy:methodology' on page 2 undefined
line 102: Citation clark:pct' on page 2 undefined 
line 103: CitationLamport:LaTeX' on page 2 undefined
line 103: Citation salas:calculus' on page 2 undefined 
line 109: CitationLamport:LaTeX' on page 2 undefined
line 120: Citation Lamport:LaTeX' on page 2 undefined 
line 140: Referencetab:freq' on page 2 undefined
line 164: Reference tab:commands' on page 2 undefined 
line 184: CitationFear05' on page 2 undefined
line 268: Citation `Amsthm15' on page 3 undefined
line 264: Overfull \hbox (5.8488pt too wide) in paragraph
line 286: Overfull \hbox (14.46077pt too wide) detected
line 4: Overfull \hbox (11.41887pt too wide) in paragraph
: No file sample-sigconf.bbl.
: There were undefined citations.
: There were undefined references.
: Label(s) may have changed. Rerun to get cross-references right.

**Comment by borisveytsman** [comment]
Unfortunately, this is not the full log - you omitted the beginning where it lists the version of the LaTeX packages involved.  However, judging by the absence of some font packages and the error displayed, it looks like your TeX installation is very old.

You need to upgrade your TeX engine.  Please note that TeX Studio is *not* a TeX engine: it is just a front end, and you need to upgrade the underlaying TeX layer.

**Comment by liudonglei** [comment]
Thank you. I will go to upgrade my MikTex tool
