### ISSUE TITLE
How to create indent form like this kind?

### ISSUE THREAD

**Issue by MrWanter** [borisveytsman/acmart#135]
Hi! I'm new to latex, I have a simple problem but I can't figure out how to do it, I want to create indent form like this:

```
test test test test test test test test:
       test  test test test test test test tes test test
              test test test test test test test test test 
              test test test test test test test test test
       test  test test test test test test tes test test
              test test test test test test test test test 
              test test test test test test test test test
       test  test test test test test test tes test test
              test test test test test test test test test 
              test test test test test test test test test
```
Thank you!

**Comment by borisveytsman** [comment]
This is not an `acmart`-specific question or problem.  There are many places to ask questions like this, for example, http://tex.stackexchange.com/.

The answer to your question depends on whether you want TeX to split the input into lines, or you know what lines splits are.  In the first case look at `\parshape` command.  In the second place you need to use a `list`.  See:  http://tex.stackexchange.com/questions/32226/how-to-layout-irregular-paragraph-shape, https://en.wikibooks.org/wiki/LaTeX/List_Structures

**Comment by MrWanter** [comment]
Thank you very much!
