### ISSUE TITLE
Counter 'theorem' is used for all other labels and throws off Cleveref (definition/lemma/example appears as theorem)

### ISSUE THREAD

**Issue by cogumbreiro** [borisveytsman/acmart#138]
This issue is regarding this problem: http://tex.stackexchange.com/questions/361251/

When using any predefined theorem-environment such as `example`, `definition`, or `lemma` Cleveref always shows up `theorem`. I was expecting Cleveref to the appropriate name. The source the problem seems to be that the counter `theorem` is used for all environments.

*I am wondering if we can fix this at the cls-level, or if there's a better fix than the workaround discussed below.*

For instance, when defining
```tex
\begin{example}
\label{myex}
Assume BLA BLA
\end{example}
```
Then, the next sentence
```tex
In \cref{myex}, we explained BLA BLA
```
renders as
```
In theorem 4.1. we explained BLA BLA
```

The workaround is to override the counter of the label. Rewriting the original example with the fix becomes:

```tex
\begin{example}
\label[example]{myex}
Assume BLA BLA
\end{example}
```

**Comment by Blaisorblade** [comment]
I run into this as well, and traced it to a problem with the underlying amsart class described here: https://tex.stackexchange.com/a/253694/1340.

The usual fix would be to load packages in this order **before defining theorems**:

```latex
\usepackage{hyperref}
\usepackage{amsthm}
\usepackage{cleveref}
%
% Define example, definition, lemma environments here with newtheorem HERE.
```

But `amsart` has an inline variant of `amsthm`, so this is impossible. That answers describes a hack which doesn't work well with amsart or acmart.

It's not clear how to fix this even with `acmart-preload-hook.tex`.

**Comment by rionda** [comment]
I also run into these, and it would be great to have acmart work with cleveref.
