### ISSUE TITLE
underscore cannot be shown in URL

### ISSUE THREAD

**Issue by haoscs** [borisveytsman/acmart#139]
Typically \url{...} works fine for the URLs including underscore (_). But when I switch to the acmart, now the underscore is causing the next character being explained as a subscript. Could anyone help me on how to remain the underscore in URLs?

Many thanks!

**Comment by borisveytsman** [comment]
Can you provide an example of the problem?

**Comment by haoscs** [comment]
I find that the problem is on the use of URLBreaks I defined in previous manuscript. 

```
\documentclass[sigconf]{acmart}
\usepackage{url}

\def\UrlBreaks{\do\/\do-}
\renewcommand{\UrlBreaks}{\do\/\do-\do:\do\a\do\b\do\c\do\d\do\e\do\f\do\g\do\h\do\i\do\j\do\k\do\l\do\m\do\n\do\o\do\p\do\q\do\r\do\s\do\t\do\u\do\v\do\w\do\x\do\y\do\z\do\A\do\B\do\C\do\D\do\E\do\F\do\G\do\H\do\I\do\J\do\K\do\L\do\M\do\N\do\O\do\P\do\Q\do\R\do\S\do\T\do\U\do\V\do\W\do\X\do\Y\do\Z}

\begin{document}
\title[short titlle]{title}
\maketitle

text \url{http://www.bfk.de/bfk_dnslogger_en.html}

\end{document}

```

With the use of UrlBreaks for old template, the underscore in url would be explained as subscript:
<img width="877" alt="2017-04-11 14 05 24" src="https://cloud.githubusercontent.com/assets/6439915/24923632/2181dc5e-1ec0-11e7-80f7-1c90afb49865.png">

I delete the UrlBreaks and now the problem has gone.
