### ISSUE TITLE
The word "Proof" is not included in proofs with an optional argument [name]

### ISSUE THREAD

**Issue by kostis** [borisveytsman/acmart#140]
The issue is explained in the following `.tex` file (and the generated `.pdf` which is attached).  Besides being weird, the behavior differs from what one gets if the old ACM style file (`acmsmall.cls`) is used.  I consider this a bug.  Note that optional arguments work OK in theorems, but not in proofs.

```tex
\documentclass[format=acmsmall, review=false, screen=true]{acmart}

\begin{document}

\section{Section Showing a Bug in Proofs with an [Optional] Argument}

This section contains two theorems with their proofs.
\begin{theorem}[First]\label{thm:first}
  This is the first theorem...
\end{theorem}

\begin{proof}
  It is immediately followed by its proof.
\end{proof}

\begin{theorem}[Second]\label{thm:second}
  This is the second theorem...
\end{theorem}

There is a need to put some text here, ... perhaps much text ..., and hence
there is a need to use an optional argument in the \texttt{begin\{proof\}} ...
\texttt{end\{proof\}} block below so that this is clear what this is a proof of.

\begin{proof}[of Theorem~\ref{thm:second}]
  This ``proof'' has a bug because the word \textsc{Proof} has disappeared!
  The behaviour is not what one gets if the old ACM journal style file is used.
  There, the word \textsc{Proof} is included.
\end{proof}

\end{document}
```

[proof_bug.pdf](https://github.com/borisveytsman/acmart/files/921696/proof_bug.pdf)

**Comment by borisveytsman** [comment]
This is not a bug, but a feature.  You can easily write `\begin{proof}[Proof of Theorem~\ref{thm:second}]`.  However, now you also can write `\begin{proof}[Direct proof of Theorem~\ref{thm:second}]`,  `\begin{proof}[Computational proof of Theorem~\ref{thm:second}]` etc., creating the proof names which were not easily available before.

**Comment by kostis** [comment]
Of course I can write the word "Proof" manually (and live with this as a solution), but this `feature' means that I need to write something different when using `acmart.cls` and many other class files, including the old ACM style files. It also means that the proof environment does not behave `similarly' to theorem, definition, etc. which may break the `principle of least astonishment'. (Yes, I know it's slightly different since it adds a \qed at the end.)

Anyway, writing all these here just as something to think about.

**Comment by borisveytsman** [comment]
Well, most people working with math use `amsart` or `amsmath`.  Not adding "Proof" to the custom proof name is their behavior.  Thus ACM now follows the widespread custom.
