### ISSUE TITLE
Website reference (ACM-Reference-Format.bst)

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#142]
This is partly a style question, but the current `ACM-Reference-Format.bst` does not nicely handle a reference to a website/webpage without an author and date.  For example, many project websites do not have a distinct author or (copyright) date.  Similarly, in such a reference, the URL is the key content, and isn't served well by relegation to a "Retrieved <date> from <url>." note.  For example, how might a bibliographic entry for the following be crafted:
```
We compare our system to that of Manticore.~\cite{ManticorePaper1,ManticorePaper2,ManticoreWebsite}.
```

Something like
```
@misc{ManticoreWebsite,
  note = "\url{http://manticore.cs.uchicago.edu}",
  title = "The Manticore Project",
}
```
leaves an awkward "(????)" for a missing year; also, it gets sorted to the beginning of the references.

@Craig-Rodkin

**Comment by borisveytsman** [comment]
There are two issues here.

1.  In the author-year style one expects the publications to have authors.  The cludge `autthor = {Anon}` is a cludge, but it is a common practice.

2.  So far ACM insisted on years for all publications - if the year is unknown, the form `year = {2005?}` is acceptable.

I can implement other decisions, but I need ACM to make the decisions themselves.

**Comment by MatthewFluet** [comment]
One problem with using Anon, at least for submissions with double-blind reviewing, is that it is sometimes used to reference a work by the authors.

**Comment by Craig-Rodkin** [comment]
I heard back from staff. They are in agreement with Matthew.  For websites, please make the year and author optional. 

Thanks

**Comment by borisveytsman** [comment]
How should the entry be formatted if it does not have author and/or year?  Can you give me some examples?

**Comment by Craig-Rodkin** [comment]
I’ve asked ACM’s journals manager for examples. Will send ASAP.

Regards,

-Craig

Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>
http://member.acm.org/~rodkin

Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service<http://www.acm.org/publications/acm-author-izer-service>

**Comment by Craig-Rodkin** [comment]
Here' are the formats:

Website name. Page name. Retrieved from www.URL.com.

or 

Website name. n. d. Page name. Retrieved from www.URL.com.


n. d. = no date

As per copyediting manager:  **_although many websites don’t show a copyright year at the bottom of the page, you can view the page properties to see when the page was last modified, in which case that would be the year that you could use in the reference._**

**Comment by borisveytsman** [comment]
C> Date: Fri, 28 Apr 2017 10:50:51 -0700
C> From: Craig-Rodkin <notifications@github.com>


C> Website name. Page name. Retrieved from www.URL.com.

C> or 

C> Website name. n. d. Page name. Retrieved from www.URL.com.


C> n. d. = no date

Done

-- 
Good luck

-Boris

We are drowning in information but starved for knowledge.
		-- John Naisbitt, Megatrends

**Comment by ianfoster** [comment]
Did this issue get addressed? Currently I get things like this, which looks horrible: 

[n. d.]. List of File Formats. ([n. d.]). Retrieved March 1, 2018 from https: //en.wikipedia.org/wiki/List_of_ le_formats

when using:

@misc{wikipedia,
    title   = "List of File Formats",
    url = {https://en.wikipedia.org/wiki/List_of_file_formats},
    lastaccessed = {March 1, 2018}
}

I can add a year = 2018, which is somewhat artificial, and then get the following, which isn't much better:

2018. List of File Formats. (2018). Retrieved March 1, 2018 from https://en.wikipedia.org/wiki/List_of_ le_formats

**Comment by Craig-Rodkin** [comment]
This was addressed by ACM’s editorial staff. We now have the following style for online documents:
(for a complete list, please see: https://www.acm.org/publications/authors/bibtex-formatting)
For an online document/WWW resource:Website year can be found at the bottom of the website page or by viewing page properties/source to see when the page was last modified.

  *   @online{Thornburg01,
author ={Harry Thornburg},
year = {2001},
title ={Introduction to Bayesian Statistics},
url ={http://ccrma.stanford.edu/~jos/bayes/bayes.html},
month ={mar},
lastaccessed ={March 2, 2005},
}

  *   @misc{ acm:###,
author = {ACM},
title = {Association for Computing Machinery: Advancing Computing as a Science & Profession},
url = {http://www.acm.org/}
}

  *   @misc{ wiki:###,
author = {Wikipedia},
title = {{W}ikipedia{,} The Free Encyclopedia},
year = {2017},
url = {https://www.wikipedia.org/}
}


Regards,

-Craig

Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>
http://member.acm.org/~rodkin

Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service<http://www.acm.org/publications/acm-author-izer-service>

**Comment by dongxiao92** [comment]
@Craig-Rodkin 
All the above three examples have author. What if there is no obvious author, like a github project?

**Comment by tnull** [comment]
I've run into the same problem, without an explicit autor, I get entries like this:

    2019. The Go Programming Language. Retrieved September 23rd, 2019 from https://golang.org

Is there any solution in sight when one does not want to supply an artificial author?
