### ISSUE TITLE
Citation style (with some urgency for SIGGRAPH 2017)

### ISSUE THREAD

**Issue by hullin** [borisveytsman/acmart#143]
ACM-Reference-Format.bst may need a tiny bit more attention. In l.1167f, the style lists all authors by full given names {ff } followed by last name, although the comment a few lines above says otherwise. This causes the bibliography to be swamped in given names, wasting a lot of space and causing a quite inconsistent overall look since there are always some bib entries that only provide the initials. After changing {ff } to {f. } the result, at least to me, looks much smoother.

This version seems like a good working solution to me:

```
{"\bibinfo{person}{" s nameptr "{vv }{ll, }{f.}{, jj}" format.name$ * "}" * 't := }
{"\bibinfo{person}{" s nameptr "{f. }{vv }{ll}{, jj}" format.name$ * "}" * 't := }
```

Kind regards,
Matthias

**Comment by Craig-Rodkin** [comment]
In reviewing reference sections in published articles, I see inconsistency in output...even within an article. I will consult with relevant staff and get back to everyone shortly.

**Comment by Craig-Rodkin** [comment]
ACM wants the full first name but we cannot insist on it because authors do not always have the information. 

The .bst should never truncate what is supplied for either first or middle, but it cannot require the full names.

Since having the full name helps ACM resolve references (benefit for all authors) and normalize authors names in the ACM Digital Library, the full name is preferred despite the extra space required.

**Comment by borisveytsman** [comment]
Well, looks like ACM has a policy...

**Comment by hullin** [comment]
ll.1167-1168 still lists first author the same as remaining authors, first name(s) followed by last name.

**Comment by borisveytsman** [comment]
Yes, and this is what ACM instructed me to keep.

**Comment by MatthewFluet** [comment]
I think that @hullin's last comment (and now #145) are noting that the `format.names` function includes the comment:
```
  % Format bibliographical entries with the first author last name first,
  % and subsequent authors with initials followed by last name.
  % All names are formatted in this routine.
```
but the actual formatting does not treat the first author differently from subsequent authors.
