### ISSUE TITLE
bullets tabbed too far to the right in itemized list and ACMTOG style

### ISSUE THREAD

**Issue by schro20** [borisveytsman/acmart#144]
My guess is that the amount of indentation for the bullets in an itemized list is correct for a single column format. For the two column format of TOG the amount of indentation is too much. Obviously that is an aesthetic judgment, but I don't believe it should be controversial.

**Comment by Craig-Rodkin** [comment]
This is a design implementation issue which needs to be put forth to the stakeholders who are governing the templates. I will bring your request to their attention.
