### ISSUE TITLE
reconsider style decision: First name last name in bibliography

### ISSUE THREAD

**Issue by schro20** [borisveytsman/acmart#145]
In TOG style the bibliography is alphabetical by last name. However the typesetting puts the first name before the last name. This makes it visually tedious to search for a paper by author's last name.

**Comment by Craig-Rodkin** [comment]
This is the ACM style which has been in place for journal and proceedings for decades.  While we will not make the change at this time, I will record your recommendation for future review by the staff and volunteers.

**Comment by jowens** [comment]
Here's a 2016 SIGGRAPH paper: ![diffractiveachromat_peng2016_low-res_pdf](https://cloud.githubusercontent.com/assets/976970/25689497/75970af6-303d-11e7-8667-eda9fcda6cc2.png)

and a 2015 TOG paper: ![occluded_pdf](https://cloud.githubusercontent.com/assets/976970/25689506/8af8ba84-303d-11e7-99d0-227054284dc2.png)

(I picked the first of each type from http://kesen.realtimerendering.com/sig2016.html)

@Craig-Rodkin, what am I missing here?

**Comment by schro20** [comment]
It may also be worth pointing out that even if this had been the convention for a long time (perhaps for other ACM publications? certainly not for TOG) it is still a bad idea. We could run a quick user study asking people to locate a reference entry and see how long they take with the two conventions. I am confident on putting my money on the "last, f." version to beat out the "first last" version. We should be aiming for the best UI we can. If tradition has done it badly, let's be open to the data and change things.

**Comment by jowens** [comment]
@Craig-Rodkin, can you address this with respect to the screen shots I made above? Just FYI, I have a 2009 TOG in front of me (SIGGRAPH 2009) and it also puts last names first. I guess I respectfully disagree with "in place ... for decades".
