### ISSUE TITLE
Option for a compact paper header

### ISSUE THREAD

**Issue by fanchyna** [borisveytsman/acmart#146]
Is there an option for a compact paper header? So instead of doing 
author1                author2
affiliation1           affiliation2
email1                  email2

do
author1*, author2**
* affiliation1
** affiliation2
email1,email2

The second one is useful (and looks better) when there are many authors (>=4) and most authors have the same affiliation and share the same email domain. In fact, this format is still popular in many conference and journal templates.

**Comment by borisveytsman** [comment]
This option is not  implemented right now because it is not in the design.  I will ask ACM whether they want this option.

**Comment by fanchyna** [comment]
It would be nice if this is implemented because many authors manually modify the ACM template into this format and the papers were acceptable.

**Comment by Craig-Rodkin** [comment]
ACM and the group of volunteer leaders who worked on the consolidation effort have set and will set the ACM template standard moving forward. We need all authors to follow this format in order to get their articles published. 

Previously, proceedings editors and program chairs did not scrutinize PDFs enough ensure authors adhered to the template standards created within the TeX .cls file. 

The goal is to have ALL published articles have the same ACM look and feel and not to have author specific variations.

Moving forward, ACM will be enforcing the standard output via a production management system. Deviating from the layout specs will not be allowed and authors will be required to correct and resubmit.

We are always looking for author feedback to bring to the volunteers. I will certainly bring your suggestion to the volunteers as part of a larger template review process.

**Comment by schro20** [comment]
Thank you Craig. Please add: (1) the type is too small in the bibliography relative to the rest of the paper; (2) having a bibliography ordered by last name but printed with first name first makes for exhausting scanning of the bibliography when one is looking for something (I would consider this an example of a bad UI...); (3) bullets in itemized lists (in the double column SIGGRAPH format) are indented too far; (4) spacing between the last author in the title and the abstract should be different visually from the spacing between multiple lines of authors; (5) in the theorem environment the space between the (optional) theorem title and the start of the theorem text is too tight. There are also problems with the fonts. For example, \ldots are too large. super and subscripts in math mode are too large relative to their parent size. Do you have any typographers or layout designers on your team of volunteers?

**Comment by drt24** [comment]
@Craig-Rodkin I am currently struggling to find a way to get the authors list to display in a way that does not look stupid when I have 5 authors with the same institution and one email address (Firstname.Lastname@example.com). If I provide full affiliation information (department, institution, country) and share all this then I get one column with 9 lines in the middle of the page:

    author1
    author2
    author3
    author4
    author5
    department
    institution
    country
    email

This looks silly and wastes lots of white space on either side of this central column. The guidance recommends repeating affiliation for each author. However, when the affiliation is the same this is confusing as the reader is left to check if there are any differences. It also makes the whole thing take up far too much space (10 lines):

    author1            author2             author3
    department         department          department
    institution        institution         institution
    country            country             country
    email              email               email
             author4              author5
             department           department
             institution          institution
             country              country
             email                email

What I want to do and have been able to do in the past is (6 lines):

    author1            author2            author3
             author4              author5
                      department
                      institution
                       country
                        email

What people seem to be doing to cope with this is to drop everything except the institution:

    author1            author2           author3
    institution        institution       institution
             author4                author5
             institution            institution

However, that means that a whole load of metadata is missed out and the reader is left without the email addresses of the authors etc.

**Comment by JensLincke** [comment]
@Craig-Rodkin I have a paper with 9 author's. What shall I do?

**Comment by borisveytsman** [comment]
Looks like this is something that should be solved on the ACM editors level...
