### ISSUE TITLE
old fonts

### ISSUE THREAD

**Issue by bargteil** [borisveytsman/acmart#148]
The new fonts aren't pretty.  The text font is okay (though I prefer Times), but the math font is very difficult to read.

+% \begin{macro}{\if@ACM@oldfonts}
+% \changes{v1.33}{2017/04/26}{Added macro}
+%   Whether we use old fonts
+%    \begin{macrocode}
+\define@boolkey+{acmart.cls}[@ACM@]{oldfonts}[true]{%
+  \if@ACM@oldfonts
+    \PackageInfo{\@classname}{Using old fonts}%
+  \else
+    \PackageInfo{\@classname}{Using new fonts}%
+  \fi}{\PackageError{\@classname}{Option oldfonts can be either true or
+    false}}
+\ExecuteOptionsX{oldfonts=false}
+%    \end{macrocode}
+%
+% \end{macro}

@@ -2549,11 +2583,14 @@ Computing Machinery]
 % We use Libertine throughout.
 %    \begin{macrocode}
 \if@ACM@newfonts
+\if@ACM@oldfonts
+\else
 \RequirePackage[tt=false, type1=true]{libertine}
 \RequirePackage[varqu]{zi4}
 \RequirePackage[libertine]{newtxmath}
 \RequirePackage[T1]{fontenc}
 \fi
+\fi
 %    \end{macrocode}
 %
 % The SIGCHI extended abstracts are sans serif:

**Comment by borisveytsman** [comment]
As Craig wrote here, https://github.com/borisveytsman/acmart/issues/146, ACM really wants the distinct look and feel on all its publications.  The fonts were selected by ACM editors, and I am not empowered to change their design guidelines :(

**Comment by borisveytsman** [comment]
I guess I can close the issue until ACM decides to change fonts
