### ISSUE TITLE
bold paragraphs and sub subsection headings

### ISSUE THREAD

**Issue by bargteil** [borisveytsman/acmart#149]
The italicized headings are too easy to miss when scanning through a paper.  Bold ones are more obvious.  Also the spacing after the numbering for subsubsections is a bit too wide.

+% \begin{macro}{\if@ACM@boldparagraph}
+% \changes{v1.33}{2017/04/26}{Added macro}
+%   Whether we use bold paragraph and subsubsection headings
+%    \begin{macrocode}
+\define@boolkey+{acmart.cls}[@ACM@]{boldparagraph}[true]{%
+  \if@ACM@oldfonts
+    \PackageInfo{\@classname}{Using bold paragraph and subsubsections headings}%
+  \else
+    \PackageInfo{\@classname}{Using italic paragraph and subsubsection headings}%
+  \fi}{\PackageError{\@classname}{Option boldparagraph can be either true or
+    false}}
+\ExecuteOptionsX{boldparagraph=false}

@@ -5239,10 +5276,17 @@ Computing Machinery]
   {-.5\baselineskip \@plus -2\p@ \@minus -.2\p@}%
   {-3.5\p@}%
   {\@subsubsecfont\@adddotafter}}
+\if@ACM@boldparagraph
+\newcommand\basicsubsubsection{\@startsection{subsubsection}{3}{0pt}%
+  {-.5\baselineskip \@plus -2\p@ \@minus -.2\p@}%
+  {-3.5\p@}%
+  {\@subsubsecfont\@adddotafter}}
+\renewcommand\subsubsection[1]{\basicsubsubsection{\hspace{-.625em}#1}}
 \renewcommand\paragraph{\@startsection{paragraph}{4}{\parindent}%
   {-.5\baselineskip \@plus -2\p@ \@minus -.2\p@}%
   {-3.5\p@}%
   {\@parfont\@adddotafter}}
+\fi
 \renewcommand\part{\@startsection{part}{9}{\z@}%
   {-10\p@ \@plus -4\p@ \@minus -2\p@}%
   {4\p@}%
@@ -5274,6 +5318,10 @@ Computing Machinery]
 \def\@subsecfont{\sffamily\bfseries\section@raggedright}
 \def\@subsubsecfont{\sffamily\itshape}
 \def\@parfont{\itshape}
+\if@ACM@boldparagraph
+\def\@subsubsecfont{\sffamily\bfseries}
+\def\@parfont{\bfseries}
+\fi
 \setcounter{secnumdepth}{3}
 \ifcase\ACM@format@nr
 \relax % manuscript

**Comment by borisveytsman** [comment]
I am very sorry, but this is again the policy of ACM;  please see Craig's reply at https://github.com/borisveytsman/acmart/issues/146
