### ISSUE TITLE
Redundant year in bibliography

### ISSUE THREAD

**Issue by keenancrane** [borisveytsman/acmart#151]
Many bibliography entries show the year twice.  For instance, the bib entry

```
@article{Cheung,
   author = {Kenneth Cheung and Tomohiro Tachi and Sam Calisch and Koryo Miura},
   title = {Origami interleaved tube cellular materials},
   journal = {Smart Materials and Structures},
   volume = {23},
   number = {9},
   year = {2014}
}
```

gets rendered as

![redundant_year](https://cloud.githubusercontent.com/assets/3604525/25555620/74c9adc2-2cb9-11e7-98b1-0533e22b3918.jpg)

I suspect this is happening because the ACM reference format specifies that the journal month and year should follow the volume and number:

https://www.acm.org/publications/authors/reference-formatting

But in a case where the publisher does not associate a month with a given issue, it's not clear whether or not re-printing the year (sans month) is the correct behavior.

**Comment by borisveytsman** [comment]
This is how ACM wants it.
