### ISSUE TITLE
Can't use package url with hyphens option

### ISSUE THREAD

**Issue by mcanini** [borisveytsman/acmart#152]
url package is loaded by the class (via hyperref, I think).
however, I find it useful to load url with the hyphens option.
is there a way to pass it down to the class?

or it might be useful to add \RequirePackage[hyphens]{url} before hyperref is loaded?

**Comment by MatthewFluet** [comment]
See #103 and 28285e2.

**Comment by borisveytsman** [comment]
Doe sMatthewFluet's   suggestion in #103 works for you?

**Comment by mcanini** [comment]
Yes, having a hook file would work.

**Comment by borisveytsman** [comment]
Ok, then I close the issue.  Thanks!
