### ISSUE TITLE
Unable to load fontspec with the acmart class

### ISSUE THREAD

**Issue by AlexisBRENON** [borisveytsman/acmart#156]
Hi,

I'm using `lualatex` to compile my document. I would like to use the `fontawesome` package. However, `fontawesome` relies on `fontspec` and loading this package cause an error.

Example:
This works without any error.
```
\documentclass{article}
\usepackage{fontspec}
\begin{document}
\end{document}
```

This rise an error:
```
\documentclass{acmart}
\usepackage{fontspec}
\begin{document}
\end{document}
```

Log is available here: https://gist.github.com/AlexisBRENON/1c834fcb4c342793c598e19adae478bc

Ignoring the error will generate the document without any problem, but I ❤️ when my log doesn't contain any warning or error...

Thanks,
Alexis.

**Comment by borisveytsman** [comment]
I have not ported `acmart` to lualatex yet.  Pdflatex can use `fontawesome` without problems and compiles fine.

**Comment by AlexisBRENON** [comment]
OK. I'll stick to Pdflatex for the moment. Maybe adding just one line in the documentation to say that `acmart` is not compatible with lualatex could be great.

Thanks for the answer.

**Comment by borisveytsman** [comment]
I'd rather make it compatible :)

I will close this issue.  If you wish, please open an issue "Make acmart compatible with lualatex"
