### ISSUE TITLE
how to NOT abbreviate a citation

### ISSUE THREAD

**Issue by stephennspencer** [borisveytsman/acmart#159]
In my .bib file I have 

@misc{CyberCANOE,
  year = 2014,
  ... the rest of the bib entry
}

and when I cite this I see [Cyb 2014] but I'd like to see [CyberCANOE 2014]. Is there a way I can do this?

Thanks!

Best,
Stephen

**Comment by borisveytsman** [comment]
There is a field `key` for this purpose

```
@misc{CyberCANOE,
   year = 2014,
   key={CyberCANOE}
}
```
