### ISSUE TITLE
overfull hboxes, no apparent place to break

### ISSUE THREAD

**Issue by stephennspencer** [borisveytsman/acmart#160]
In Section 2, and again in the Acknowledgments section of this document, there are overfull hboxes, and I'm not sure how to counsel the author to resolve these issues.
[0321-yamazaki.pdf](https://github.com/borisveytsman/acmart/files/1005393/0321-yamazaki.pdf)

[hapbeat_newformat.tex.txt](https://github.com/borisveytsman/acmart/files/1005395/hapbeat_newformat.tex.txt)

Any thoughts?

ps: Would it be appropriate to allow files with ".tex" file suffix to be uploaded?

**Comment by borisveytsman** [comment]
Sometimes the only remedy is rewriting.  For example, in the Acknowledgements changing the phrase to "This work was supported by JSPS KAKENHI by Grant Number JP17H01774."  (added 'by') solves the issue.
