### ISSUE TITLE
Could sigconf, anonymous leave space for the authors?

### ISSUE THREAD

**Issue by cmacdonald** [borisveytsman/acmart#162]
Hi,

A feature request: when using anonymous mode, the template does not leave a gap equal to the size of the authors. This means that the spacing/pagination of the paper has to change once it is accepted. It would be great if anonymous mode left an appropriately sized gap below "Anonymous Authors(s)", at least equal to one row of authors.

Craig

**Comment by cmacdonald** [comment]
Agreed. But if I have to meet a page limit, loosing 2 large paragraphs because I didn't _estimate_ correctly the size of the author block is a particular frustration. Its more significant than minor tweaks to wording that might be requested by reviewers.

**Comment by borisveytsman** [comment]
Craig, I wanted to do this, but was overruled:  I was told that the number of authors might give too much info to the reviewer.   

The author should typeset the paper in the non-anonymous mode to estimate the number of pages, and use anonymous mode only for reviewers.

**Comment by cmacdonald** [comment]
Hi Boris

Thanks for the confirmation.

I guess another option could be leaving a "default" amount of space - author, 2 lines of address, email - which would not give the game away.

**Comment by borisveytsman** [comment]
I am not sure it would not just confuse people...

**Comment by cmacdonald** [comment]
I would argue that was the status quo in sig-alternate.cls for the last umpteen years! The new one is also confusing.

**Comment by fmatheus** [comment]
The expression "Anonymous Author(s)" sounds a little misleading, may "Author(s) omitted for blind review" would be more accurate.

**Comment by tylermenezes** [comment]
It would be nice if this were available as an option. SIGCSE for one does not support anonymous mode:

> 1. A block for each author of the paper is required, so if there are 5 authors, then, this will be done with 3 authors in one row and the other two in the following row. See the PDF of the LaTeX template for a visual example. 
> 
> ...
> As a reminder, submissions need to be as close to the final publishable paper as possible. This means they should include all elements of such a publication and space for each author name so that the text would not need to be reduced to produce the final version of the paper.

(They also request that the Acknowledgements heading be present with placeholder acks text, also not emitted by anonymous mode right now)
