### ISSUE TITLE
Compatibility between DOI and  the information provided by ACM 

### ISSUE THREAD

**Issue by gvdgdo** [borisveytsman/acmart#163]
I have been involved in the creation of the proceeding of an ACM conference. In the instruction form ACM after one completes the right management form they include the snippet:

```
\copyrightyear{2017}
\acmYear{2017}
\setcopyright{acmlicensed}
\acmConference{ICAIL '17}{June 12-16, 2017}{London, United Kingdom}
\acmPrice{15.00}
\acmDOI{http://dx.doi.org/10.1145/3086512.3086513} 
\acmISBN{978-1-4503-4891-1/17/06}
```

The problem is with `\acmDOI` because it produces `https://doi.org//http://dx.doi.org`, i.e., repetition of the domain name (`http://doi.org`).

Please coordinate with ACM to solve this issue.

**Comment by borisveytsman** [comment]
ACM says this issue was solved some time ago with the new authors' insrtructions published.

**Comment by gvdgdo** [comment]
Sorry to disagree, but the style manual specifies to use `\acmDOI{doi number without doi domain}` but, up to one week ago, the ACM Right Management creates (legally binding) Copyright/License agreements that specify to use `\acmDOI{doi with http and doi domain}`.

**Comment by Craig-Rodkin** [comment]
Hello Guido Governatori, thank you for your concern regarding the instructions we are providing authors. 

ACM is now in a transition phase moving from an older set of class files (ACM TeX template .cls version 2.8) to the current consolidated class file (new ACM Consolidated TeX template Version 1.3 and above).

During this transition phase, we are still supporting the old templates and must provide instructions for both the older and newer templates. This is where the confusion might be. 

The instructions for the new template Version 1.3 and above provide "\acmDOI{10.1145/...}"

the instructions for TeX template .cls version 2.8 and Microsoft Word provide "\doi{http://dx.doi.org/10.1145/...}"

I hope this clear this matter up for you.
