### ISSUE TITLE
URL is not displayed for @online bibliography entry

### ISSUE THREAD

**Issue by philip-bl** [borisveytsman/acmart#164]
Here is my minimal example: https://www.sharelatex.com/project/5922173828c65ed52009b110
Reproducet it on https://www.sharelatex.com and on my local system with arch linux and latest texlive packages.
I tried it with formats *manuscript* and *sigconf*. It only displays name, date and title. It also reports the following warning:

```
warning: entry type for "github:nt2" isn't style-file defined
```

**Comment by borisveytsman** [comment]
In your example you use the line `\bibliographystyle{humannat}`.  Please change to `\bibliographystyle{ACM-Reference-Format}`.
