### ISSUE TITLE
Error in creating pdf using dvipdf and ps2pdf commands when using review mode

### ISSUE THREAD

**Issue by sranjanus** [borisveytsman/acmart#165]
I am able to create pdfs of the new document templates with the dvipdf and ps2pdf with the class inputs set to
documentclass[acmtog, anonymous]{acmart}
but as soon as review is added
documentclass[acmtog, review, anonymous]{acmart}
I can no longer convert to pdfs with these commands.

The specific error is  (omitted all the stack output :):
Error: /undefined in XC@ACMRed
GPL Ghostscript 9.15: Unrecoverable error, exit code 1

**Comment by borisveytsman** [comment]
Looks like a bug in `xcolor`.  Ok, will enable a workaround
