### ISSUE TITLE
Cannot reference labels in section titles that are all-caps

### ISSUE THREAD

**Issue by iliyang** [borisveytsman/acmart#170]
I have a document that uses
```latex
\documentclass[format=acmsmall]{acmart}
```
where section titles are all-caps. Whenever I declare a section that references something:
```latex
\section{Derivation of \ref{eq:Something} from Section \ref{sec:OtherThing}}
```
the references cannot be resolved and I get warnings like this:
```
/.../main.tex:225: Package hyperref Warning: Token not allowed in a PDF string (Unicode):(hyperref)                removing `\hbox' on input line 225.
```
But if above I change `\section` to `\subsection` (whose title is now *not* all caps), then everything works. I believe this is a problem with the template. A discussion on the same issue but with the `memoir` class can be found [here](https://tex.stackexchange.com/questions/99712/cross-reference-in-section-title-broken-in-header).

**Comment by krono** [comment]
I think this is a general problem in LaTeX with [fragile commands](https://tex.stackexchange.com/questions/4736/what-is-the-difference-between-fragile-and-robust-commands#4747)


You could try either 

```LaTeX
\section{Derivation of \protect\ref{eq:Something} from Section \protect\ref{sec:OtherThing}}
```

so as to manually protect the refs or

```LaTeX
\section{Derivation of \texorpdfstring{\ref{eq:Something}{REPLACEMENT FOR reference} from Section \texorpdfstring{\ref{sec:OtherThing}{SECTIONNAME}}
```

Other than that, it is typically not advisable to put crossreferences into section headings, as they will be used in other contexts beside the mere printing.

**Comment by iliyang** [comment]
I tried both suggestions, here's how the second looks:
```latex
\section{Derivation of Equation~\texorpdfstring{\eqref{eq:ExpansionGeneric}}{bla}}
```
But neither work, and emit the same error:
```
/.../main.tex:228: LaTeX Warning: Reference `EQ:EXPANSIONGENERIC' on page 4 undefined on input line 228.
/.../main.tex: LaTeX Warning: There were undefined references.
```
If I capitalize the label (as the error suggests to try), then it works. But why does it insist on the label being capitalized?

Actually, I really don't like those all-caps titles. Since this is for my own technical report, I'd prefer to have titles with traditional capitalization. Is there any way to turn capitalization off?

**Comment by borisveytsman** [comment]
Well, uppercasing of section titles is prescribed by ACM, so here I cannot help you.  I can, however, prevent uppercasing of references - see the next commit.

**Comment by iliyang** [comment]
Thanks for the fix, I'll wait for the new package release in TeX Live to see if it solves my problem.

Regarding the uppercasing, I understand it's prescribed by ACM. I was just wondering if an option could be added in the template (e.g. a macro) to disable it when the document being compiled is not for an ACM submission.
