### ISSUE TITLE
spacing in "algorithm" environment

### ISSUE THREAD

**Issue by stephennspencer** [borisveytsman/acmart#171]
In the "algorithm" environment, the enclosing box overlaps line numbers when the line numbers get to double digits. (See LaTeX source and PDF.)
[spencer.pdf](https://github.com/borisveytsman/acmart/files/1072161/spencer.pdf)

[spencer.txt](https://github.com/borisveytsman/acmart/files/1072164/spencer.txt)

(Also, why wouldn't ".tex" be an appropriate file upload type?)

**Comment by borisveytsman** [comment]
I guess this is the `algorithm2e` issue.  I got better results by changing the skip between the numbers and the text:

```
\usepackage[linesnumbered,lined,boxed,commentsnumbered]{algorithm2e}
\SetNlSkip{.3em}
```

**Comment by borisveytsman** [comment]
I think I will close it unless my solution does not work for you
