### ISSUE TITLE
Sorting articles by the same first author then by year

### ISSUE THREAD

**Issue by AvengerDr** [borisveytsman/acmart#175]
Hi, as the title says, articles that have the same first author are just sorted by title. Can this be fixed?

**Comment by borisveytsman** [comment]
Can you provide an example?  I thought I was sorting by author and then by year...

**Comment by AvengerDr** [comment]
Sure, have a look at the following picture. This is with the template downloaded from the ACM website.

![image](https://user-images.githubusercontent.com/4924830/27792991-17c517e2-5ff4-11e7-9b76-4d576f0c1c14.png)

The correct order would be 19, 17, 18.

Reference 17 has in its bibtex a later "month" (ie March) entry, so should appear after 19 (which has January).

**Comment by borisveytsman** [comment]
I disagree.  The sorting is by all authors, and if *all* the authors are the same, the year is used to break the ties.  In your example author collectives are different, and we sort accordingly.

**Comment by AvengerDr** [comment]
I see, well please consider the possibility of forcing the order based on just the first author and month/year. 

Because I hope you agree that the chance that exactly the same authors collaborating together on various papers is very low. At least one or two will change over the years, so that occasion might never present itself in reality.

**Comment by borisveytsman** [comment]
It is common to provide sorting by all authors rather than first author only.
