### ISSUE TITLE
Forcing \subtitle{xxx} in the ACM reference format on the first page

### ISSUE THREAD

**Issue by AvengerDr** [borisveytsman/acmart#176]
I was using the (new?) `\subtitle` command to contain part of the paper's title. The paper has a title like "_xxxx? yyyyy"_. However, if I use `\subtitle{yyyy}`, this part is omitted from the _ACM Reference Format_ citation on the first page. Is there a way to force it?

Because if put yyyy in the `\title` then it overlaps the _Author 1_ part in the header.

Thanks in advance.

**Comment by MatthewFluet** [comment]
You should use
```
\title[xxxx?]{xxxx? yyyyy]
```
The full title (printed on the first page and in the ACM Reference Format) will be "xxxx? yyyyy", but the short title (printed in the header) will be "xxxx?"

**Comment by borisveytsman** [comment]
I agree with @MatthewFluet.  Subtitle is not a part of the title, and is not a part of the reference citation.
