### ISSUE TITLE
doesn't display `\ref` properly

### ISSUE THREAD

**Issue by kirk86** [borisveytsman/acmart#179]
Hi and thanks for this. I just have a quick question, whenever I use `\ref` to reference figures or tables  for some reason which I haven't understood yet I always get `??` the not rendering sing and an a warning about not rendered properly references. BWT the `\cite` command works fine and I can see all my references. Any suggestions on that would be grateful?

**Comment by borisveytsman** [comment]
What happens if you rerun latex?

**Comment by kirk86** [comment]
nothing, same thing as many times as I run latex.

**Comment by borisveytsman** [comment]
Can you post the minimal (non)working example?

**Comment by borisveytsman** [comment]
Looks like the author solved their problem
