### ISSUE TITLE
line numbering with `review=true` does not properly scale with document font size

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#18]

**Comment by borisveytsman** [comment]
I've added a couple of changes to the code, but to tell the truth this numbering was never intended to be exact: it is difficult to achieve due to display material that moves line distances.  Rather, it is a very rough guide to help editors to convey the information to authors.

**Comment by MatthewFluet** [comment]
I guess my description/concern wasn't clear.  I understand that line-by-line alignment isn't the purpose.  Rather, I was observing that `\ACM@linenum` was so carefully set to fill only the text area at the default fontsize, but the line numbers run off the bottom of the page if one uses the `11pt` class option.  Things could be simpler and more uniform (but less pretty) if `\ACM@linenum` was just always set to 99.
