### ISSUE TITLE
Don't load `cleveref`

### ISSUE THREAD

**Issue by mainland** [borisveytsman/acmart#180]
From the `cleveref` documentation:

> The cleveref package must be loaded after all other packages that don’t specifically support it, i.e. the `\usepackage{cleveref}` line should usually be the last `\usepackage` command in your document’s preamble.

In particular, since I use the `listings` package, I have to edit `acmart.cls` to remove the loading of `cleveref` and instead load it myself or references break.

**Comment by MatthewFluet** [comment]
+1

It doesn't seem that `cleveref` is needed for anything provided directly by `acmart`.  I upgraded a system from Fedora 25 to Fedora 26, and consequently many TeX packages updated, and get
```
! LaTeX Error: No counter 'd' defined.
```
errors at a `\begin{definition}` and
```
! LaTeX Error: No counter 'l' defined.
```
errors at a `\begin{lemma}`.

**Comment by rionda** [comment]
Note that cleveref was added in response to #138 .

**Comment by Blaisorblade** [comment]
For those who *don't* want `cleveref` (@MatthewFluet): adding a `cleveref` class option (and make `\RequirePackage{cleveref}` conditional on this option) should be good.

For those who want `cleveref` like @mainland: does `\cref{lemma:xyz}` output "Lemma XYZ" for you (assuming `lemma:xyz` is an actual lemma label)? Given #138, I guess no.

If using `\RequirePackage{listings}` before `\documentclass` doesn't work, I suspect you should load `listings` using `acmart-preload-hook.tex`, following the example in the docs:
https://www.acm.org/binaries/content/assets/publications/consolidated-tex-template/acmart.pdf
If `listings` must be loaded after other packages, those might have to go into that hook as well.

Overall: `cleveref` affects `acmart`'s definitions of theorem styles and commands. So the only alternative (technically) would be to (optionally) move those definitions into a separate package that can be loaded after `cleveref` (or other such packages). Maybe `acmart` could still run this code by default, unless a new option is specified. But such a solution seems more complex to deploy and use. (Worst-case, we could all copy those lines from `acmart` and paste them after loading `cleveref`, but that seems tricky).

**Comment by rionda** [comment]
@Blaisorblade : cleveref works without any problem: \cref{xxx} gives the expected output. #138 is a closed and solved issue.

**Comment by MatthewFluet** [comment]
@Blaisorblade In my case, it isn't whether I want or don't want `cleveref`; it is that on my TeX distribution, simply using a theorem-derived environment yields an error.  But, that's different from the issue reported by @mainland, so I'll open a new one.

**Comment by borisveytsman** [comment]
Thanks for the discussion

Looks like the only option that may satisfy everybody is to 

1.  Put theorem definitions into a separate style
2.  Optionally delay loading the style until the preamble, so the user may load `cleveref` if needed

**Comment by Blaisorblade** [comment]
> Put theorem definitions into a separate style

To avoid a separate sty file, could that be done via the AtBeginDocument hook (maybe what you have in mind already)? I've seen similar tricks in tocbibind.

**Comment by borisveytsman** [comment]
This would be less clean
