### ISSUE TITLE
Support non-ACM pubs (w/o ISBN / DOI) more easily

### ISSUE THREAD

**Issue by mdekstrand** [borisveytsman/acmart#184]
It is common practice for supplementary meetings at ACM conferences, such as workshops and poster proceedings, to use the ACM SIG format for papers, but not to publish in the DL. Such papers do not have DOIs or ISBNs. However, it is quite difficult to remove the DOI / ISBN things from the copyright block.

I am using a locally-modified version of the style to accomplish this for RecSys Poster Proceedings camera-ready papers, but it'd be nice if this could be supported out-of-the-box. I see two decent options:

1. A `nonacm` option that suppresses the 'ACM ISBN' and 'DOI' options; it would function like the `\if@ACM@manuscript` flag in the current copyright block, but would completely suppress that portion of the block instead of saying 'Manuscript submitted'.
2. Detect empty values of `acmDOI` and `acmISBN` to suppress the appropriate portions of the copyright box.

**Comment by borisveytsman** [comment]
I guess your patch closes this

**Comment by gasche** [comment]
I had the same idea and implemented a 'nonacm' option in #282 for this.

Note: I first tried to use empty `\acmPrice{}` and `\acmDOI{}` macros as you did, but that didn't work in the journal format (your patch only covered conference formats), and my proposal removes more things such as the "", Vol. 1, No. 1, Article ." footer.

**Comment by MakarovIA** [comment]
it is not working combined with sigconf option.
is there any way to check the empty or some keyword argument so that it will be ommitted in the final document?

**Comment by ian-fox** [comment]
I'm seeing the same thing as @MakarovIA, in sigchi as well. Compiler output includes a warning:

```
LaTeX Warning: Unused global option(s):
    [nonacm=true].
```

**Comment by borisveytsman** [comment]
What is the class version?  You need 1.54 for nonacm to work

**Comment by ian-fox** [comment]
v2.20.4. `nonacm` seems to work for the classes that start with `acm`, but not the ones that start with `sig`.

**Comment by ian-fox** [comment]
Ah, that's fixed it. Apologies, didn't realize the tool I was using didn't get the latest packages when I installed it.

Interestingly `nonacm` seemed to work just fine for the classes prefixed with `acm`, it was only broken on the ones that started with `sig`. Both are working now though, thanks!
