### ISSUE TITLE
acmauthoryear reference indexing

### ISSUE THREAD

**Issue by bargteil** [borisveytsman/acmart#186]
It would make it much easier to locate references when using acmauthoryear if the first author's last name appeared at the beginning of the bibliographic reference.

**Comment by Blaisorblade** [comment]
👍 , but dup of #154 and #145.

**Comment by borisveytsman** [comment]
It is easy to do, but must be approved by ACM - @craigrodkin

**Comment by kseitz** [comment]
I agree with this comment.  As @jowens notes in #145, SIGGRAPH papers put the last name at the beginning for many years, until the switch to this new template.  @Craig-Rodkin can we get a follow up please (either here or in #145)?  Thanks!
