### ISSUE TITLE
insufficient flexibility with `natbib` option

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#19]
Some features of `natbib` can only be enabled via package options.  In particular, the `sort` and `sort&compress` package options.

Using
```
\documentclass[sigplan, natbib=false]{acmart}
\usepackage[sort&compress]{natbib}
...
```
gives
```
! LaTeX Error: Command \citename already defined.
               Or name \end... illegal, see p.192 of the manual.
```

It also misses out on the other configuration of `natbib` in `acmart.cls` (e.g., `\bibpunct` and `\bibfont`).

**Comment by MatthewFluet** [comment]
One option would be to allow the `natbib` class option to take a list of options to be passed to the `natbib` package:
```
\documentclass[sigplan, natbib={sort&compress}]{acmart}
...
```
This would also make it easy to switch between authoryear and numbers:
```
\documentclass[sigplan, natbib={authoryear,sort&compress}]{acmart}
...
```
or
```
\documentclass[sigplan, natbib={numbers,sort&compress}]{acmart}
...
```

A simple `natbib` or `natbib=true` would be equivalent to `natbib={}`, while `natbib=false` would skip loading `natbib`.

**Comment by borisveytsman** [comment]
Thanks.  I used a slightly different solution: I've added flexiblity to the natbib \setcitestyle command, so you now can use \setcitestyle{super,sort&compress}.  I've updated the docs.

**Comment by MatthewFluet** [comment]
It seems that this solution is rather fragile, relying on internal details of the `natbib` implementation and not robust in the face of future `natbib` options.

**Comment by borisveytsman** [comment]
The problem here is that natbib relies on the way latex processes global options.  This means command like natbib=sort&compress work fine, but natbib={sort&compress,curly} would fail.  It is possible to overcome, but this will be even more fragile...

**Comment by MatthewFluet** [comment]
Do you really mean the way that `natbib` processes global options?  Or did you mean the way that `acmart.cls` processes global options?

**Comment by borisveytsman** [comment]
See Section 5,2 in kvoptions manual for the discussion.

**Comment by borisveytsman** [comment]
Just try passing multiple options to natbib with and without kvoptions-patch loaded, and see the problem here.

**Comment by borisveytsman** [comment]
What is easy to do is to make cumulative options, like \documentclass[sigchi, passtonatbib=sort&compress, passtonatbib=numbers, passtonatbib=super]{acmart}, but this is not very intuitive.

Actually I think that citation customization should be done on the SIG level rather than by the authors, so we can pass options to natbib based on the SIG chosen.

**Comment by MatthewFluet** [comment]
Ah, I didn't realize that option parsing wasn't a local implementation choice of a class/package.

**Comment by MatthewFluet** [comment]
I tend to agree that SIG's should define a good default.  The motivation for more flexibility in the `natbib` option is the following: I tend to think that `sort&compress` is a good default (and it is the default in `sigplanconf.cls`), since the author who doesn't think about the order of references in a `\cite` get's a nice behavior.  But, the sorting is necessarily by author, and some authors who do think about the order of references in a `\cite` and want to sort chronologically don't have an easy way to obtain that behavior.

**Comment by MatthewFluet** [comment]
Anyways, it really seems to be a failing of `natbib` to make `sort` and `compress` accessible from `\setcitestyle`.

**Comment by borisveytsman** [comment]
Well, I've added this ability for the time being.  Natbib seems to be pretty stable, but if it is changed, I will know it first

Unfortunately patching each other's packages is the standard behavior among package writers...
