### ISSUE TITLE
Streetaddress command gets ignored in v1.44

### ISSUE THREAD

**Issue by jpauwels** [borisveytsman/acmart#190]
See for example sample-sigchi.tex, where `\streetaddress{P.O. Box 1212}` has no visible effect in the PDF.

**Comment by MatthewFluet** [comment]
As stated in the class documentation (https://github.com/borisveytsman/acmart/blob/master/acmart.dtx#L583):
```
% Inside these commands you should use \cs{position},
% \cs{institution}, \cs{department}, \cs{city}, \cs{streetaddress},
% \cs{state}, \cs{postcode} and \cs{country} macros to indicate the
% corresponding parts of the affiliation.  Note that in some cases
% (for example, journals) these parts are not printed in the resulting
% copy, but they \emph{are} necessary since they are used by the XML
% metadata extraction programs.
```

**Comment by jpauwels** [comment]
Thing is, it previously used to be printed. Certainly in v1.28 and I believe v1.32 too.

**Comment by jpauwels** [comment]
Okay, I found it in the Changelog as introduced in v1.40. Sorry for the bother.

**Comment by borisveytsman** [comment]
Sometimes my habit of writing detailed comments and logs pays :)
