### ISSUE TITLE
\crefs's in the section titles in the appendix won't work

### ISSUE THREAD

**Issue by ghost** [borisveytsman/acmart#192]
When compiling
```
\documentclass{acmart}
\usepackage{cleveref}
\begin{document}
\section{Main Results}\label{sec:main}
Some theorems.
\appendix
Let's reference the main results: \cref{sec:main}.
\section{Proofs of theorems from \cref{sec:main}}
\end{document}
```
the first reference produces "section 1" as expected, while the second produces question marks.
I guess, this is due to acmart capitalizing too much. Could we, perhaps, kindly ask for a bugfix? Thank you in advance.

**Comment by borisveytsman** [comment]
Cleveref is not easy to support.

Right now you can use  `\section{Proofs of theorems from section~\ref{sec:main}}`

**Comment by LeonMeier** [comment]
Thanks for the notice! (Of course, I'd appreciate it if you or the author of `textcase` could take care of that in the future.)

**Comment by davidcarlisle** [comment]
you can also  use `\NoCaseChange{\cref{...}}`

**Comment by LeonMeier** [comment]
@davidcarlisle The output of 
```
\documentclass{acmart}
\usepackage{cleveref}
\crefname{section}{\S}{\S\S}%%% otherwise you get a small "section"
\begin{document}
\section{Main Results}\label{sec:main}
Some theorems.
\appendix
Let's reference the main results: \cref{sec:main}.
\section{Proofs of theorems from \NoCaseChange{\cref{sec:main}}}
\end{document}
```
is o.k., but the warning 
```
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\new@ifnextchar' on input line 9.
```
is printed. Moreover, in the outline of the PDF file we see "sec:main" rather than "1".

**Comment by borisveytsman** [comment]
@davidcarlisle David, this would be wrong:  the requirement is to have "PROOF OF THEOREMS FROM SECTION 1", and `\NoChangeCase` would give "PROOF OF THEOREMS FROM section 1"

**Comment by vedhasua** [comment]
I stumbled upon your page when looking for a solution, currently facing exactly this issue when using WileyNJD-v2.cls. Please please do let me know if there is fix, if you have figured one already.

Interestingly, 
1. I get "??" in the appendix section title even if I use `\section{Proof for \NoCaseChange{\Cref{mythm}} }` for **_WileyNJD-v2.cls_**. 

2. I get a text (although not pretty looking) e.g. "PROOF FOR Theorem 1" for **_wiley-article.cls_**.

3. With the **_default_** article class (i.e. no explicit `.cls` in the current directory) and with `\documentclass[12pt]{article}` in the preamble I have no issues `Cref`erring to a label in the main paper from the appendix section title, but I loose the desired formatting settings of course.

**Comment by dbogatov** [comment]
I have same problem (year 2021) and workaround so far is using regular `\ref{...}`.
