### ISSUE TITLE
Warning: 'Please load the "caption" package  AFTER babel/frenchb; reported on input line 909.'

### ISSUE THREAD

**Issue by LeonMeier** [borisveytsman/acmart#193]
When processing
```
\documentclass{acmart}
\usepackage[french,american]{babel}
\begin{document}
Some text.
\end{document}
```
pdflatex spits out the following warning:
```
Package frenchb.ldf Warning: Please load the "caption" package
(frenchb.ldf)                AFTER babel/frenchb; reported on input line 909.
```

Given the fact that the above code does not load caption _directly_, this warning looks strange. In particular, there is no hint on what goes wrong if the warning is ignored. I guess, the three packages (babel,caption,acmart) should jive better with each other; don't ask me how.

**Comment by tohecz** [comment]
Well, considering that:
0. this is not a fault of any single one of the three packages;
0. it's easily cured by specifying `\RequirePackage[french,american]{babel}` before `\documentclass`,
I don't think this can qualify as a bug.

And also, I think that the warning itself is a very good hint of what's going on; as you do not load the `caption` package directly, something else is. And as it says that you should load `babel` first, it's hardly `babel` itself that loads it. So by Holmes' logic, it's `acmart` that loads it. Voilà!

**Comment by LeonMeier** [comment]
Running pdflatex on
```
\RequirePackage[french,american]{babel}
\documentclass{acmart}
\begin{document}
Some text.
\end{document}
```
produces an error message:
```
Babel <3.9r> and hyphenation patterns for 54 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
! Missing \endcsname inserted.
<to be read again> 
                   \@classoptionslist 
l.301     \@empty}
                  
? X
```

Moreover, is the original warning just a message without any ill effects? Or is the hyphenation of French (partially or fully) broken? Or only broken in captions? Do quotation marks change their meaning?

An aside: after having looked at the code, we know that caption is loaded inside acmart. However, simply by looking at the real-size main file with dozens of other packages and control statements floating around, but without `\usepackage{caption}`, we wouldn't know where to look for the culprit. We'd have to tediously construct a minimal example.

**Comment by tohecz** [comment]
> We'd have to tediously construct a minimal example.

Indeed, that's the point.

This aside, the fact that you can't load `babel` before `\documentclass` _is_ interesting (unlike the original problem) and probably worth asking the experts!

**Comment by LeonMeier** [comment]
@tohecz Look, we silly users don't know what could be interesting for you great experts. If we see a warning, we feel, ergo, warned. Now, the warning is not overly actionable to us: we neither know whether we can safely ignore it, whether we should reorganize our code somehow, or whether we should try to hack into acmart.

**Comment by borisveytsman** [comment]
This warning is harmless *unless* the main language of your document in French.  If you use Babel just for occasional French fragments, disregard it.

If ACM starts publishing documents with the main language French, we need to return to this issue.
