### ISSUE TITLE
Passing options to microtype and/or hyperref

### ISSUE THREAD

**Issue by LeonMeier** [borisveytsman/acmart#194]
Assuming that I'd like to pass the options
`babel=true, final=true, verbose=errors`
to microtype, is there any standard way to do it without hacking into acmart.cls? As for now, I don't see how to do it.

A similar question concerns passing options to hyperref:
`bookmarks=false, breaklinks=true, pdfborder={0 0 1}, colorlinks=false, hidelinks`.

**Comment by tohecz** [comment]
There are two standard ways how to do this: either try with `\PassOptionsToPackage` or try `\microtypesetup`/`\hypersetup`. (You opened the documentation of `microtype` and `hyperef` to see whether they provide a solution before coming here, right?) If both ways failed, maybe you shall share this information here so that people know.

**Comment by LeonMeier** [comment]
Thx for `\microtypesetup`; I was not aware of that. As for `\hypersetup`, I used it, but there is a clash between the acmart line `\RequirePackage[bookmarksnumbered,unicode]{hyperref}` and my request `\hypersetup{bookmarks=false}`:
```
Package hyperref Warning: Option `bookmarks' has already been used,
(hyperref)                setting the option has no effect on input line 2.
```

**Comment by krono** [comment]
Why do you want to disable bookmarks? They seem mandatory for acmart

**Comment by LeonMeier** [comment]
There was in incompatibility of bookmarks with something else in the past. However, could not recollect the exact reason right now. That's why I closed the bug report.

**Comment by krono** [comment]
ok, I was just curious.

**Comment by qingkaishi** [comment]
I also have the requirement to remove bookmarks because the camera-ready version for the conference ICSE2020 (ACM/IEEE international conference on software engineering) requires us to do so. Is there any convenient way now to close the bookmarks without modifying the acmart.cls?

**Comment by borisveytsman** [comment]
`\hypersetup{bookmarks=false}`

**Comment by qingkaishi** [comment]
> `\hypersetup{bookmarks=false}`

Actually, it does not work. I have to modify the acmart.cls to disable the bookmarks. Thank you all the same.
