### ISSUE TITLE
Title font not bold

### ISSUE THREAD

**Issue by nomeata** [borisveytsman/acmart#197]
The title is not typeset bold; this can already be seen with the `sample-acmsmall.tex` file in the distribution, and the publisher is complaining about that.

May it be an incompatibility with my LaTeX distribution (TeXLive 2016 on Debian unstable)? But it can also be seen on https://www.overleaf.com/latex/templates/association-for-computing-machinery-acm-small-standard-format-template/sksvmbxyfhnw#.WZNpPHVCRjN

**Comment by borisveytsman** [comment]
It looks like a bug with your font system.  Will try to talk to overleaf folks

**Comment by borisveytsman** [comment]
Overleaf people are great. They found the bug in fonts and a workaround!
