### ISSUE TITLE
Indentation for bibliography number 100 and up are not well indented

### ISSUE THREAD

**Issue by studiawan** [borisveytsman/acmart#198]
I am writing a survey paper for ACM Computing Surveys and I include 120 references. However, reference number 100 and up is not well indented in the References section. How to solve this issue?
 
![bib](https://user-images.githubusercontent.com/1132921/29344517-00c591ae-826b-11e7-8cb6-c84c8178e55c.png)

**Comment by borisveytsman** [comment]
Hmmm.  Can you send me your source?  E-mail is fine

Thanks!

**Comment by studiawan** [comment]
Hi, I have sent the latex source of the paper and bib file to your email. Thanks a lot.

**Comment by studiawan** [comment]
The References section is now beautifully indented. Thanks a lot!
