### ISSUE TITLE
Year is displayed twice for journal in References

### ISSUE THREAD

**Issue by studiawan** [borisveytsman/acmart#200]
I just noticed that the year is displayed twice for journal paper in References. Please see image below. However, this issue does not exist for the conference paper.

![1](https://user-images.githubusercontent.com/1132921/29393250-4be2914e-8335-11e7-8563-52ddc4e1e08a.png)

**Comment by MatthewFluet** [comment]
Duplicate of #151.  As noted in that issue, this is how ACM wants journal references formatted.

**Comment by studiawan** [comment]
Thank you for reminding about the previously closed issue.
