### ISSUE TITLE
journal article 1st page changes required

### ISSUE THREAD

**Issue by Craig-Rodkin** [borisveytsman/acmart#205]
Hi Boris,

We have required changes to all journal article 1st pages

The Author Notes and Author Address' data between the separator line (after the introduction) and above the rights information need to be separated into 2 sections

The "Author Notes" needs to remain a free text field
The Authors' addresses format is as follows:
Authors' addresses: FI. MI. LN, full affiliation, complete street address, email address;  FI. MI. LN, full affiliation, complete street address, email address.

I found a good example of the Authors' addresses section which includes 2 authors from the same affiliation. See [https://doi.org/10.1145/2700209] attached article
[a28-chitniss.pdf](https://github.com/borisveytsman/acmart/files/1252782/a28-chitniss.pdf)

**Comment by dbeyer** [comment]
I would like to propose to use another separator line between all the author and title notes and the rights information.

**Comment by Craig-Rodkin** [comment]
A separator line separating rights information is a good idea.

I would leave the title notes and author info as is.

Boris, please implement.
