### ISSUE TITLE
Email editing question (space and add special character)

### ISSUE THREAD

**Issue by nix7965** [borisveytsman/acmart#208]
Hi, I have two questions as follows.

1. Spacing 
I try to add space as follows.
1@abc.com, {2,3,4,5}@cba.com

However, it doesn't work when I try to do as follows.
\email{1@abc.com, {2,3,4,5}@cba.com}

Other than this, I have tried multiple methods. But, they didn't work.
Is there any way to do?

2. Add special character
I try to add some special character such as "\dag"
But, how to add it? I tried this way as follows, but it doesn't work.
\email{1@abc.com $\dag$, {2,3,4,5}@cba.com $\ddag$}

**Comment by borisveytsman** [comment]
Try
```
\email{1@abc.com}
\email{{2,3,4}@cba.com}
```
Note however, that this is *not* recommended, since e-mail is used in the metadata, so you are better off with
```
\email{1@abc.com}
\email[2@cba.com]
\email{3@cba.com}
\email{4@cba.com}
```

**Comment by nix7965** [comment]
Thank you for your response.

About spacing, your suggestion leads to line breaking.
For example, 
\email{1@abc.com}
\email{{2,3,4}@cba.com}

It produces two lines of emails.
"1@abc.com
{2,3,4,5}@cba.com"
- not "1@abc.com, {2,3,4,5}@cba.com" which is written in one line.

If you have some idea, please let me know.

**Comment by borisveytsman** [comment]
Well, the style guidelines I have require e-mails on single lines...

**Comment by nix7965** [comment]
Ok, I understood. I am not familiar with github issue system. So, I think this issue can be closed.

**Comment by nix7965** [comment]
Hi, 

My one of previous questions is how to add special characters. 
By putting the following letters, "\email{1@abc.com $\dag$}"
I wanted to get "1@abc.com†"

I thought "To add footnotes, use \authornote" is the answer. However, it does not work in that way.

Do you have some idea on it?
