### ISSUE TITLE
Problem with compiling sample-sigconf.tex

### ISSUE THREAD

**Issue by elham1296** [borisveytsman/acmart#209]
I am trying to write a paper using your  ACM masterarticle template. 
When I compile sample-sigconf.tex it gives me the following error:

Error: "acmart.cls not found"
I downloaded this file and put it in the directory, now it gives me a lot of errors and warnings.

**Comment by borisveytsman** [comment]
You need to run `latex acmart.ins` to extract the class.  However, it might be a better option to upgrade your TeX installation.

**Comment by borisveytsman** [comment]
I think this issue could be closed
