### ISSUE TITLE
Should option 'review' switch on page numbers as well?

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#216]
Option 'review' prints some line numbers, but no page numbers.
Wouldn't the page numbers be even more important for reviewing?

**Comment by borisveytsman** [comment]
With line numbers being consecutive, why would a reviewer need page numbers?

**Comment by dbeyer** [comment]
The line numbers sometimes do not match the lines of the document.
Therefore, some reviewers prefer to say "fix second line on page 3" instead of
"fix the line that is between lines 234 and 235".

**Comment by rionda** [comment]
(Only partially related) The NIPS style seems to do a particularly good job at matching the line numbers with the text lines...
