### ISSUE TITLE
The third parameter of \acmConference to indicate the address of the conference seems not work

### ISSUE THREAD

**Issue by desert0616** [borisveytsman/acmart#217]
No matter what to fill, it always is ACM, New York, NY, USA.

**Comment by Blaisorblade** [comment]
As a fellow class user: Having seen papers where it works, I expect you'll need to post a Minimal Working Example for people to figure out what is happening.

**Comment by borisveytsman** [comment]
@desert0616  You mean the address in the reference format?  ACM decided recently that, according to the usual practice, the address in the reference format should be *not* the conference address, but the publisher's address.  Which, of course, is New York, NY, USA.

**Comment by desert0616** [comment]
@borisveytsman Noted with thanks.
