### ISSUE TITLE
Balanced double columns

### ISSUE THREAD

**Issue by nico202** [borisveytsman/acmart#222]
Hi, I had to "manually" balance the columns on the last page (references) since I'm asked to keep them balanced.
I could not find an option in this template, so I added
`\usepackage{flushend}`
to my document.
Don't know what is the expected behaviour

Thanks, Nicolò

**Comment by Blaisorblade** [comment]
@borisveytsman I'm sure you know better but I wonder: is `flushend` safe enough, or just another LaTeX hack to balance columns?

The lore is that most approaches are either hard or unsafe — see e.g. https://tex.stackexchange.com/questions/5815/how-to-balance-last-page-of-two-column-layout#comment765413_5817.

Maybe class docs should just recommend options or link to a good discussion?

From `flushend` docs:

> [default] It is used to switch on new version of balancing algorithm. This version has some heuristic guesses for footnotes, floats and section like head skip. So it is more dangerous in the case for text misplace or disappear.

**Comment by Blaisorblade** [comment]
For the record: `flushend` was removed again in https://github.com/borisveytsman/acmart/issues/246#issuecomment-331539399 after causing an infinite loop(!).
