### ISSUE TITLE
Layout issue when authors have >99 references

### ISSUE THREAD

**Issue by Craig-Rodkin** [borisveytsman/acmart#223]
I wanted to bring an issue to your attention that may be a bug in the most recent ACM Latex template. Either that, or there is an option hidden somewhere that I'm unaware of.

I have an accepted paper to CSCW 2018 using the latest acmart, format=acmsmall. The paper has well over 100 citations, but starting at cite 100 in the bibliography the justification of the entries is off. It's clearly an alignment issue: the numbers are aligned assuming numerals of the format [##], but when the numbers become three digits it breaks the justification.

I've attached the bugged pdf to demonstrate the issue.
[main.pdf](https://github.com/borisveytsman/acmart/files/1299387/main.pdf)

**Comment by MatthewFluet** [comment]
Duplicate of #198 and fixed by 29f282e.  Ask the authors to update their version of acmart.

**Comment by Craig-Rodkin** [comment]
Thank you Matthew. I will inform the author.

Regards,

-Craig

Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>
http://member.acm.org/~rodkin

Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service<http://www.acm.org/publications/acm-author-izer-service>

**Comment by Craig-Rodkin** [comment]
Duplicate issue which was resolved. Closing this issue
