### ISSUE TITLE
"artifact evaluated" block

### ISSUE THREAD

**Issue by jowens** [borisveytsman/acmart#23]
Some ACM conferences have artifact evaluation. Artifacts successfully evaluated get a badge. The badge currently goes in the top-right corner of the first page but the new style makes that difficult. Please ensure that there's a uniform solution for "what LaTeX code should conference organizers tell AE authors to put into their papers to display the badge". Previous answer is below (from the PPoPP 2016 organizers), but falls off the right side of the page in the new format.

```
\usepackage[firstpage]{draftwatermark}
\SetWatermarkText{\hspace*{8in}\raisebox{6.5in}{\includegraphics{img/ae-logo.pdf}}}
\SetWatermarkAngle{0}
```

**Comment by borisveytsman** [comment]
No problem.

Could you give me a link to an example of an article with the artifact displayed?  What are possible sizes of the artifacts?  Where can I find some graphics files for artifacts?  

Thanks

-B

**Comment by jowens** [comment]
I think there were 11 papers at PPoPP with artifact evaluation. The logo is about an inch in diameter, so not small. [ae-logo.pdf](https://github.com/borisveytsman/acmart/files/243949/ae-logo.pdf)

Here's our paper DOI, and a local copy, as an example:
http://dx.doi.org/10.1145/2851141.2851145
http://escholarship.org/uc/item/6xz7z9k0

PPoPP TOC: http://dl.acm.org/citation.cfm?id=2851141&picked=prox&cfid=576293188&cftoken=49069218

**Comment by borisveytsman** [comment]
Thanks.  What happens if the title overlaps with the logo?  Should we ask the author to split the title into several lines using \\?

**Comment by jowens** [comment]
The current setup (sigplanconf) very clearly knows nothing about the existence of such a badge. \\ would perhaps be the only way to handle it quickly.
![main_pdf__page_1_of_12_](https://cloud.githubusercontent.com/assets/976970/14940045/a2f096d0-0f18-11e6-9590-281a8314b49b.png)

The current setup doesn't have a link, but I think a link would be sensible. For PPoPP 2016, it would be one of the following two links, I suppose:
http://conf.researchr.org/track/PPoPP-2016/Artifact+Evaluation
http://ctuning.org/ae/ppopp2016.html

**Comment by borisveytsman** [comment]
I've added interface for two badges: a left one and a right one (I hope there will be no more than two in the future.  While I am at it, I also made the title aware of badges, so it does not overlap them.

John, could you please comment on the size of the badge?

**Comment by jowens** [comment]
I'm gonna call that "splendid". I'm perfectly happy with the size, though maybe you can ask the artifact-evaluation folks. :) Below are three pics of title with badge; longer title with badge; longer title without badge.

https://www.evernote.com/l/AAGSKzlOyiNODbTMnZNQxNV3hzmomvEoqms
https://www.evernote.com/l/AAHo_YxkUJVPeZBvUaKfMgAlgERm3nPS06g
https://www.evernote.com/l/AAHiXowJH31F-pQHYzEsWLXvMQ1P1aDIfSk

**Comment by borisveytsman** [comment]
Great
