### ISSUE TITLE
error in the "abstract" environment ("acmtog" vs. "sigconf")

### ISSUE THREAD

**Issue by stephennspencer** [borisveytsman/acmart#236]
When one leaves a blank line after \begin{abstract} while using the "acmtog" template style, the first line of the abstract is indented as if it were the second paragraph of the abstract.

    \begin{abstract}

    The quick brown fox jumps over the lazy dogs.

When one leaves a blank line after \begin{abstract} while using the "sigconf" template style, the first line of the abstract is not indented. (The correct behavior.)

    \begin{abstract}
    The quick brown fox jumps over the lazy dogs.

This appears to be a bug to be fixed in (at least) the "acmtog"-specific code, if not elsewhere.

**Comment by borisveytsman** [comment]
A bug in the journal (as opposite to sig) code.  Fixed.  Thanks
