### ISSUE TITLE
Line breaks in long email addresses

### ISSUE THREAD

**Issue by matteodellamico** [borisveytsman/acmart#239]
Hi,

long email addresses can end up with pretty ugly line breaks, and solving that is pretty tricky. I ended up asking on stack exchange to solve the problem, but it would be great if there were an easier solution in the acmart class itself.

https://tex.stackexchange.com/questions/391157/acmart-ugly-email-addresses-how-to-avoid-line-breaking

Thanks!

**Comment by yforster** [comment]
Increasing the UrlBreakPenalty to 10000 worked for me as well. Incorporating this to the class seems reasonable to me, because I don't see any scenario where an email address with a line break is acceptable.
