### ISSUE TITLE
Footnotes on first-page

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#24]
A footnote on the first-page (and first-column of a two-column format) is set below the copyright text (whereas title and author notes are set above).

Possibly related to #10.

**Comment by borisveytsman** [comment]
What would be the correct order?  Body text footnotes, then title/author footnotes, then permssion/copyright block?

**Comment by MatthewFluet** [comment]
I would expect the permission/copyright block is always at the very bottom of the first page (and first-column).  I tend to think that it should be treated more as a float, than as a footnote.

I would expect footnotes to appear in order of occurrence: title notes, author notes, abstract footnotes (see #25), body text footnotes.
