### ISSUE TITLE
Add acmart and version to PDF Creator tag?

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#241]
The PDF tag Producer is set to the version of pdfTeX, e.g.,
Producer:       pdfTeX-1.40.17
and the PDF tag Creator is set to a more specific package description, e.g.,
Creator:        LaTeX with hyperref package

Proposal: Change the Creator tag to
LaTeX with hyperref package and acmart-1.47 class
or only
LaTeX with acmart-1.47

This would make it easy to identify that acmart and which acmart version was used to create a certain paper PDF.

What do you think?

**Comment by dbeyer** [comment]
Thanks.  To make it perfect: Could you please abbreviate ACM in the version text (it looks unnecessarily longish)?

**Comment by borisveytsman** [comment]
This line is used in the log, and I'd rather have it more informative...
