### ISSUE TITLE
Switch on UTF8 encoding

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#242]
Since ACMART is internationally used, by many people with accents in author names and affiliations,
it might be a good idea to switch on uft8 input encoding by default,
in order to relieve the authors from one additional config line in each of their main.tex files.
Is it possible to include the following in the acmart class file?
\RequirePackage[utf8]{inputenc}

**Comment by krono** [comment]
Or even

```LaTeX
  \RequirePackage[utf8]{inputenx}
  \input{ix-utf8enc.dfu}
```

**Comment by borisveytsman** [comment]
Adding this line will make life marginally better for the authors who use UTF-8 in input.  However, it will make life tremendously more hard for the authors who do not: for example, just adding an epigraph in Greek and using LGR.

**Comment by krono** [comment]
Isn't `LGR` a font encoding, not an input encoding?

**Comment by borisveytsman** [comment]
Yes, you are right

Ok suppose you want a Russian citation and use koi8.

**Comment by krono** [comment]
hm, is the Russian support so bad with UTF8 in LaTeX?

**Comment by borisveytsman** [comment]
Many people use koi-8 and cp1251 by tradition.

**Comment by krono** [comment]
```LaTeX
\documentclass[sigconf,russian,english]{acmart}

\RequirePackage[LGR,OT1,LY1,T2A,T1]{fontenc}
\RequirePackage[utf8]{inputenx}
\input{ix-utf8enc.dfu}
\RequirePackage{alphabeta}
\usepackage{babel}
\begin{document}

\foreignlanguage{russian}{я не знаю}
\end{document}
```

this seems to work for short parts

**Comment by krono** [comment]
Also, shouldn't we advocate to _only_ use utf-8? I persnoally think it is worthwile.

**Comment by borisveytsman** [comment]
We have thousands of authors.  I am not sure we are in a position to forcefully advocate input encodings:  do we want a long holy war among some passionate ones?  I would rather give as much freedom to authors as I can.

**Comment by krono** [comment]
That's true.
But with this reasoning, acmart also would have to consider XeTeX and LuaTeX, or even Biblatex instead of BibTeX, right?

**Comment by borisveytsman** [comment]
absolutely.  This is in my plans

**Comment by krono** [comment]
Ping me if I can help :)

**Comment by borisveytsman** [comment]
Thanks!

**Comment by zackw** [comment]
Please note that neither `inputenc` nor `inputenx` sets the space factor of Unicode close curly quotes correctly.  (`\sfcode’` is 0, but `\sfcode”` is 1000.  Both should be zero.)  Therefore, if you do take the Unicode input plunge, please also add

```
% inputenc doesn't set the space factor of Unicode close curly quote
% correctly.  (In current versions, the \sfcode of ’ is 0, but the
% \sfcode of ” is still 1000.  Both should be zero.)
\AtBeginDocument{%
  \sfcode\csname\encodingdefault\string\textquotedblright\endcsname=0%
  \sfcode\csname\encodingdefault\string\textquoteright\endcsname=0%
}
```

to an appropriate place in the class file.

**Comment by zackw** [comment]
I wrote them a note and cc:ed you.

**Comment by rionda** [comment]
Is this question still relevant since utf-8 encoding is the default in LaTeX since 2018 (see https://tug.org/TUGboat/tb39-1/tb121ltnews28.pdf) ?

**Comment by borisveytsman** [comment]
This is now obsolete due to changes in LaTeX kernel
