### ISSUE TITLE
Cannot build `sample-sigplan.pdf`

### ISSUE THREAD

**Issue by adamsmd** [borisveytsman/acmart#246]
With the latest master (c8703302e798ba070fa3e152a4868501c1da2aba), running `make clean` and then `make` on my system hangs while trying to build `sample-sigplan.pdf`.  Is this happening for anyone else?

The attached file ([sigplan-bug.tex.txt](https://github.com/borisveytsman/acmart/files/1325367/sigplan-bug.tex.txt)) is a minimal working example of the bug.  It seems to depend on exactly where pages and columns end up being broken.  Does `pdflatex sigplan-bug.tex` hang for anyone else?

**Comment by Blaisorblade** [comment]
For me (with TeXlive 2017) `sample-sigplan.pdf` works, but fails after I remove its `.aux` file.

Your sample fails as well — the hang seems to be in a loop (see `\iterate` below, though you don't always get a break there). According to the logs, this is after the output routine was invoked first.

```
Underfull \vbox (badness 10000) has occurred while \output is active [1.1{/usr/
local/texlive/2017/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]^C
! Interruption.
\iterate ...kip@b \ht \flushend@@varbox@a \setbox
                                                  \flushend@@varbox@a \vbox ...
l.147 \end{document}
```

Have you tried bisecting the issue with `git bisect` to find the commit introducing it? Removing auxiliary files might help.

**Comment by borisveytsman** [comment]
Looks like the problem is in the `flushend` package.  

I'm afraid I must delete it: too dangerous :(
