### ISSUE TITLE
Footnotes in abstract

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#25]
Footnotes in abstract do not receive a footnote mark, neither at the reference point in the abstract nor in the footnote text.

Related to #24, since the abstract almost certainly falls on first-page.

**Comment by borisveytsman** [comment]
Suppose we rearrange the footnotes.  Where do abstract footnotes belong:  with the text footnotes of with the author/title notes?

**Comment by MatthewFluet** [comment]
I would expect footnotes to appear in order of occurrence: title notes, author notes, abstract footnotes, body text footnotes.
