### ISSUE TITLE
The font of your paper should be corrected.   With the new template, Linux Biolinum should be used as sans serif font for the title, for headers,..

### ISSUE THREAD

**Issue by ligianistor** [borisveytsman/acmart#250]
I am having the following problem:
The font of your paper should be corrected.
  With the new template, Linux Biolinum should be used as sans serif font for the title, for headers,
  for headings, and for captions of figures and tables.
  Linux Libertine should be used as serif font for all other content.
  Some packages change the font of the template. Please see the help page that is linked on the instructions page for hints.
I attached the log.
[main.log](https://github.com/borisveytsman/acmart/files/1347477/main.log)

**Comment by krono** [comment]
It seems you use Ubuntu Xenial, so make sure you have `texlive-fonts-extra` installed, or better, `texlive-full`.

**Comment by ligianistor** [comment]
Thanks. I installed texlive-fonts-extra and the fonts that I needed were
installed.

**Comment by krono** [comment]
Ok, then please close the issue
