### ISSUE TITLE
named option to \definecolor needs prologue

### ISSUE THREAD

**Issue by eg9** [borisveytsman/acmart#257]
Consider the minimal example

    \documentclass{article}
    \usepackage{xcolor}

    \definecolor[named]{ACMRed}{cmyk}{0,0.90,0.86,0}

    \begin{document}

    \textcolor{ACMRed}{XYZ}

    \end{document}

If compiled with `latex+dvips+ps2pdf` it will throw an error in the last phase.

The problem is solved by adding the `prologue` option to `xcolor`:

    \usepackage[prologue]{xcolor}

that does nothing when `pdflatex` or other engines are used, but is decisive for `dvips`. See section 2.5.1 in the manual of `xcolor`.

The `acmart` class is affected, because it defines colors with the `named` option, but fails to load the `prologue` option, so documents cannot be compiled with `latex+dvips+ps2pdf`.

Reference: https://tex.stackexchange.com/questions/396350/

**Comment by borisveytsman** [comment]
Thanks
