### ISSUE TITLE
Undefined control sequence \ClassInfo

### ISSUE THREAD

**Issue by gaya-** [borisveytsman/acmart#258]
Hi,

I'm trying to compile the sample-manuscript.tex using the following command:

```
pdflatex sample-manuscript.tex
```

on an Ubuntu 16.04 with the most up-to-date version of TexLive (This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)) and I'm getting the error that's in the title. Am I using a way too old version of TexLive?

**Comment by borisveytsman** [comment]
TL2015 is indeed 2 years old, but `\ClassInfo` is a rather old macro, and should not be a problem.  Can you post the log?

**Comment by gaya-** [comment]
@borisveytsman Thanks for your reply. I looked at the log and found out that the xkeyval was causing a problem. Then I checked its version and it turned out it was very old. After updating xkeyval the error disappeared. Sorry, I should've looked at the log before opening the issue. Thanks.
