### ISSUE TITLE
phdthesis title emphasize causes overfull hbox

### ISSUE THREAD

**Issue by W4RH4WK** [borisveytsman/acmart#259]
Inside `ACM-Reference-Format.bst` inside the `phdthesis` function following comment can be found: *NB: ACM style requires emphasized thesis title*.

I recently encountered a problem where no line breaks are inserted into the title causing an overfull hbox. Removing the `emphasize` property results in the wanted (but probably not ACM comform) typesetting.

The relevant bibliography entry:
```
@phdthesis{jordan2014insieme,
  title={Insieme: A compiler infrastructure for parallel programs},
  author={Jordan, Herbert},
  year={2014},
  school={University of Innsbruck}
}
```

Screenshot with emphasize (current default):
![screenshot_2017-11-07_17-07-42](https://user-images.githubusercontent.com/328798/32503743-4b9bc7fc-c3de-11e7-9aad-9a8f2257bd3b.png)

Screenshot without emphasize (test configuration):
![screenshot_2017-11-07_17-08-16](https://user-images.githubusercontent.com/328798/32503766-5ceffd8e-c3de-11e7-8eae-f55e6b76d222.png)

**Comment by borisveytsman** [comment]
Somewhere you redefined `\emph`:  instead of italics it produces underlines, which makes line breaking more difficult.

Please do not do this:  underlining is considered a very bad idea in fine typography.

**Comment by W4RH4WK** [comment]
Thank you for your reply. I originally thought this style was dictated by the template. Turns out I was completely wrong. The LaTeX file I received contained `\usepackage{ulem}` (used because of the strike-out feature). Adding `[normalem]` fixed the probleme.
