### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by mjchen611** [borisveytsman/acmart#260]
Hi,
Sorry to brother you.
I have some questions about the template of technical papers.
I use the template https://www.siggraph.org//learn/instructions-authors          -- "acmtog"
And I add
\documentclass[acmtog,anonymous,timestamp,review]{acmart} 
to the latex file. (follow the instruction in submission page)
But in the PDF file,  it will also show 
1) ACM Reference Format in the first page;
2) Copyright in the left column bottom of the first page;
2) Volume , Month, Year... in the footer;
Are these questions caused by the wrong template I used?
Or these questions can be ignored in the submission version?

And can you send me an correst template of technical papers and a correct exampled of submission pdf file?

Thank you so much.
Best Regards.

**Comment by borisveytsman** [comment]
I think his is what TOG expects to be there

**Comment by mjchen611** [comment]
Thank you so much for you reply.

I want to submit a paper to siggraph conf, is it ok to use this template?
the reference link is ：
https://s2018.siggraph.org/conference/conference-overview/technical-papers/technical-papers-submissions/  -- SUBMISSION REQUIREMENTS
https://www.siggraph.org//learn/instructions-authors

I'm not sure this template ("acmtog") is right one, can you give me some instructions/advices?

Thank you so much.
Best Regards.

**Comment by borisveytsman** [comment]
Siggraph uses `sigconf` format rather than `acmtog`.  `acmtog` is used by TOG journal.

**Comment by mjchen611** [comment]
Thank you for your reply.
I saw technical papers would be published as a special issue of ACM Transactions on Graphics.
And SUBMISSION REQUIREMENTS:
add
\documentclass[# acmtog,anonymous,timestamp,review]{acmart}
So I confused.

Thank you so much.
Best Regards.

**Comment by borisveytsman** [comment]
No need to be confused!

*Normally* SIGGRAPH use `sigconf`.  However, since your conference publishes its proceedings as a special issue of TOG, you should use `acmtog`.  This is really the question of how the papers are published.

**Comment by mjchen611** [comment]
Thank you so much.
So I just use "acmtog".

Best Regards.

**Comment by stephennspencer** [comment]
Using the "acmtog" template style is correct if you are submitting a Technical Paper to the SIGGRAPH 2018 conference. 

Best,
Stephen

**Comment by mjchen611** [comment]
Thank you for your reply.

Ok.

Thank you so much.
Best wishes.

Mingjia.

2017-12-13 13:57 GMT+08:00 stephennspencer <notifications@github.com>:

**Comment by mjchen611** [comment]
Thank you for your reply.

Ok.

Thank you so much.
Best wishes.
Mingjia.
