### ISSUE TITLE
Option to sort multiple citations in same bracket with chronological order

### ISSUE THREAD

**Issue by cqd123123** [borisveytsman/acmart#264]
Hi, 

It seems when I have multiple citations under the same bracket, they will be sorted alphabetically by default. Would it be possible to sort them in chronological order instead ?

For example, in latex \cite{aa, bb, cc} currently would be compiled as [aa et al. 2017; bb et al. 2016; cc et al. 2015]. But it would be better if there is an option to sort them chronologically as [cc et al. 2015; bb et al. 2016; aa et al. 2017].

Thanks

**Comment by alecjacobson** [comment]
I second this request.

**Comment by borisveytsman** [comment]
The sorting is done by `natbib`.  By default `natbib` sorts in the same order as the list of references is sorted.  

The command `\setcitestyle{nosort}` switches sorting off, so you can manually put the citation in the order you want

I will update the docs to reflect this.
