### ISSUE TITLE
\label only works after \caption in algorithm2e environment

### ISSUE THREAD

**Issue by alexandersvozil** [borisveytsman/acmart#265]
As the title says, acmart does only accept the algorithm2e labels if they are put after the \caption.
I do not know if this is a feature or a bug. But I am writing this so others can find this.

**Comment by krono** [comment]
This is a general recommendation regardless of `algorithm2e` and `acmart`. It's best to always put the `\label` after the `\caption`

**Comment by borisveytsman** [comment]
This is the expected and documented behavior:  `\caption` increases the counter, uses by `\label` (it has `\refstepcounter` inside)
