### ISSUE TITLE
Long author list overlaps with conference info on page top

### ISSUE THREAD

**Issue by s-tikhomirov** [borisveytsman/acmart#268]
In my paper, the list of authors is too long and overlaps with the conference information on the top of the page. Is there a workaround?

Related: #73 (same problem, but with a long title; solved with the short title argument to `\title`).

**Comment by MatthewFluet** [comment]
Use
```
\renewcommand{\shortauthors}{A.~Longname et al.}
```
*after* `\maketitle`.

**Comment by s-tikhomirov** [comment]
Thank you!
