### ISSUE TITLE
Cannot run the files inside the folder.

### ISSUE THREAD

**Issue by zakirbd** [borisveytsman/acmart#269]
I downloaded LaTeX (Version 1.49) and tried to run files such as sample-acmlarge.tex, sample-acmsmall.tex, sample-manuscript.tex in my machine but every time I am getting an error as follows:

! LaTeX Error: \thechapter undefined.

See the LaTeX manual or LaTeX Companion for explanation.

Type  H <return>  for immediate help.

 ...                                              

                                                  

l.171 \renewcommand{\thechapter}

                                {\Roman{chapter}}

? 

I will be grateful to you, please help me in this issue.

Md. Zakir Hossain
PhD Research Student
School of Engineering and Information Technology
Murdoch University, Australia.

**Comment by borisveytsman** [comment]
Could  you add as the first line of sample TeX file the command

`\listfiles`

and rerun?
