### ISSUE TITLE
[XeLaTeX] Using polyglossia changes the used font

### ISSUE THREAD

**Issue by ebousse** [borisveytsman/acmart#271]
When compiling with XeLaTex, the correct acmart font is used :
![capture d ecran de 2018-02-21 14-40-15](https://user-images.githubusercontent.com/5868014/36482986-2c718ce2-1715-11e8-88e2-3cf488d99270.png)

But if I add `\usepackage{polyglossia}` to the preamble then it falls back on the default latex font :
![capture d ecran de 2018-02-21 14-39-55](https://user-images.githubusercontent.com/5868014/36482988-2ea8f91e-1715-11e8-96d1-c0f2b22d1f64.png)

Maybe it is related ti these two warnings, that I only encounter when compiling with `polyglossia`:
```
LaTeX Font Warning: Font shape `OT1/cmr/m/n' in size <12.5> not available
(Font)              size <12> substituted on input line 170.


LaTeX Font Warning: Font shape `OT1/cmr/m/n' in size <5.5> not available
(Font)              size <5> substituted on input line 170.
```

**Comment by nomeata** [comment]
Does this help? https://github.com/borisveytsman/acmart/issues/177#issuecomment-372777632

**Comment by nomeata** [comment]
Thanks! lualatex (which I am actually using) should probably get the same treatment.
