### ISSUE TITLE
Provide a reference Docker environment to demonstrate the examples are runnable

### ISSUE THREAD

**Issue by 1605200517** [borisveytsman/acmart#272]
For example, if I try to compile these ACM examples with the MikText Docker distro, there are some bugs regarding bibliography (biber, natbib,...) so still some debugging is required.
It would be great to be able to demonstrate an OOB reference environment with a working ACM template.

Ideally, this can be also coupled with [TravisCI](https://github.com/marketplace/travis-ci) as used by many GitHub projects.

**Comment by krono** [comment]
What about OverLeaf? They got quite a bunch of `acmart`-based templates: [https://www.overleaf.com/latex/templates?addsearch=acm]

**Comment by 1605200517** [comment]
@krono 
maybe I can't get your point but
1) I started there with https://www.overleaf.com/latex/templates/acm-conference-proceedings-new-master-template/pnrfvrrdbfwt#.WpFhw5-E68U getting those errors
2) I thought it is be based on this GitHub anyway
3) this issue is about coupling this repo with a Docker environment so that you could say in just one line

`docker run -ti -v miktex:/miktex/.miktex  -v `pwd`:/miktex/work miktex/miktex pdflatex sample-sigconf.tex`

and voila there's your paper PDF.

**Comment by krono** [comment]
{ Sidenote: what are “those errors” }

The typical TeX workflow for packages is through [CTAN](http://ctan.org), where TeX packages are hosted. As far as I know,  (a) both TeXLive and MiKTeX  get 98% of their packages there, (b) the “deployment files” of this package are hosted there (the `.cls` and the example files), and (c) I _think_ it is mostly tested on TeXLive.

For your 2. please note that you have to deal with the `.dtx` first before being able to use the `.cls` etc.

So, the OOB Reference Environment would be a TeXLive full installation (but this is subject to @borisveytsman's say, clearly).

Personally, I'd say Dockerizing a LaTeX class is mere overkill.

**Comment by 1605200517** [comment]
UPD thanks for the advice with TexLive, I tried now also one such environment,

docker run --rm --volume $PWD:/workdir --workdir /workdir makisyu/texlive-2017 platex sample-sigconf.tex 

with the following output:

Package natbib Warning: Citation `Amsthm15' on page 3 undefined on input line 2
    95.


See also
https://tex.stackexchange.com/questions/417007/working-combination-of-a-reference-system-environment-and-an-example-document-fo

**Comment by krono** [comment]
It is not possible to obtain a complete pdf with just one single run of `pdflatex`.

The warning you get is because `bibtex` has not been run yet. There's nothing wrong with that.

Once you have a bibliography, the typical sequence is

 * `pdflatex sample-sigconf`
 * `bibtex  sample-sigconf`
 * `pdflatex sample-sigconf`
 * `pdflatex sample-sigconf`

and there is not too much you can do about (well, except `latexmk` or similar).

**Comment by 1605200517** [comment]
it works! thank you.
https://github.com/1605200517/tex-mwe-citing/blob/master/texlive-acm/compile-in-docker.sh
