### ISSUE TITLE
acm mm 2018 regular paper template

### ISSUE THREAD

**Issue by gjyin91** [borisveytsman/acmart#274]
As for template of acm mm regular paper submission,  can anybody give a example of the settings of sample-sigconf-authordraft.tex  like these as followings ?  

\acmDOI{10.475/123_4}

% ISBN
\acmISBN{123-4567-24-567/08/06}

%Conference
\acmConference[WOODSTOCK'97]{ACM Woodstock conference}{July 1997}{El
  Paso, Texas USA}
\acmYear{1997}
\copyrightyear{2016}

\acmPrice{15.00}

**Comment by dongzhuoyao** [comment]
what's the difference between sample-sigconf-authordraft.tex and sample-sigconf.tex  ?

**Comment by stephennspencer** [comment]
Those parameters are sufficient for initial submission. 

If your work is accepted for presentation at the conference, you will complete an ACM Rights Form and receive the commands with conference-specific values - the real article DOI, the real name of the conference, and so on.

Best,
Stephen

**Comment by b-liu14** [comment]
How about the **CCSXML**? What should I do? Delete it?

Sorry about this simple question.

**Comment by gjyin91** [comment]
Is it right to use sample-sigconf-authordraft.tex  when  double-blind submission for review while sample-sigconf.tex for camera-ready version？

**Comment by dongzhuoyao** [comment]
same doubt with @gjyin91

**Comment by stephennspencer** [comment]
I think that "authordraft" is just that; an AUTHOR version, and not really suitable for submission. The only substantive difference between "sample-sigconf.tex" and "sample-sigconf-authordraft.tex" is that the latter has "authordraft" as a parameter to the \documentclass command.

I work with authors submitting works to SIGGRAPH-sponsored events, and direct them to use the "sigconf" template style, and add several keywords to their \documentclass command for anonymization when submitting works for review:

     \documentclass[anonymous, timestamp, review,sigconf]{acmart}

The CCS and keyword elements are required by ACM, and your review version should have them, if only to give a more realistic idea of the length of your work.

All that being said, there is probably someone associated with the ACMMM conference that should be answering these questions - e-mail to "MM18-PC@sigmm.org" goes to the event's Technical Program Chairs.

Best,
Stephen

**Comment by borisveytsman** [comment]
I think I can close this issue
