### ISSUE TITLE
Letter suffix (e.g. 2015a) is displayed in year field of reference

### ISSUE THREAD

**Issue by ari-blenkhorn** [borisveytsman/acmart#275]
Noticed in PDF version of this paper: https://dl.acm.org/citation.cfm?id=3130882

Within the main text, these show up appropriately as [2015a] and [2015b], but in the full reference list they should state just the year, without the added letters.

C. Jiang, C. Schroeder, A. Selle, J. Teran, and A. Stomakhin. **2015a**. The Affine Particle-
In-Cell Method. ACM Trans. Graph. 34, 4 (2015), 51:1–51:10.
Min Jiang, Richard Southern, and Jian J. Zhang. **2015b**. A Particle-based Dissolution
Model using Chemical Collision Energy. Proceedings of the 10th International Conference
on Computer Graphics Theory and Applications (2015), 285–293.

**Comment by borisveytsman** [comment]
I would disagree.  If we do not show letter suffixes in the list of references, how does the reader know which text citation corresponds to which item in the list?  Adding letters to the year in the list is quite customary for this pupose.
