### ISSUE TITLE
DOI Issue

### ISSUE THREAD

**Issue by bargteil** [borisveytsman/acmart#278]
I get a warning 
Warning--unrecognized DOI value [0.1145/2451236.2451243]

using the bibtex entry from the digital library:
@article{Jones:2016:EPD:2897824.2925979,
author = {Jones, Ben and Thuerey, Nils and Shinar, Tamar and Bargteil, Adam W.},
title = {Example-based Plastic Deformation of Rigid Bodies},
journal = {ACM Trans. Graph.},
issue_date = {July 2016},
volume = {35},
number = {4},
month = jul,
year = {2016},
issn = {0730-0301},
pages = {34:1--34:11},
articleno = {34},
numpages = {11},
url = {http://doi.acm.org/10.1145/2897824.2925979},
doi = {10.1145/2897824.2925979},
acmid = {2925979},
publisher = {ACM},
address = {New York, NY, USA},
keywords = {deformation, example-based simulation, local blending, plasticity, rigid body simulation, skinning},
}

**Comment by borisveytsman** [comment]
I cannot reproduce the warning.  Is it possible that you have the line
```
doi = {0.1145/2451236.2451243},
```

**Comment by bargteil** [comment]
I do not have that line.  I’ve attached the full bib and tex files.

**Comment by borisveytsman** [comment]
I cannot reproduce your problem with your files :(

**Comment by borisveytsman** [comment]
Font adjustment requires a lot of experience.  I did some work here, but you might want to contact Michael Sharpe, who is one of the leading experts here
