### ISSUE TITLE
option to hide all ACM-specific information?

### ISSUE THREAD

**Issue by cyrus-** [borisveytsman/acmart#280]
I'd like to post a version of a submitted paper to arxiv, ideally with the same formatting as acmart but without any ACM/publication-specific information (namely, the copyright info + the "Proceedings of the ACM..." in the footer, etc.).

Is there an easy way to do this?

I'm currently using the sigplan single column format, if that matters.

**Comment by borisveytsman** [comment]
I guess the recent commit by @gasche closes this
