### ISSUE TITLE
References order not correct for, e.g., Dutch names with tussenvoegsel

### ISSUE THREAD

**Issue by rionda** [borisveytsman/acmart#281]
The bibliography is not always sorted correctly: when the first author of a publication has a Dutch name containing a [tussenvoegsel](https://en.wikipedia.org/wiki/Tussenvoegsel) (e.g., "van Leeuwen), this word is taken into consideration when sorting the references, but it should not (as per the wikipedia page, and one reviewer that commented on this issue when reviewing a paper of mine). 

I haven't checked, but the same issue may arise for the German "von", which should also not be considered when sorting (see https://en.wikipedia.org/wiki/Von).

Minimal example:

`minimal.tex`:

```latex
\documentclass[sigconf]{acmart}
\begin{document}
\title{Minimal}
\author{X Y}
\maketitle
\cite{RiondatoU14,VanLeeuwenU16}
\bibliographystyle{ACM-Reference-Format}
\bibliography{minimal}
\end{document}
```

`minimal.bib`:

```bibtex
@inproceedings{VanLeeuwenU16,
	Author = {van Leeuwen, Matthijs and Ukkonen, Antti},
	Booktitle = {Proceedings of Discovery Science},
	Series = {DS '16},
	Title = {Expect the Unexpected -- On the Significance of Subgroups},
	Year = {2016}}

@article{RiondatoU14,
	Author = {Riondato, Matteo and Upfal, Eli},
	Journal = {ACM Trans. Knowl. Disc. from Data},
	Number = {4},
	Pages = {20},
	Title = {Efficient Discovery of Association Rules and Frequent Itemsets through Sampling with Tight Performance Guarantees},
	Volume = {8},
	Year = {2014}}
```

The resulting PDF has the "RiondatoU14" reference listed before the "VanLeeuwenU16", but the order should be the opposite (because "Leeuwen" < "Riondato").

**Comment by borisveytsman** [comment]
There are two ways to order `van Leeuwen`:  under `V` or under `L`.  Traditionally ACM uses the first one.  The relevant function in the `bst` file is `format.lab.names`, and it now uses the format `{vv}~{ll}`, i.e. Mathijs van Leeuwen is sorted as `van leeuwen`.

**Comment by krono** [comment]
Sidenote: This practice differs between Dutch (Netherlands) and Flemish (Belgium) [wikipedia](https://en.wikipedia.org/wiki/Dutch_name#Surnames):

> In name directories in the Netherlands, the **prefixes are always ignored for sorting** (e.g., Van Rijn is ordered under 'R', but written in full. So a listing would be Raamdonck, Van Rijn, Rutgers and not Vaandrig, Van Rijn, Vondel). A Dutch surname may often contain an article and/or a preposition, preceding the noun. Sometimes these have been merged with the name. Many Dutch surnames originated from different personal qualities, geographical locations, and occupations. However, Dutch names in English directories (e.g., reference lists of scientific papers) may be ordered on the full name including all prefixes (Van Rijn would be ordered under 'V'), partly because many Dutch emigrant families to English-speaking countries have had their prefixes capitalized for them, whether they liked it or not, like Martin Van Buren or Steve Van Dyck, and normal practise in English is to order on the first capitalized element.

> In Belgium, all **prefixes are always included for sorting**.

Other references (especially answer two):
 - https://academia.stackexchange.com/questions/8870/how-should-van-names-be-ordered-in-a-bibliography

**Comment by borisveytsman** [comment]
@rionda .  

1.  Looks like your reviewer was wrong since Dutch authors with 'van' must be sorted under V, unlike Belgian ones.

2.  Anyway I've added the documentation and the instructions how to override this design choice (Patashnik's `\noopsort` trick)
