### ISSUE TITLE
acmart breaks with tipa package

### ISSUE THREAD

**Issue by gattilorenz** [borisveytsman/acmart#283]
importing the tipa package (used for writing the International Phonetic Alphabet) breaks acmart, since acmart uses the libertine font.

I patched the template manually ( following the guide at https://tex.stackexchange.com/questions/377235/sffamily-mdseries-undefined-control-sequence ) but you might want to fix it for everybody

**Comment by borisveytsman** [comment]
I cannot reproduce your problem.  Here is my file:

```
\documentclass[sigconf]{acmart}
\usepackage{tipa}

\begin{document}

\textipa{f@"nEtIks} \ipaclap{\textipa{b}}{\textipa{/}}

\end{document}
```

This compiles to:
[tmp.pdf](https://github.com/borisveytsman/acmart/files/2043170/tmp.pdf)
