### ISSUE TITLE
Permission block on second page takes up two columns

### ISSUE THREAD

**Issue by sandeep-ps** [borisveytsman/acmart#286]
Permission block on the second page seems to be using up both columns but overlaps with text on the second column. This is happening when there are many authors in a paper and only title and authors list can be typeset on the first page.

**Comment by borisveytsman** [comment]
Could you provide an example?

**Comment by sandeep-ps** [comment]
Sure. Please see below. This is on second page. 
![image](https://user-images.githubusercontent.com/4306604/40633972-5b9771fa-62b8-11e8-85a0-a1d8ca21a864.png)

**Comment by borisveytsman** [comment]
Could you post (or e-mail me) the text file?  It does not look like what my style should produce.

**Comment by sandeep-ps** [comment]
Sure. I have emailed you the relevant files. Thanks.

**Comment by borisveytsman** [comment]
Discussed offline
