### ISSUE TITLE
Template for Rebuttal

### ISSUE THREAD

**Issue by b-liu14** [borisveytsman/acmart#287]
Hi, I have no idea for how to make the small title and get rid of the footnote in the left bottom for rebuttal.
Can anyone help me? Thanks very much!

**Comment by borisveytsman** [comment]
Why do you need to get rid of them?

**Comment by b-liu14** [comment]
In the rebuttal period, responses must be no longer than ONE page in length and I don't think the footnote is necessary for rebuttal.

**Comment by rionda** [comment]
Are you sure the rebuttal has to be in ACM format? Seems a bit of a weird request...

**Comment by b-liu14** [comment]
Yes.
> After receiving the reviews, authors may optionally submit a rebuttal to address the reviewers' comments, which will be limited to a one-page PDF file using the "acm-sigconf template"

**Comment by borisveytsman** [comment]
Then it must include footnote since it is a part of the template

**Comment by b-liu14** [comment]
Ok, thanks!
