### ISSUE TITLE
multiline authors incorrect in "ACM Reference format" section

### ISSUE THREAD

**Issue by ozross** [borisveytsman/acmart#288]
Multiple authors with the same affiliation are given using \\ as separator, e.g. in  SIGCHI-a  style.
This will require a local redefinition (e.g.,  `\def\\{,}`  )  before  \authors  is used in  `\@mkbibcitation`
viz.
```
\def\@mkbibcitation{\bgroup
  \def\footnotemark{}%
  \par\medskip\small\noindent{\bfseries ACM Reference format:}\par\nobreak
 \def\\{,}%%%% <<<<----------    here!
  \noindent\authors. \@acmYear. \@title.
```
There already figures to be a space-character coming after the `\\`, so there doesn't need to be one within the redefined expansion. Otherwise, one could try a test like here:
   `\def\\{, \ignorespaces}`

Hope this helps.

**Comment by dbeyer** [comment]
The redefinition of `\\` in commit a498e05 seems to be not local enough: #300.
