### ISSUE TITLE
Bookmarks not working with some ACM styles

### ISSUE THREAD

**Issue by ozross** [borisveytsman/acmart#290]
This is a complicated issue due to the fact that  `nameref.sty` (called by  hyperref ) patches the  `\@sect` and  `\@ssect` macros to insert coding to generate Bookmarks. viz.
```
\let\NR@sect\@sect
\newcounter{section@level}
\def\@sect#1#2#3#4#5#6[#7]#8{%
  \setcounter{section@level}{#2}%
  \NR@gettitle{#7}%
  \NR@sect{#1}{#2}{#3}{#4}{#5}{#6}[{#7}]{\Sectionformat{#8}{#2}}%
}
\let\NR@ssect\@ssect
\def\@ssect#1#2#3#4#5{%
  \NR@gettitle{#5}%
  \NR@ssect{#1}{#2}{#3}{#4}{\Sectionformat{#5}{#1}}%
}
```
The command `\Sectionformat` is provided as a place to hook-in styling commands or other macros, when actually setting the section title, which `balanced-text` is held in parameter `#8` (or `#5` for `\@ssect`).
Styling commands are passed via `#6` (or `#4` for `\@ssect`), but must be applied to `{#8}` (or `#5` for `\@ssect`). To allow this to happen smoothly — consider a requirement to use `\MakeUppercase`, as in `\@secfont` with  `sigchia` style — we need an indirect mechanism that can be easily overridden when appropriate. 
In particular, where `acmart.cls` currently has macro re-definitions like:
```
\renewcommand\section{\@startsection{section}{1}{\z@}%
  {-.75\baselineskip \@plus -2\p@ \@minus -.2\p@}%
  {.25\baselineskip}%
  {\@secfont}}
```
alter these (5 instances currently) to become
```
\renewcommand\section{\@startsection{section}{1}{\z@}%
  {-.75\baselineskip \@plus -2\p@ \@minus -.2\p@}%
  {.25\baselineskip}%
  {\ACM@NRadjust\@secfont}}
```
and
```
\renewcommand\paragraph{\@startsection{paragraph}{4}{\parindent}%
  {-.5\baselineskip \@plus -2\p@ \@minus -.2\p@}%
  {-3.5\p@}%
  {\ACM@NRadjust{\@parfont\@adddotafter}}}
```
Then we need macro definitions as follows:
```
\def\ACM@NRadjust#1{%
 \begingroup
  \expandafter\ifx\csname Sectionformat\endcsname\relax
  % do nothing when  \Sectionformat  is unknown
   \def\next{\endgroup #1}%
 \else
  \def\next{\endgroup
   \let\realSectionformat\Sectionformat
   \def\ACM@sect@format@{#1}%
   \let\Sectionformat\ACM@NR@adjustedSectionformat
 %%  next lines added 2018-06-17 to ensure section number is styled
   \let\real@adddotafter\@adddotafter
   \let\@adddotafter\ACM@adddotafter
   #1{}% imposes the styles, but nullifies  \MakeUppercase 
   \let\@adddotafter\real@adddotafter
  }%
 \fi \next
}
\def\ACM@NR@adjustedSectionformat#1#2{%
 \realSectionformat{\ACM@sect@format{#1}}{#2}%
 \let\Sectionformat\realSectionformat}
\DeclareRobustCommand{\ACM@sect@format}{\ACM@sect@format@}
\def\ACM@sect@format@null#1{#1}
\let\ACM@sect@format@\ACM@sect@format@null
\AtBeginDocument{%
 \expandafter\ifx\csname LTX@adddotafter\endcsname\relax
  \let\LTX@adddotafter\@adddotafter
 \fi
}
\def\ACM@adddotafter#1{\ifx\relax#1\relax\else\LTX@adddotafter{#1}\fi}
```
Here's a description of what all this does.

Initially `\ACM@sect@format@` just passes through its `#1` argument unchanged.
When a sectioning macro such as `\section` occurs, the `\ACM@NRadjust` redefines `\ACM@sect@format@` to expand into the styling commands; e.g., `\@secfont`.
Then `\Sectionformat` is temporarily redefined to produce  `\realSectionformat{\ACM@sect@format{#1}}{#2}`, which ultimately becomes `\Sectionformat{\@secfont{#1}}{#2}`.
This is done to allow `\Sectionformat` to be variable, as may be needed in particular circumstances. Its current expansion is saved as `\realSectionformat` which is used with the modified 1st argument, then `\Sectionformat` is reverted to its former expansion.

To style the section-number, the line  `#1{}` is used at the end of `\ACM@NRadjust`. This imposes style-changing commands for fonts and sizes, but any `\MakeUppercase` acts on just the `{}`. It's a bit hacky, by essentially assuming that only numbers occur here, not letters to be case-changed. (This should be acceptable in a class-file, as it ought to be possible to change the case elsewhere, if that was ever desired.) Also, it can result in `\@adddotafter` being called too soon, so a slight adjustment is made, via `\ACM@adddotafter`, which now tests whether its argument is empty. But the coding has to allow for other packages to have also patched `\@adddotafter`.

The styling commands come indirectly through the robust `\ACM@sect@format` which expands into `\ACM@sect@format@`, hence into `\@secfont` to allow styling to be applied to the section title as `{#1}`. The braces here allow something like `\MakeUppercase` to act only on the title text.
The indirection via `\ACM@sect@format` is to allow this behavior to be changed or extended; e.g., by macros that may just want to get at the `#1` text without any styling. This is particularly important for Tagged PDF, where tagging of the textual content is needed. For example `\let\ACM@sect@format\ACM@sect@format@null` causes the styling to be bypassed.

Such a patch has been tested with a couple of ACM format styles (incl. `sigchia`). It captures all the functionality required to get everything working properly for bookmarks and other macros that need to use the text of a section-title. Furthermore, if this coding is tested without the `nameref.sty` package having been loaded, then `\Sectionformat` figures to be unknown, and `\ACM@NRadjust` simply returns its argument, without any bracing.

Cheers,
 
     Ross

**Comment by ozross** [comment]
I've just discovered this isn't quite enough with numbered sections.
Styling isn't applied to the section-number itself. 
I'm having a good look at this, to determine what is needed to get this happening properly.

**Comment by borisveytsman** [comment]
Ross, please test
