### ISSUE TITLE
Unwanted comma appears in ACM Reference Format as part of title

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#300]
Commit a498e05 breaks the ACM Reference Format

To reproduce the issue, please compile the following paper with and without the commit:

```
\documentclass[sigconf]{acmart}
\begin{document}

\title{First Line of Title\\
Second Line of Title}

\maketitle
\end{document}
```

**Comment by borisveytsman** [comment]
Are you sure comma here is unwanted?

**Comment by dbeyer** [comment]
Absolutely.
A line break in the title is purely layout and has no bibliographic meaning.
Therefore, it should not be represented in the citation in any way (not as line break, not as comma).

**Comment by borisveytsman** [comment]
Does the new commit look better?

**Comment by dbeyer** [comment]
Much better!  Thanks a lot!
