### ISSUE TITLE
Double-column and amsmath

### ISSUE THREAD

**Issue by zilinc** [borisveytsman/acmart#302]
While using the double-column formats, if I put the `gather` or `align` environment from the `amsmath` package inside a `figure*`, which is meant to span over two columns, it will horizontally align equations to the center of a column instead of to the whole page. E.g.
```
\begin{figure*}
\begin{gather*}
a = b
\end{gather*}
\end{figure*}
```
It kind of looks like:
```
text text text text             text text text text
text text text text             text text text text
text text text text             text text text text
+--------------------------------------------------+
|       a = b                                      |
+--------------------------------------------------+
              Fig. Mis-aligned equations

text text text text             text text text text
text text text text             text text text text
text text text text             text text text text
```
Is there a way to align the equations to the center of the page? Thanks.

**Comment by borisveytsman** [comment]
I am not sure whether it is good idea to put equations into floats, and if yes, whether equations must be centered there.  But anyway, equations in `amsmath`, which `acmart` inherits from, a centered with respect to `\columnwidth`.  A local change inside the figure makes equations centered:

`\begin{figure*}
  \centering
  \columnwidth=\linewidth
  \[
    a=b
  \]
  \caption{tmp}
\end{figure*}`

**Comment by zilinc** [comment]
Many thanks for the answer.
