### ISSUE TITLE
Citing products or datasets

### ISSUE THREAD

**Issue by domoritz** [borisveytsman/acmart#310]
#142 talks about how to cite a website but how do I cite a product or dataset, which is available at a website?

```bib
@misc{bts,
    author={Bureau of Transportation Statistics},
    title={On-Time Performance},
    howpublished={\url{https://www.transtats.bts.gov/DL_SelectFields.asp?DB_Short_Name=On-Time&Table_ID=236}},
    note = {Accessed: 2018-09-12}
}
```

Is `misc` the right class? In this case there is no obvious date so I get `n.d.` twice. Is this expected behavior? 

<img width="462" alt="screen shot 2018-09-12 at 14 13 48" src="https://user-images.githubusercontent.com/589034/45453598-1cd6f800-b696-11e8-8b8a-d6f359f94602.png">

**Comment by borisveytsman** [comment]
In this case I'd use `online`, but internally `online` is mapped into `misc` anyway.

Yes, `n.d.` (no date) is the expected behavior
