### ISSUE TITLE
Different font size in figure vs table captions

### ISSUE THREAD

**Issue by luileito** [borisveytsman/acmart#312]
The font size is slightly larger in table captions (concretely 12.5% larger). Is this on purpose? I was expecting them to be the same size.
![fontsizes](https://user-images.githubusercontent.com/1146339/45751612-2c64bc80-bc13-11e8-9069-b534735dae95.png)

**Comment by borisveytsman** [comment]
I think this was a requirement for sigchi.

**Comment by borisveytsman** [comment]
Yup.  @craig-rodkin, can you please check?

**Comment by borisveytsman** [comment]
btw, figure captions are under the figures, table captions are above the tables, so different formatting may be justified

**Comment by Craig-Rodkin** [comment]
The captions are in the correct positions. I will ask for clarity on the point size. thanks
