### ISSUE TITLE
subfiles don't compile when longer than 2 pages?

### ISSUE THREAD

**Issue by alialkhatib** [borisveytsman/acmart#314]
This might be related to #308, but it manifests differently. When I try to compile a subfile that'll be longer than 2 pages in total, it fails with the following error:

```
<path to file: line number>: Undefined control sequence. [\end{document}]
```

For the moment I'm just adding `%!TEX root = ./main.tex` to the top of the document so it compiles the main document instead of trying to compile the subfile, but that negates some of the benefit of subfiles (faster compilation, makes it easier to review just that one section, etc...).

I'm racing a little for a deadline so I might not be able to get _right_ back to any followup comments, but I'll try to return in a few days if I can help.

**Comment by borisveytsman** [comment]
I am afraid there is something wrong with your setup.  Subfiles + acmart work for me

**Comment by alialkhatib** [comment]
As with #308 I'll take a look and see if anyone else can replicate what I'm seeing to try and narrow down source for >2pg documents not compiling. Thanks for the followup in both cases!
