### ISSUE TITLE
Red color of cross-references detracts reader attention from contents

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#316]
Dear Boris,

Could you please change the default color of the cross references (figures etc.)
from light red to something darker, as nicely done for literature references and links?

I know many other authors that hate this coloring, because it really draws the attention
of readers to a detail that should not be highlighted that much.

Best,
Dirk

**Comment by brunyuriy** [comment]
I agree!  The red color is very distracting and it reduces the readability of the paper.  Frankly, I think this should just be plain black.  I see no reason to highlight figure and table numbers.  

Thank you!
Yuriy

**Comment by borisveytsman** [comment]
Here is the situation:  I am restricted to ACM colors, see http://identitystandards.acm.org/identitystandards.pdf.  Which color from those listed on page 18 would work better?

**Comment by brunyuriy** [comment]
Black
C0, M0, Y0, K100
R0, G0, B0

Same color as the text.  There is no reason to break up the text and draw attention to something that's less important than the text.

**Comment by dbeyer** [comment]
@brunyuriy: Style guidelines usually say that text with links (URLs) should be recognizable (holds for web pages and also for text in PDF documents), in order for the reader to quickly understand that there is something to click on.
I am not sure if this applies to crossrefs, too, but if they are set in black, then the reader would not recognize that there is something to click on. So if set in black, we can omit the refs altogether.

**Comment by dbeyer** [comment]
So I would recommend either
(a) use ACM Dark Blue or ACM Purple, or
(b) omit such intra-document linking (and print in black).

I personally almost never click on the intra-document links, but find the colored URL links quite useful.

And I agree that the current situation (red) is bad, because it wants readers' attention too much.

**Comment by brunyuriy** [comment]
I agree that URLs need to be in a blue color, but crossrefs?  I really do find it distracting.  Why does, for example, Figure 5 need to have the 5 in blue?  I still vote for black.  I'm fine with it being a link, but not an obvious one.  That way, it preserves the functionality AND improves readability.
