### ISSUE TITLE
Column baselines are not aligned

### ISSUE THREAD

**Issue by pqu** [borisveytsman/acmart#317]
The last line of each column in the two-column formats is not always flush with the page baseline and therefore can appear unbalanced. An example can be seen on page 3 of the `sample-sigchi` document (with `showframe`):

<img width="1310" src="https://user-images.githubusercontent.com/227179/46190667-6126e280-c2a9-11e8-8b8c-dc7cdc0cda24.png">

**Comment by borisveytsman** [comment]
Right now we do not do grid typesetting:  with variable length figures it is not easy...
