### ISSUE TITLE
key for misc entries

### ISSUE THREAD

**Issue by JuliaLawall** [borisveytsman/acmart#318]
Could it be possible to avoid printing the key for misc entries, and use the title in its place?  At least for web pages, there is no deterministic way to choose the key, and it is the title that is meaningful.

**Comment by borisveytsman** [comment]
Can you provide a MWE?  I am not sure when do I print the key?

**Comment by JuliaLawall** [comment]
On Sun, 14 Oct 2018, Boris Veytsman wrote:

>
> Can you provide a MWE? I am not sure when do I print the key?

mwe.tex:

\documentclass[format=acmsmall, review=false, screen=true]{acmart}
\begin{document}

\cite{Alloc}

% Bibliography
\bibliographystyle{ACM-Reference-Format}
\bibliography{mwe}


\end{document}

----------------------------

mwe.bib:

@misc{Alloc,
	key={Allocation},
	title={{Linux} kernel documentation for memory allocation},
	note={https://www.kernel.org/doc/htmldocs/kernel-api/API-kmalloc.html},
	year={2018}
}

----------------------------

The pdf is attached.

julia

**Comment by JuliaLawall** [comment]
On Sat, 20 Oct 2018, Boris Veytsman wrote:

>
> Thanks. Here is the situation:
>
>  1.
>
>     For texts without the author author={Anon.} is the preferred way to
>     create labels. This gives for your entry Anon. 2018, which is the
>     preferred form of citation.

Preferred by whom?  Our paper is using number citations, not author-date
citations.  An example is:

[41] MySQL 2018. MYSQL database. https://www.mysql.com/

What is the purpose of printing the key in this case?

julia

**Comment by borisveytsman** [comment]
I'm afraid you miss the meaning of `key` field.  `key` field is not the key to the entry:  this is what is printed in the bibliography list if authors are missing.  This is exactly what is done

**Comment by JuliaLawall** [comment]
On Sat, 20 Oct 2018, Boris Veytsman wrote:

>
> I'm afraid you miss the meaning of key field. key field is not the key to
> the entry: this is what is printed in the bibliography list if authors are
> missing. This is exactly what is done

In other styles, the key is used for sorting and is not shown.  If the key
is shown just like an author would be shown, then there doesn't seem to be
a point to have a separate tag.  People could just put the information in
the author field.

The bibtex documentation says:

key field

Used for alphabetizing and creating a label when the "author" and "editor"
fields are missing. This field should not be confused with the citation
key that appears in the \cite command and at the beginning of the entry.

Format:

     KEY = field_text

It doesn't say that the key should be printed.

julia
