### ISSUE TITLE
Balanced last page (for 'sigconf' and 'sigplan' mode)

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#328]
ACM wants the authors to submit papers with balanced last pages,
for example, in case of the double-column formats `sigconf` and `sigplan`.

This is related to issue #222, which was closed because class `acmart` was
taking care of this, but it seems in issue #246 the `flushend` got removed.

Should `acmart` implement the balancing?
Either with or without using the other packages.
One option seems to be package `flushend`,
the other option seems to be package `balance`, where
a command `\balance` need to be inserted at the end of the document.

**Comment by yforster** [comment]
I think `acmart` should implement balancing if ACM wants authors to submit papers with balanced last pages without any doubt.

I think if `flushend` is too dangerous, `balance` is okay and the template files should be extended with a comment that the `balance` command is needed on the last page. (Also, in our use case, `balance` is producing a nicer looking last page than `flushend`.)

**Comment by borisveytsman** [comment]
Ok, let us add `balance` with the user option to switch it off

**Comment by yipliu** [comment]
Hi,

In v1.84, when I set balance=True, nothing has been changed.

**Comment by szsam** [comment]
In v1.90, last page is not balanced even if balance=true
