### ISSUE TITLE
Customizing author blocks to be single column, line by line

### ISSUE THREAD

**Issue by muclipse** [borisveytsman/acmart#329]
Hi, I'm loving the ACMart format and enjoying my writing.

One challenging point is that it is tough to customize the layout of the author blocks in top matters.

I want to place the author names in a single line on top, and their detailed affiliations below the line, each of them in a single line.

The example paper is:

![7](https://user-images.githubusercontent.com/5862566/49785680-add87080-fd64-11e8-9efa-c6c0480039bd.png)

I've read the manual, but it seems that there are no procedural ways to accomplish such a layout.

Is it seriously violating the design principle of the new ACM format?

If not, how can I manually write the author block in the top matter?

Thank you.

**Comment by borisveytsman** [comment]
I am afraid the first is true:  this would seriously violate the design of ACM papers :(
