### ISSUE TITLE
hyperref Warning: Token not allowed in a PDF string

### ISSUE THREAD

**Issue by Sckholar** [borisveytsman/acmart#332]
Using any `ccsdesc` command will produce various Hyperref warnings, presumably because LaTeX macros are stored in the PDF metadata.

MWE:
```tex
\documentclass[sigplan]{acmart}

\ccsdesc[500]{A~B}

\begin{document}
	\title{Title}
	\maketitle
\end{document}
```

produces

> Package hyperref Warning: Token not allowed in a PDF string (Unicode):
> (hyperref)                removing `\global' on input line 7.
> 
> Package hyperref Warning: Token not allowed in a PDF string (Unicode):
> (hyperref)                removing `\advance' on input line 7.
> 
> Package hyperref Warning: Token not allowed in a PDF string (Unicode):
> (hyperref)                removing `\c@@concepts' on input line 7.

**Comment by stephennspencer** [comment]
Building this sample article - 
https://www.siggraph.org/sites/default/files/sample-SIGGRAPH-techpaper-submission.zip - with v1.54 produces no warnings, and does with v1.57. In addition to the hyperref warnings, there are warnings about \vspace.

[sample-acmtog-SIGGRAPH-submission-1.54.log](https://github.com/borisveytsman/acmart/files/2776336/sample-acmtog-SIGGRAPH-submission-1.54.log)
[sample-acmtog-SIGGRAPH-submission-1.57.log](https://github.com/borisveytsman/acmart/files/2776337/sample-acmtog-SIGGRAPH-submission-1.57.log)
