### ISSUE TITLE
Moderate flexibility in `natbib` option

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#34]
As noted in #19, it is best if the selected `format` option dictates good defaults for `natbib` citation style.  However, it would be good if the numbers vs. authoryear could be made with the `natbib` class option, allowing the selected `format` to make the appropriate defaults for that style.  At the very least, SIGPLAN has supported both citation styles, but they dictate slightly different specifics in the `natbib` `\setcitestyle` invocation.

A proposal is a scaled back version of #19, whereby the `natbib` option would support four choices:
* `false` - does not load `natbib`
* `authoryear` - uses `natbib` with `\setcitestyle{authoryear}`, possibly with `format`-specific customization
* `numbers` - uses `natbib` with `\setcitestyle{numbers}`, possibly with `format`-specific customization
* `true` - behaves like `authoryear` or `numbers` as chosen by the `format`

**Comment by borisveytsman** [comment]
I added the following logic:

1.  A format can select natbib (and possibly natbib customization) 
2.  If the user explicitly sets natbib to true or false, this trumps format's selection.

A format can choose \setcitestyle{authoryear} or \setcitestyle{numbers}.  If the user chooses, however, it trumps format's choice.  I think is is more clear than setting numbers and authoyear in options.

**Comment by MatthewFluet** [comment]
The problem with this approach is that it doesn't allow a format to establish different formatting conventions for authoryear vs numbers.  In particular, for SIGPLAN/natbib/authoryear, I'd like
```
  \setcitestyle{%
    authoryear,%
    open={(},close={)},citesep={;},%
    aysep={},yysep={,},%
    notesep={, }}
```
and for SIGPLAN/natbib/numbers, I'd like
```
  \setcitestyle{%
    numbers,sort,compress%
    open={[},close={]},citesep={,},%
    notesep={, }}
```
Obviously, I'd not like to require the author to complete the entire `\setcitestyle` command, but with the current implementation, `\setcitesyle{numbers}` will simply retain the settings of the other options.

**Comment by MatthewFluet** [comment]
A second, more stylistic question with the current implementation.  Why introduce an explicit `@ACM@natbib@override` boolean and related logic instead of performing an `\ExecuteOptions{natbib=true}` for appropriate formats within the non-error branch of the `format` option definition?  I understand that that would require the `format` option to come before the `natbib` option in an author's `\documentclass[...]{acmart}`, but is there more to it than wanting to allow options to come in an arbitrary order?

**Comment by borisveytsman** [comment]
1.  I can define and document two cite styles:  acmnumbers and acmauthoryear.  The format can adjust them, and the author could select them with \citestyle{acmnumbers} or \citestyle{acmauthoryear}.  What do you think?

2.  I do not like to depend on the order of options:  somebody is going to break it.

**Comment by MatthewFluet** [comment]
Yes, I think `\citestyle` would be a good approach; it steers authors away from the lower-level `\setcitestyle`.
