### ISSUE TITLE
v1.57 vspace warning

### ISSUE THREAD

**Issue by chenqiuyuan** [borisveytsman/acmart#341]
In acmart.dtx, why does the following warning always occurred even when I do not use any \vspace command.
Besides, I do not understand why it needs to warn twice.

% \begin{macro}{\vspace}
% \changes{v1.57}{2018/12/16}{Added warning}
% We do not disable \cs{vspace}, but add warning to it
%    \begin{macrocode}
\apptocmd{\@vspace}{\ClassWarning{\@classname}{\string\vspace\space should
    only be used to provide space above/below surrounding
    objects}}{}{} 
\apptocmd{\@vspacer}{\ClassWarning{\@classname}{\string\vspace\space should
    only be used to provide space above/below surrounding
    objects}}{}{} 
%    \end{macrocode}
% 
% \end{macro}

**Comment by borisveytsman** [comment]
Corrected in 1.58
