### ISSUE TITLE
loss of line number in review mode 

### ISSUE THREAD

**Issue by python152** [borisveytsman/acmart#342]
Based on this [SO thread](https://tex.stackexchange.com/questions/346292/how-to-remove-conference-information-from-the-acm-2017-sigconf-template), we can remove running header/footer/copyright from the template for submission.  However, this seems to be in conflict with review mode - the following example shows that first page is okay, and second page it doesn't generate line number anymore. Any idea?

```
\documentclass[sigconf,review]{acmart}
\usepackage{lipsum}

\title{ACM Conference Sample}
\settopmatter{printacmref=false} % Removes citation information below abstract
\renewcommand\footnotetextcopyrightpermission[1]{} % removes footnote with conference information in first column
\pagestyle{plain}
\begin{document}
\maketitle
\section{Introduction}
\lipsum[1-15]
\end{document}
```

**Comment by bennn** [comment]
Try the `nonacm` option instead.

```
\documentclass[nonacm,sigconf,review]{acmart}
\usepackage{lipsum}

\title{ACM Conference Sample}
\begin{document}
\maketitle
\section{Introduction}
\lipsum[1-15]
\end{document}
```

**Comment by python152** [comment]
just tried, this option doesn't remove running header.

**Comment by bennn** [comment]
What version of acmart.cls are you using?

The option was added in v1.54. On an earlier version, adding `nonacm` won't change anything.

**Comment by python152** [comment]
I did an package update first (Mac Texlive 2018), the print out shows it is 1.57.
I also tried it out on Overleaf in case my environment is messed up, it is the same, running header is still there.

**Comment by bennn** [comment]
Ok. I don't know what to say. Here's the `.tex` and `.pdf` I'm seeing.
[test.tar.gz](https://github.com/borisveytsman/acmart/files/3070338/test.tar.gz)

**Comment by python152** [comment]
Here is what I can tell: **with** `acmart.cls` in the directory, and preamble of `noacm, sigconf,review`, I can replicate what you see. Noted that 2nd page line number only appears on the right side; if you change the order to `sigconf, review, noacm`, then line number appear to be correct on both page, but running header comes back.

**without** acmart.cls, i.e., use v1.58 from textlive, then the order doesn't matter, running header is always there.

**Comment by borisveytsman** [comment]
Works in v1.59

**Comment by mlscott14627** [comment]
The fix, I believe, at least for proceedings, belongs in the following lines:

  \else % Proceedings
    \fancyfoot[C]{\if@ACM@printfolios\footnotesize\thepage\fi}%
    \fancyhead[LO]{\ACM@linecountL\@headfootfont\shorttitle}%
    \fancyhead[RE]{\@headfootfont\@shortauthors\ACM@linecountR}%
    \if@ACM@nonacm\else%
      \fancyhead[LE]{\ACM@linecountL\@headfootfont
        \acmConference@shortname,
        \acmConference@date, \acmConference@venue}%
      \fancyhead[RO]{\@headfootfont
        \acmConference@shortname,
        \acmConference@date, \acmConference@venue\ACM@linecountR}%
    \fi
  \fi

I believe it should instead read

  \else % Proceedings
    \fancyfoot[C]{\if@ACM@printfolios\footnotesize\thepage\fi}%
    \fancyhead[LO]{\ACM@linecountL\@headfootfont\shorttitle}%
    \fancyhead[RE]{\@headfootfont\@shortauthors\ACM@linecountR}%
    \if@ACM@nonacm%
      \fancyhead[LE]{\ACM@linecountL}%
      \fancyhead[RO]{\ACM@linecountR}%
    \else%
      \fancyhead[LE]{\ACM@linecountL\@headfootfont
        \acmConference@shortname,
        \acmConference@date, \acmConference@venue}%
      \fancyhead[RO]{\@headfootfont
        \acmConference@shortname,
        \acmConference@date, \acmConference@venue\ACM@linecountR}%
    \fi
  \fi

**Comment by dongpengxu** [comment]
I find that it's because the review mode conflicts with the \pagestyle{plain} command. Simply removing the pagestyle command works, as the review mode already has page numbers. I am using v1.92.
