### ISSUE TITLE
Balancing columns on last page when it's the first

### ISSUE THREAD

**Issue by bradcray** [borisveytsman/acmart#344]
I'm working on a 1-page abstract for inclusion in an ACM / SIGPLAN proceedings and am trying to balance the columns on that page since it's the last page.  What I'm finding is that if I do nothing, the columns are not balanced; yet if I insert a `\balance` command into the first column, the copyright notice gets jammed into the middle of the CCS keywords (see uploaded screenshot of the left column).  Is this a bug, or is there a trick for balancing columns for 1-page abstracts like this?  (or do such 1-page abstracts not require balancing?

<img width="630" alt="Screen Shot 2019-05-09 at 1 21 42 PM" src="https://user-images.githubusercontent.com/7536222/57484456-ea4dc100-725d-11e9-8234-fac2bf4e6739.png">

**Comment by smokhov** [comment]
On Thu, 9 May 2019, Brad Chamberlain wrote:

> Date: Thu, 09 May 2019 13:26:23 -0700
> 
> I'm working on a 1-page abstract for inclusion in an ACM / SIGPLAN 
> proceedings and am trying to balance the columns on that page since it's 
> the last page.  What I'm finding is that if I do nothing, the columns 
> are not balanced; yet if I insert a `\balance` command into the first 
> column, the copyright notice gets jammed into the middle of the CCS 
> keywords (see uploaded screenshot of the left column).  Is this a bug, 
> or is there a trick for balancing columns for 1-page abstracts like 
> this?  (or do such 1-page abstracts not require balancing?

It seems odd to having to have a one-pager balanced like that given that 
the copyright notice should always remain in the same spot at all times...

Not an expert here, but I would say it is OK to leave the one-pager 
unbalanced if you don't have enough text to fill it all in, or, simply, 
add more content to fill it out completely.

-- 
Serguei Mokhov, PhD, Manager, Networks & Security, AITS | /~\    The ASCII
Affiliate @ Computer Science and Software Engineering & | \ / Ribbon Campaign
Concordia Institute for Information Systems Engineering |  X    Against HTML
Gina Cody School of ENCS, Montreal, Quebec, Canada      | / \      Email!
http://www.cs.concordia.ca/~mokhov
---
Co-founder, CCIFF, http://cciff.ca
ET Summit: http://cciff.ca/2018/festival/et/
https://www.youtube.com/channel/UCcJ-jSP6Cya8o-aWoB4l3Pw
---
Technical Lead
http://mdreams-stage.com
http://users.encs.concordia.ca/~gipsy
http://marf.sf.net | http://sf.net/projects/marf

**Comment by bradcray** [comment]
Thanks for weighing in, @smokhov!  I was also wondering if an exception would/could be made for 1-page "abstract" submissions to ACM proceedings (e.g., the abstract of a keynote talk), but it seems that the bot that checks submissions complains if I leave the first page unbalanced, setting up a catch-22.  I'd imagine that the "right" thing to do would be to balance everything other than the copyright text and then to just slap the copyright onto the bottom of the first column.  But unfortunately, this does not seem to happen, at least when using the `\balance` command to do the balancing.

**Comment by bradcray** [comment]
As a workaround for others encountering this issue, I found that if I manually stuck a `\pagebreak` to manually balance the pages, I could get the main text, CCS concepts, keywords all to balance the way I wanted and the copyright ended up at the bottom of the first column.  The submission bot is still complaining at me that the columns aren't balanced (presumably because of the copyright notice itself), but it at least looks reasonable to my eye.

**Comment by bradcray** [comment]
I've since spoken with several other people who've run into the same problem.  It seems specific to one-page documents.  I realize that this isn't a common case for full research papers, but for proceedings that include abstracts for keynote speakers or talk-only submissions it's a problem.

**Comment by borisveytsman** [comment]
I've added the warning to the documentation
