### ISSUE TITLE
Order of affiliation and e-mail address

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#345]
Hi Boris,

The following two snippets lead to visually different PDFs:
```
\author{Dirk Beyer}
\email{Dirk.Beyer@sosy-lab.org}
\affiliation{\institution{LMU Munich}\country{Germany}}
```
versus
```
\author{Dirk Beyer}
\affiliation{\institution{LMU Munich}\country{Germany}}
\email{Dirk.Beyer@sosy-lab.org}
```

Shouldn't the style dictate an order, independently from how the authors put it in the sources?
Just a question ... I have no strong opinion about it.

**Comment by borisveytsman** [comment]
I do not want to enforce the order since we do not have the guidance from SIGS...
