### ISSUE TITLE
"File `acmart.cls' not found." after installing version 1.60 via the Miktex package manager

### ISSUE THREAD

**Issue by kalevalp** [borisveytsman/acmart#346]
There is no .cls file to be found anywhere. 

This is the contents of the package:
![image](https://user-images.githubusercontent.com/6950165/57584696-f0a29e00-74e6-11e9-98e4-33526203509a.png)

**Comment by borisveytsman** [comment]
This looks like a problem with MikTeX.  Filed https://github.com/MiKTeX/miktex-packaging/issues/101
