### ISSUE TITLE
15 authors with the same affliation: Any feasible solution?

### ISSUE THREAD

**Issue by xuhdev** [borisveytsman/acmart#347]
I know a similar issue has been discussed in #98 , but this is a slightly different issue. It is quite a waste of space to list 15 authors in a 5 by 3 array, with each cell uses 5 lines -- in most other templates, this can be solved using no more than 5 lines. Can you offer an elegant solution for this issue?

**Comment by stephennspencer** [comment]
The elegant solution IS to split the author list into three columns, as noted in the User Guide. 

Depending on the length of the affiliation, five columns of three authors each may work, as well.

Remember: each author must be defined separately, and each author must have an affiliation.

**Comment by borisveytsman** [comment]
THanks, @stephennspencer .  I think I can close it now
