### ISSUE TITLE
! LaTeX Error: File `acmart.cls' not found.

### ISSUE THREAD

**Issue by m-bilgic** [borisveytsman/acmart#348]
Using MiKTeX version 2.9.700. Windows 10. Installed the acmart package using the  MiKTeX package manager; updated the package database. Using \documentclass[sigconf]{acmart} in my tex file. pdflatex error: 

> ! LaTeX Error: File `acmart.cls' not found.

**Comment by borisveytsman** [comment]
Duplicates https://github.com/MiKTeX/miktex-packaging/issues/101
