### ISSUE TITLE
\setcopyright{rightsretained} doesn't compile since 99ac418

### ISSUE THREAD

**Issue by binshengliu** [borisveytsman/acmart#349]
```
./dc-abstract.tex:78: LaTeX Error: Can be used only in preamble.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.78 \setcopyright{rightsretained}
```

It compiles if putting the copyright code before `\begin{document}`, but the permission form says the snippet should be placed after `\begin{document}`.

This is since 99ac418

**Comment by borisveytsman** [comment]
Thanks.  The simplest fix to update the documentation.  @Craig-Rodkin, could you please update the permission from stating that `\setcopyright` must be put BEFORE `\begin{document}`?
