### ISSUE TITLE
Suggest use of subcaption in documentation and samples

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#35]
Given the use of the `caption` package, it would seem that the complementary `subcaption` package would be the recommended way to obtain subfigures and subtables.  Recommend the `subcaption` package in the class documentation and demonstrate use in samples.

**Comment by borisveytsman** [comment]
I've added this to the documentation.  I am hesitant about sample - they seem to be already intimidating for a new user.  Perhaps adding new samples demonstrating various features would help?
