### ISSUE TITLE
E-mail split in addresses again (v1.61)

### ISSUE THREAD

**Issue by fniephaus** [borisveytsman/acmart#350]
From the `v1.57` changelog: *E-mail is no longer split in addresses*.
It looks like e-mails are split in addresses again in `v1.61`.

**Comment by borisveytsman** [comment]
Can you provide a minimal example?  Thanks!

**Comment by fniephaus** [comment]
Sure, when I use:

```latex
\author{XXXXX XXXXXXXX}
\affiliation{%
  \department{Xxxxx Xxxxxxxx Xxxxxxxxx}
  \institution{Xxxxxxxxxx xx Xxxxxxx}
  \city{Xxxxxxx}
  \country{Xxxxxxx}}
\email{xxxxx.xxxxxxxx@xxx.xxx-xxxxxxx.xx}

\author{Xxx Xxxxxxxxxxxx}
\affiliation{%
  \institution{Xxxxxx Xxxx}
  \city{Xxxxxxx}
  \country{Xxxxxxx}}
\email{xxx.xxxxxxxxxxx@xxxxxx.xxx}

\author{Xxxxxx Xxxxxxxxxx}
\affiliation{%
  \department{Xxxxx Xxxxxxxx Xxxxxxxxx}
  \institution{Xxxxxxxxxx xx Xxxxxxx}
  \city{Xxxxxxx}
  \country{Xxxxxxx}}
\email{xxxxxx.xxxxxxxxxx@xxx.xxx-xxxxxxx.xx}
```

in `sample-sigplan.tex`, I get this:

![image](https://user-images.githubusercontent.com/2368856/58862255-90031d00-86b0-11e9-823e-449df09c4cc8.png)

**Comment by borisveytsman** [comment]
The breaks here are on `-`.  It was never the intention to forbid breaks on hyphens in email addresses - otherwise long emails would break the author boxes.

**Comment by fniephaus** [comment]
Thanks for the info!
