### ISSUE TITLE
Column balancing doesn't work with footnotes

### ISSUE THREAD

**Issue by mpickering** [borisveytsman/acmart#353]
The `balance` package doesn't work well if their are footnotes on the final page. In this case I was saved because `flushend` worked. 

![image](https://user-images.githubusercontent.com/1216657/60399398-a55a5280-9b5b-11e9-96e5-a3b82bbb901a.png)

Seeing as there is no reliable way to balance two columns in latex, the requirement to do so should be removed from the guidelines.

**Comment by SamuelGong** [comment]
The same issue is observed here. Looking forward to any update.

**Comment by borisveytsman** [comment]
Looks like now it works
