### ISSUE TITLE
Adding extra information to ACM copyright footer

### ISSUE THREAD

**Issue by kammirzazad** [borisveytsman/acmart#355]
I would like add information about grant and conference to the acmsmall's footer, something like [this](http://aceslab.org/sites/default/files/main_journal.pdf) but I am not sure how it could be done without changing acmart.cls.

**Comment by kammirzazad** [comment]
Although not recommended, seems like \thanks{} would the trick. It would place the extra info in the footer right before the authors' address. 
I could not find how to merge two footers (address one and copyright one) in acmart v1.61. I am guessing that this version enforces copyright to be in a separate footer.

**Comment by stephennspencer** [comment]
That content - or at least the grant-specific content - should go into the Acknowledgments section: 

\begin{acks}
We thank reviewers for their insightful comments. This work is supported in parts by ONR (N00014-11-1-0885) and MURI (FA9550-14-1-0351) grants.
\end{acks}

which goes after the last major section and before the references.
