### ISSUE TITLE
What is the "official" way to typeset sans-serif upright math Greek?

### ISSUE THREAD

**Issue by MdAyquassar** [borisveytsman/acmart#358]
For example, to typeset sans-serif upright Ω in math mode, we may say `\mathsf{\upOmega}` for {xe|lua}latex and `\mathsf{\Upomega}` for pdflatex+`\usepackage{upgreek}`.  However, `upgreek` is aged and introduces a little bit too much vertical space. For pdflatex without `upgreek`, we'd have to go with something like `\font\upsfgreek=stix-mathsf \def\upsfOmega{\text{\upsfgreek \char"0A}}`, which introduces one more font. Related: https://tex.stackexchange.com/questions/483715/usepackageslantedgreeknewtxmath-mathsf-upomega-wont-render 

Any "official" suggestion for acmart? Do the packages called from acmart.cls have sans-serif upright math Greek letters under some macro name already, perhaps? As for now, having a macro for sans-serif upright Ω in math mode would make me personally happy, but I'd prefer a general solution rather than a one-off.

**Comment by borisveytsman** [comment]
I am not sure about "official" way.  A rather hackish way is to use OT1 font for sans serif instead of T1 as provided by newtxmath:

```
\documentclass{acmart}
\DeclareMathAlphabet{\mathsf}{OT1}{\sfdefault}{m}{n}
\begin{document}
\[
  \mathsf{\upOmega}
\]
\end{document}

```

However I do not know the position of ACM publishing about upright sans serif Greek.

**Comment by MdAyquassar** [comment]
First and foremost, thank you. Second, your solution is the same as [what @egreg suggested](http://tex.stackexchange.com/a/483720). 

Third, it seemed to me that this solution would have changed the font of all sans-serif maths, not only of the sans-serif upright Greek, right? However, visually, I see no difference in Latin sans-sarif maths, e.g., when compiling

```
\documentclass{acmart}
\DeclareMathAlphabet{\mathsf}{OT1}{\sfdefault}{m}{n}%%% The suggestion of @egreg and @borisveytsman.
\begin{document}
The problem is \(\mathsf{PSpace}\)-complete. %%% <- This text looks the same regardless of the above suggestion.
\[
  f(n)=\mathsf{\upOmega}(n)
\]
\end{document}
```

with our without the suggestion. This absence of changes in sans-serif Latin is good (but I don't see why there are none).
