### ISSUE TITLE
Placement of abstract

### ISSUE THREAD

**Issue by eg9** [borisveytsman/acmart#360]
If the `abstract` environment is placed after `\maketitle` it just disappears without warning. Yes, the manual, on page 17, explicitly warns about this, but do users read manuals?

See https://tex.stackexchange.com/q/503238/4427

This could be cured by adding `\@saveabstract{}` at the end of `\@mkabstract` and also adding a test for emptiness of `\@abstract` at end document:

```latex
\AtEndDocument{\if\relax\detokenize\expandafter{\@abstract}\relax\else<Error: abstract was misplaced>\fi}
```

**Comment by borisveytsman** [comment]
Thanks! 

 I used slightly different logic in my solution: if abstract is used after maketitle, I now produce an error.
