### ISSUE TITLE
Problems with varioref, cleveref, and acmart together

### ISSUE THREAD

**Issue by micahjsmith** [borisveytsman/acmart#364]
I see that cleveref is an oft-discussed topic here.

Following the documentation of cleveref, 

> If you are using both varioref and hyperref, make sure you are loading them in the correct order, otherwise cross-references will reference completely the wrong thing without any warning in the LATEX output or log! The packages mustbe loaded in the following order: varioref, hyperref, cleveref

I generally add as the last three lines in my preamble (even if I do not use one of the packages):

```
\usepackage{hyperref}
\usepackage{varioref}
\usepackage{cleveref}
```

With `article`, `IEEEtran`, and other classes, this works great. But with acmart, this results in undefined references for sections only, while references to figures and tables continues to work.

See the following minimal example:
```
\documentclass{acmart}

\usepackage{varioref}
\usepackage[capitalise]{cleveref}

\begin{document}

\section{Introduction}
\label{sec:intro}
A

\section{Methods}
See \Cref{sec:intro}.

\end{document}
```

This results in the following warning:
```
LaTeX Warning: Cref reference format for label type `' undefined on input line 
13.
```

And the result is that the section reference is `See ??`

Either of the following two changes fix the reference problem in this minimal example:
1. removing `\usepackage{varioref}`
2. changing to a different document class such as `article`

**Comment by borisveytsman** [comment]
You need to run latex twice to resolve the labels.  I do not see problems with your example

[tmp.pdf](https://github.com/borisveytsman/acmart/files/3747117/tmp.pdf)

**Comment by micahjsmith** [comment]
Hi Boris, thanks for your quick response. I always compile files with `latexmk -pdf test.tex` or similar and this does not result in the section references being processed on my system. I just trained manually running `pdflatex test.tex` twice and I still get the undefined references problem. If it seems there is a difference between your system and my system, I'm happy to provide additional debugging information. I will try poking around as well.

**Comment by micahjsmith** [comment]
Manually updating all the packages in my TeXLive distribution (including acmart 2019/08/05 -> 2019/08/24) fixed the problem for me. Thanks.

**Comment by jasonhemann** [comment]
> I see that cleveref is an oft-discussed topic here.
> 
> Following the documentation of cleveref,
> 
> > If you are using both varioref and hyperref, make sure you are loading them in the correct order, otherwise cross-references will reference completely the wrong thing without any warning in the LATEX output or log! The packages mustbe loaded in the following order: varioref, hyperref, cleveref
> 
> I generally add as the last three lines in my preamble (even if I do not use one of the packages):
> 
> ```
> \usepackage{hyperref}
> \usepackage{varioref}
> \usepackage{cleveref}
> ```

Only an FYI since the problem is addressed, but the documentation says it wants `varioref` *before* `hyperref`. Misordering them may cause other issues down the line.
