### ISSUE TITLE
Algorithms and spurious vspace warnings

### ISSUE THREAD

**Issue by vneiger** [borisveytsman/acmart#367]
When using the package "algorithm" which defines a floating algorithm environment, I get warnings about the use of vspace.

Minimal working example:
```latex
\documentclass[acmsmall]{acmart}
\usepackage{algorithm}
\begin{document}
  \begin{algorithm}
    Here is an algorithm
    \caption{Algo}
  \end{algorithm}
\end{document}
```

Notes:
- the warnings do not appear if no caption is inserted
- this has been observed on at least two configurations
- the warning is the following and appears twice: `Class acmart Warning: \vspace should only be used to provide space above/below
surrounding objects on input line 10.`
- this might be related to Issue #341

**Comment by borisveytsman** [comment]
Thanks!

**Comment by zhiqiangzhongddu** [comment]
@borisveytsman Have you got any solution about it? I still have this warning on my side, and I found that it works well with Overleaf. So do I need to upgrade my packages?

**Comment by borisveytsman** [comment]
I've corrected it in v1.66 (to be released soon)

**Comment by lamBOOO** [comment]
I have the same error

> `Class acmart Warning: \vspace should only be used to provide space above/below surrounding objects on input line XXX.`

using the listings package.

Minimal working example:
```
\begin{lstlisting}[
  style=pythonstyle,
  caption={XXX1},
  commentstyle=\color{comment_c}\rmfamily\itshape,
]
a**2 + b**2 = c**2
\end{lstlisting}
```

I think it's related to this issue.

**Comment by ppannuto** [comment]
This same issue is exhibited if the minted package is used to provide the listings environment. MWE:

```
\documentclass{acmart}

\usepackage{minted}

\begin{document}

\begin{listing}
  \caption{caption}
  Foo
\end{listing}

\end{document}
```

Note, under normal usage there is also an interior minted block, like this:

```
\documentclass{acmart}

\usepackage{minted}

\begin{document}

\begin{listing}
  \caption{caption}
\begin{minted}{rust}

//! main.rs
\end{minted}
\end{listing}

\end{document}
```

But this is not necessary to trigger the warning.

**Comment by yegor256** [comment]
@ppannuto any solution found to eliminate this warning?

**Comment by k4rtik** [comment]
Like https://github.com/borisveytsman/acmart/issues/367#issuecomment-570953301 I am facing the same issue with `lstinputlisting` for including code files directly using the listings package.
