### ISSUE TITLE
keywords+maketitle = spurious vspace warning

### ISSUE THREAD

**Issue by guillaumesalagnac** [borisveytsman/acmart#368]
The template always complains about `\vspace` even  when I'm not using it at all. It seems that the problem is triggered by using both the `\maketitle` and `\keywords` commands (removing one makes the warning disappear).
Minimal example below:

```\documentclass{acmart}
\begin{document}
\title{keywords+maketitle = spurious vspace warning}
\keywords{any keyword will do}
\maketitle
\end{document}
```

Is this a "bug" in `acmart.cls`, or am I missing something obvious ?

**Comment by borisveytsman** [comment]
Thanks!

**Comment by k4rtik** [comment]
I am still getting this error with "LaTeX with acmart 2020/11/15 v1.75 [...] and hyperref 2021-02-27 v7.00k Hypertext links for LaTeX".

Commenting out `\keywords{...}` makes the `\vspace` warning go away.

**Comment by borisveytsman** [comment]
Ok, will try to suppress the warning
