### ISSUE TITLE
option nonacm still prints acmArticle

### ISSUE THREAD

**Issue by benediktahrens** [borisveytsman/acmart#369]
The option nonacm should be used to produce a version that does not feature any ACM stuff, and no publication data.

This does not work when \acmArticle is set: with \acmArticle set, e.g., to {X}, even with option nonacm one still gets a block on the right side of the first page, with X printed in it.

**Comment by borisveytsman** [comment]
I cannot reproduce this behavior.  Can you provide a minimal working document?

**Comment by benediktahrens** [comment]
@borisveytsman : Thanks a lot for your answer.

This MWE should not have the black box with "1" printed in the upper right corner, but does have it with acmart 1.65:

```latex
\documentclass[
acmsmall,screen,
authorversion=true,
nonacm=true
]{acmart} 
\settopmatter{printacmref=false, 
              printccs=false, 
              printfolios=true
              }

\acmArticle{1}

\title{Title}
\begin{document}
\maketitle
\end{document}
```

**Comment by borisveytsman** [comment]
Thanks

I think the paper number blob is not specific to ACM.  Imagine a non-ACM journal wanting to create its own class based on acmart (using `\LoadClass`).  This journal might want to use blobs too.

Since blobs are not produced unless `\acmArticle` is explicitly set (it is not by default), I feel I should rather leave them even if `nonacm` is chosen.

**Comment by benediktahrens** [comment]
Thanks a lot for your answer.


> Thanks
> 
> I think the paper number blob is not specific to ACM. Imagine a non-ACM journal wanting to create its own class based on acmart (using `\LoadClass`). This journal might want to use blobs too.

In this case, it is weird that the paper number blob is set by a LaTeX option starting with \acm....
Also, would that non-ACM journal not also want to set a DOI, or a volume number? All of these are also set using \acm... options, and these other options *do* observe nonacm.

> Since blobs are not produced unless `\acmArticle` is explicitly set (it is not by default), I feel I should rather leave them even if `nonacm` is chosen.

The same is true for all the other options starting with \acm, like \acmYear, \acmDOI, etc.

It seems inconsistent to me that the nonacm option makes it that *some* acm options are ignored, but not others. I would probably expect that all the options starting with \acm... observe the nonacm option.
