### ISSUE TITLE
ACM BibTeX Formatting instructions say "location" but code uses "city" for @inproceedings

### ISSUE THREAD

**Issue by fsaad** [borisveytsman/acmart#370]
The [ACM BibTeX Formatting instructions](https://www.acm.org/publications/authors/bibtex-formatting) state that `location` should be used to identify the place a conference (@inproceedings) was held but the code uses `city` instead:

https://github.com/borisveytsman/acmart/blob/c4d61c2ca6c76432906e65248dc03b428a10e1fd/ACM-Reference-Format.bst#L1235-L1239

It seems either (i) the code in this repo should be updated to have "location" be an alias to "city", or (ii) the instructions on the ACM website should be updated.  

The first solution appears to makes more as the ACM knowingly request `location` instead `city` in their instructions and the BibTeX produced on the DL ACM uses `location` not `city`.

**Comment by fsaad** [comment]
Hi @borisveytsman, thank you for the patch.  Does https://github.com/borisveytsman/acmart/commit/74bbbadbb055d12dcf6246841944047dc01ee34d fix the issue?

I think the idea for my ticket was that the user should be able to write "location" in the .bib file as specified in the official ACM instructions and then have it act just as though "city" was specified.  I am not sure that the solution of setting ` FUNCTION {location} {city}` does the trick (based on a simple test I just did using the tip of master).  Instead I think that `FUNCTION { format.city }` should check for either the `city` or `location` fields here:
https://github.com/borisveytsman/acmart/blob/74bbbadbb055d12dcf6246841944047dc01ee34d/ACM-Reference-Format.bst#L1246-L1256

**Comment by borisveytsman** [comment]
Ok, let me redo it

**Comment by pqu** [comment]
Does the ACM really want the location information printed in the reference? The exemplar [ACM reference format](https://www.acm.org/publications/authors/reference-formatting) for their exemplar BibTeX entry does not include the location.

**Comment by borisveytsman** [comment]
I guess this is a question for @Craig-Rodkin

**Comment by fsaad** [comment]
> Does the ACM really want the location information printed in the reference? The exemplar [ACM reference format](https://www.acm.org/publications/authors/reference-formatting) for their exemplar BibTeX entry does not include the location.

@pqu I think the answer is yes, the exemplar ACM reference format for their exemplar BibTeX entry does indeed include the location.  On the URL you pasted, click "Note: For BibTeX examples see: http://www.acm.org/publications/authors/bibtex-formatting".

```
For a (paginated proceedings) article in a conference proceedings (conference, symposium or workshop):
@inproceedings{Andler:1979:PPE:567752.567774,
author = {Andler, Sten},
title = {Predicate Path Expressions},
booktitle = {Proceedings of the 6th ACM SIGACT-SIGPLAN Symposium on Principles of Programming Languages},
series = {POPL '79},
year = {1979},
location = {San Antonio, Texas},
pages = {226--236},
numpages = {11},
url = {https://doi.org/10.1145/567752.567774},
doi = {10.1145/567752.567774},
acmid = {567774},
publisher = {ACM},
address = {New York, NY, USA},
}
```
The ability to include both address (of publisher) and location (of conference) is a strength of the ACM Reference Format, since a common abuse in practice is to write the conference location in the address field of the publisher, see e.g., https://tex.stackexchange.com/questions/76566/how-to-show-the-location-of-a-conference-in-bibtex/77556, which thankfully the ACM bib file can avoid.

**Comment by fsaad** [comment]
My guess is that the ability to include both address (of publisher) and location (of conference) is a strength of the ACM Reference Format, since a common abuse in practice is to write the conference location in the address field of the publisher, see e.g., https://tex.stackexchange.com/questions/76566/how-to-show-the-location-of-a-conference-in-bibtex/77556, which thankfully the latest ACM bib file can avoid.

**Comment by Craig-Rodkin** [comment]
Hi. Thanks for reporting this. ACM wants to capture as much information in the reference as possible. I will have the proceedings entry on the reference formatting webpage updated shortly.

**Comment by krono** [comment]
Please note that this might be incompatible with the default meaning of the fields in BibLaTeX: There, the `location` always refers to the publisher, and `venue` can be used for the place where a conference took place:

> The location of a conference, a symposium, or some other event in `@proceedings` and `@inproceedings` entries.  This field may also be useful for the custom types listed in § 2.1.3. Note that the `location` list holds the place of publication. It therefore corresponds to the `publisher` and `institution` lists.  The location of the event is given in the `venue`  field. See also `eventdate` and `eventtitle`. 

(I'm not implying that the ACM format should change, but I think it would be neat if there was not too grave discrepancy)

**Comment by fsaad** [comment]
@krono I agree avoiding discrepancies would be neat.  The ACM is using natbib, which only works with plain BibTeX not BibLaTeX, for bibliography processing, but users might already have several .bib entries that are formatted for BibLaTeX. Some relevant information:

1. BibTeX default fields only include `address` (which means address of publisher); they do not have a `location` or `venue` field.  A clear shortcoming is that the conference locations cannot be specified, which leads to the [common abuse of writing the venue inside the address field](https://tex.stackexchange.com/questions/76566/how-to-show-the-location-of-a-conference-in-bibtex/77556).

2. BibLaTeX fixes these issues by treating "location" as a synonym for address, and allowing "venue" for conference locations.

Given that `location` in ACM format contradicts `location` from BibLaTeX, it seems sensible to rename `location` to either `venue` or `city` (or both).
