### ISSUE TITLE
SIGPLAN: Keywords, CCS Section titles not printing, large separation between sections

### ISSUE THREAD

**Issue by swapnilh** [borisveytsman/acmart#375]
In the current 1.66 version, the acmart template with sigplan option does not print CCS or the Keywords section title. 

There is also a lot of whitespace/separation between subsections/sections.

I have copied the sample pdf provided with the official acmart zip file here and it shows both these issues:
http://pages.cs.wisc.edu/~swapnilh/resources/sample-sigplan.pdf

**Comment by yunmingzhang17** [comment]
Seeing the same issues.

**Comment by psybers** [comment]
I was unsure if this should be a new bug, or if its just this bug and the fix in be7d687 didn't happen to fix it properly.

But for `\documentclass[sigconf,table,review]{acmart}` papers, starting in 1.66 there was 2 glitches introduced:

1. in CCS, extra space before the first bullet point
2. space between CCS and Keywords was removed so they now touch

It seems the fix here took care of #1, but the second problem still persists.  If I need to file a separate bug, let me know.
----
----
1.65 (this looks fine):
![image](https://user-images.githubusercontent.com/1115390/72225418-49817500-3553-11ea-8e7e-e5f6ec40ff75.png)
----
----
1.66 (has the 2 problems):
![image](https://user-images.githubusercontent.com/1115390/72225434-7afa4080-3553-11ea-899e-efa8b492c9f2.png)
----
----
1.67 (has only second problem):
![image](https://user-images.githubusercontent.com/1115390/72225443-91080100-3553-11ea-8ddc-f5830329b08c.png)

**Comment by borisveytsman** [comment]
Could you file a separate issues with minimal example?  Thanks!
