### ISSUE TITLE
ACM DL BibTeX: articleno includes "Article/Paper" prefix

### ISSUE THREAD

**Issue by mporcheron** [borisveytsman/acmart#379]
The BibTeX generated by the Digital Library for venues which number articles/papers includes the prefix "Article" or "Paper".

e.g., from https://doi.org/10.1145/3173574.3174214:

```
@inproceedings{10.1145/3173574.3174214, 
…
 articleno = {Paper 640}
…}
```

However, it seems the ACM Reference Format style is also adding in the word "Article" when generating the reference. This has the undesirable effect of producing "Article Paper" (in this case, in other cases "Article Article" is generated):

> Martin Porcheron, Joel E Fischer, Stuart Reeves, and Sarah Sharples. 2018. Voice Interfaces in Everyday Life. In Proceedings of the 2018 ACM Conference on Human Factors in Computing Systems (CHI ’18). ACM, New York, NY, USA, **Article Paper 640**, 12 pages. https://doi.org/10.1145/3173574.3174214

I assume this can't be by intent (especially "Article Article")?

**Comment by krono** [comment]
I think that's a problem in the new version of the acmdl. It used to export the bibtext _without_ any prefix,

**Comment by borisveytsman** [comment]
I guess we need to work around the bug :(
