### ISSUE TITLE
Incorrect use and rendering of "series" field for @inproceedings

### ISSUE THREAD

**Issue by fsaad** [borisveytsman/acmart#381]
# Incorrect Behavior

For `@inproceedings` entries, the ACM bib file puts the `series` in between parentheses, which renders incorrectly, as shown below.

```
@inproceedings{hagerup1993,
title        = {Maintaining Discrete Probability Distributions Optimally},
author       = {Hagerup, Torben and Mehlhorn, Kurt and Munro, J. Ian},
booktitle    = {Proceedings of the 20th International Colloquium on Automata, Languages and Programming},
series       = {Lecture Notes in Computer Science},
volume       = {700},
pages        = {253--264},
year         = {1993},
publisher    = {Springer-Verlag},
address      = {Berlin},
}
```
![image](https://user-images.githubusercontent.com/5721897/74092226-fdace780-4a8e-11ea-9e1b-f91184d54197.png)

In the above example, "(Lecture Notes in Computer Science), Vol. 700" renders incorrectly, since parenthesis separate the series name from the volume number.

Note that `series` is rendered correctly for book series that are published in series, i.e., an `@incollection` entry, as shown below:

```
@incollection{trevisan2010,
title        = {Pseudorandomness in Computer Science and in Additive Combinatorics},
author       = {Trevisan, Luca},
booktitle    = {An Irregular Mind: Szemer{\'e}di is 70},
editor       = {B{\'a}r{\'a}ny, Imre and Solymosi, J{\'o}zsef and S{\'a}gi, G{\'a}bor},
series       = {Bolyai Society Mathematical Studies Series},
volume       = {21},
pages        = {619--650},
year         = {2010},
publisher    = {Springer},
address      = {Berlin},
}
```
![image](https://user-images.githubusercontent.com/5721897/74092230-12897b00-4a8f-11ea-8a0b-7d6c97533751.png)

In the above example, the series renders as "Bolyai Society Mathematical Studies Series, Vol. 21", which is correct.

# Reason for the bug

The reason for this problem is that the ACM asks for the short name of the conference in an `@inproceedings` entry to be placed in between parenthesis (see [here](https://www.acm.org/publications/authors/reference-formatting), and in BibTeX the `series` field is abused for that purpose (see [here](https://www.acm.org/publications/authors/bibtex-formatting)); i.e., the ACM asks for the following

```
@inproceedings{sten79,
author    = {Andler, Sten},
booktitle = {Proceedings of the 6th ACM SIGACT-SIGPLAN Symposium on Principles of Programming Languages},
title     = {Predicate Path Expressions},
year      = {1979},
publisher = {Association for Computing Machinery},
address   = {New York, NY, USA},
series    = {POPL '79},
pages     = {226--236},
numpages  = {11},
}
```
![image](https://user-images.githubusercontent.com/5721897/74092239-2503b480-4a8f-11ea-91ca-e47c2ad854e0.png)

It should be noted that, "POPL '79" is the shortname of a conference and not a recurring series with a volume number, unlike "Lecture Notes in Computer Science" or "Bolyai Society Mathematical Studies Series" from the previous examples.  Also, using the series for the shorntame does not give us a way to include both the actual series (i.e., "(ICALP 2013). Lecture Notes in Computer Science, Vol. 700", from the first example.

# Desired behavior

I propose that we first fix the `format.series` FUNCTION to have the following effect.

https://github.com/borisveytsman/acmart/blob/d0e62c88996d1edad1d27fcace402b164bb0c226/ACM-Reference-Format.bst#L1358-L1364
```diff
FUNCTION { format.series }
 {
   series empty.or.unknown
     {""}
-    {" \emph{(\bibinfo{series}{" * series "})}" *}
+    {". \bibinfo{series}{" * series "}" *}
   if$
 }
```

Then we should update the instructions to state that the conference short name should be parenthesized and placed in the same field as `booktitle` (which is standard in BibTeX), so that the overall behavior is as follows:

```
@inproceedings{sten79,
author    = {Andler, Sten},
booktitle = {Proceedings of the 6th ACM SIGACT-SIGPLAN Symposium on Principles of Programming Languages (POPL '79)},
title     = {Predicate Path Expressions},
year      = {1979},
publisher = {Association for Computing Machinery},
address   = {New York, NY, USA},
pages     = {226--236},
numpages  = {11},
}

@inproceedings{hagerup1993,
title        = {Maintaining Discrete Probability Distributions Optimally},
author       = {Hagerup, Torben and Mehlhorn, Kurt and Munro, J. Ian},
booktitle    = {Proceedings of the 20th International Colloquium on Automata, Languages and Programming (ICALP 1993)},
series       = {Lecture Notes in Computer Science},
volume       = {700},
pages        = {253--264},
year         = {1993},
publisher    = {Springer-Verlag},
address      = {Berlin},
}
```
![image](https://user-images.githubusercontent.com/5721897/74092283-b115dc00-4a8f-11ea-873b-415d0830f900.png)

**Comment by borisveytsman** [comment]
@craig-rodkin, what do you think?

**Comment by Craig-Rodkin** [comment]
@borisveytsman going to need to check with someone. Need some time to gather a response

**Comment by stephennspencer** [comment]
+1 for the completeness and clarity of the explanation.

**Comment by alessandropellegrini** [comment]
I see the motivation behind this request, but if you agree to make this change, please introduce a command which we can override from LaTeX in `FUNCTION { format.series }`, like `\showSERIES{}`:

```diff
FUNCTION { format.series }
 {
   series empty.or.unknown
     {""}
-    {" \emph{(\bibinfo{series}{" * series "})}" *}
+    {". \showSERIES{\bibinfo{series}{" * series "}}" *}
   if$
 }
```

Otherwise, this would definitely break backwards compatibility badly. I would have to manually update thousands of entries in my bibliographic database!

**Comment by fsaad** [comment]
I'm not sure what versioning conventions that acmart adheres to---for example, [semver](https://semver.org/) or something else---or what guarantees it provides on API stability. One way to patch this issue would be to have version 1.71 be backward compatible as suggested by @alessandropellegrini and have version 2.0 include this (and other) non-backward compatible changes.

Ultimately, authors of new papers in ACM journals or conferences that use the patched acmart (either 1.71+ or 2.0) should use .bib databases that are updated to include the correct formatting (at least for the subset of entries referenced in the new paper), and older papers should be pinned to a fixed acmart version, rather than have acmart encourage old errors in formatting to be propagated or patched in a non-maintainable way.

**Comment by alessandropellegrini** [comment]
I perfectly agree on this from a software engineering point of view, but I think that having this semversion-like major number increase would waste the effort of having a single consolidated style for all ACM publications.

For my use case this change would be a definite showstopper: I work in a research group of 15 people who collaboratively maintain a single bibtex database. We don't have a bibtex file for each article: we simply use the last version of the group database. So this would entail (maybe over time) to rework the whole large database, which has been curated with a lot of work!

**Comment by borisveytsman** [comment]
@Craig-Rodkin suggests the following solution:

> For inproceedings, I believe the volume number needs to be included before the close of the parens ... Programming (Lecture Notes in Computer Science, Vol. 700). Springer...

I think this will be backward compatible: if the series is actually the short name of the conference, then vol is just absent.  No problem with this?

**Comment by fsaad** [comment]
@borisveytsman How does the proposed solution work to handle the case where there is both a short name and a series, as in the image below for ICALP 1993 in LNCS Vol .700?  

![image](https://user-images.githubusercontent.com/5721897/80753898-1233d580-8afc-11ea-8fd2-cf05bdb40350.png)


Will the new citation include double parenthesis after one another?  That would look wrong to me.

**Comment by Craig-Rodkin** [comment]
>> I think this will be backward compatible: if the series is actually the short name of the conference, then vol is just absent. No problem with this?
Our series data is different from the acronym for this exact reason.

There are very few conference proceedings series:
ICPS, LNCS, LNAI, and a few others.

In the case where there are both, the output should look like

... Programming (ICALP 1993). (Lecture Notes in Computer Science, Vol. 700). Springer...
This does not look visually bad to me as we are separating the proceedings data and series with a period. If we are agreeable to this, then we can implement, otherwise I will need to send this inquiry to the ACM publications board as part of a similar inquiry they need to handle.

Regards,

-Craig

Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>
http://member.acm.org/~rodkin

**Comment by fsaad** [comment]
@Craig-Rodkin I am concerned that the proposed solution will lead to even more inconsistencies. 
Specifically, the proposal appears to be as follows:

1. For ACM venues, the "series" is used for "short name".
2. For venues in a volumed series, the "series" is used for "the volumed series" and the "short name" should be manually parenthesized at the end of "booktitle".

The core issue is that this convention is rather subtle and ad-hoc as far as the BibTeX standards are concerned.  A general user of ACM-Reference-Format.bst who has not delved into the specifics is very likely to make transcription errors when curating .bib files that assume this convention.

As the short names "POPL '79" and "ICALP 1993" are identical syntactic entities, I cannot imagine a user reasonably being expected to write them in fields (series vs. bootktile) and in different formats (manually parenthesized vs unparenthesized) in the .bib files, based on whether the conference appears in a volumed series or not.

The BibTeX standards state that "series" in "@inproceedings" to have identical semantics as series in "@incollection" or in "@book", see, e.g., [Section 3.2 of Patashnik's manual](http://bibtexml.sourceforge.net/btxdoc.pdf).

Can the ACM Publications Board take a look at this issue?  What are the specific constraints that the ACM have regarding this topic?  There are various ways to address the issue sensibly depending on those cosntraints.

**Comment by fsaad** [comment]
@borisveytsman Does https://github.com/borisveytsman/acmart/commit/6ff890353ddbcc3c3bbe4479a5d23d9c739e1a58 fix this issue?  It seems to produce the citation with successive parenthesis, which we were hoping to avoid, per @Craig-Rodkin's suggestion to include the period.

```
@inproceedings{hagerup1993,
title        = {Maintaining Discrete Probability Distributions Optimally},
author       = {Hagerup, Torben and Mehlhorn, Kurt and Munro, J. Ian},
booktitle    = {Proceedings of the 20th International Colloquium on Automata, Languages and Programming (ICALP 1993)},
series       = {Lecture Notes in Computer Science},
volume       = {700},
pages        = {253--264},
year         = {1993},
publisher    = {Springer-Verlag},
address      = {Berlin},
}
```
![image](https://user-images.githubusercontent.com/5721897/81033095-2b23ea00-8e60-11ea-846c-e9d3e5b3eff8.png)

Specifically, @Craig-Rodkin's advice https://github.com/borisveytsman/acmart/issues/381#issuecomment-622084389 was that when there is a volumed series, the output should be:

... Programming (ICALP 1993). (Lecture Notes in Computer Science, Vol. 700). Springer...

**Comment by fsaad** [comment]
Another option is to update the acmart documentation to clarify that the shortname of a conference in a volumed series should be placed at the beginning of booktitle, as is common in books published by e.g., the MIT Press, which gives:

```
@inproceedings{hagerup1993,
title        = {Maintaining Discrete Probability Distributions Optimally},
author       = {Hagerup, Torben and Mehlhorn, Kurt and Munro, J. Ian},
booktitle    = {ICALP 1993: Proceedings of the 20th International Colloquium on Automata, Languages and Programming},
series       = {Lecture Notes in Computer Science},
volume       = {700},
pages        = {253--264},
year         = {1993},
publisher    = {Springer-Verlag},
address      = {Berlin},
}
```
![image](https://user-images.githubusercontent.com/5721897/81033188-98377f80-8e60-11ea-8249-e805d413f3fe.png)

Granted, this proposed convention does cause an inconsistency with the fact that "POPL '79" will appear parenthesized, whereas "ICALP 1993" will not, but this inconsistency is an unavoidable consequence of the ACM's convention to have short names of their conferences be written in "series" fields without an accompaying volume, for reasons that remain unclear to me even after all this discussion.

**Comment by Craig-Rodkin** [comment]
Hi, I have brought this problem to the attention of the ACM publications board, DL subcommittee for review. They will determine a course forward for this problem.

Regards,

Craig

Craig Rodkin
ACM Publications Operations Manager
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>

**Comment by fsaad** [comment]
> Another option is to update the acmart documentation to clarify that the shortname of a conference in a volumed series should be placed at the beginning of booktitle, as is common in books published by e.g., the MIT Press, which gives:

Note that the ACM already uses this formatting when exporting `proceedings`, i.e., the "Export Citation" link at https://dl.acm.org/doi/proceedings/10.1145/3385412 produces the following BibTeX

```
@proceedings{10.1145/3385412,
title = {PLDI 2020: Proceedings of the 41st ACM SIGPLAN Conference on Programming Language Design and Implementation},
year = {2020},
isbn = {9781450376136},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
location = {London, UK}
}
```
