### ISSUE TITLE
Incorrect use of field "primaryClass" for arXiv publications

### ISSUE THREAD

**Issue by fzieris** [borisveytsman/acmart#382]
The field "primaryClass" is used for arXiv references to identify the subject, e.g., "cs.SE" for _Computer Science - Software Engineering_.

Take https://arxiv.org/abs/2002.03121 for example: The URL does not contain the subject identifier. The recommended citation of such a publication is **arXiv:2002.03121 [cs.SE]**, with the subject identifier in square brackets. The following BibTeX snippet is provided by arXiv:

```
@misc{foobarkey,
    ...
    eprint={2002.03121},
    archivePrefix={arXiv},
    primaryClass={cs.SE}
}
```

The `ACM-Reference-Format.bst`, however, renders the `primaryClass` as part of the URL, e.g.,
**arXiv:cs.SE/2002.03121** linking to http://arxiv.org/abs/cs.SE/2002.03121, which is not only a display error but also does **not** work: arxiv.org does not resolve such URLs since [the classification of an arXiv publication is not part of its identifier.](https://arxiv.org/help/arxiv_identifier) (It also uses http:// instead of https://.)

To summarize:
* The expected output for a BibTeX entry with a `primaryClass` field is: `<archivePrefix>:<eprint> [<primaryClass>]`, with the first token linking to `https://arxiv.org/abs/<eprint>`.
* The current (wrong) output is: `<archivePrefix>:<primaryClass>/<eprint>` with the whole thing linking to `http://arxiv.org/abs/<primaryClass>/<eprint>`

The changes probably need to be done in these two places:
* https://github.com/borisveytsman/acmart/blob/d0e62c88996d1edad1d27fcace402b164bb0c226/acmart.dtx#L7084
* https://github.com/borisveytsman/acmart/blob/d0e62c88996d1edad1d27fcace402b164bb0c226/ACM-Reference-Format.bst#L727

Thoughts on implementations:
* This style renders such entries correctly (albeit with "http://"): https://golem.ph.utexas.edu/~distler/TeXstuff/utphys.bst (license unclear)
* Adding a second optional argument to `\showeprint{}` would seem overly complicated to me. I'd propose to not hand over the responsibility form the .bst to the .cls file, but instead create the correct output for the .bbl file more directly.

I'm not sure about backwards compatibility issue, so I did not create a PR myself.

**Comment by krono** [comment]
Sidenote: BibLaTeX handles arXiv correctly by default, if the fields are given as such:
```
@misc{foobarkey,
    ...
    eprint={2002.03121},
    eprinttype={arXiv},
    eprintclass={cs.SE}
}
```

**Comment by fzieris** [comment]
Thanks for the hint. I'm using BibTeX, though, and it's not in my hands to change that anytime soon.

**Comment by krono** [comment]
Yes, it was more a hint to the maintainers.

**Comment by fzieris** [comment]
Thanks, @borisveytsman 👍
