### ISSUE TITLE
doi and url

### ISSUE THREAD

**Issue by SZH1230456** [borisveytsman/acmart#383]
I am using the 1.70 version with xeLatex, but when I use the bib file as follows:
![image](https://user-images.githubusercontent.com/38172534/77553311-9c7e8d80-6eef-11ea-80e0-cb3f8352241a.png)
I got the error with 
![image](https://user-images.githubusercontent.com/38172534/77553382-b4eea800-6eef-11ea-96be-bd6b3c09a763.png).

How could I fix it?

**Comment by krono** [comment]
Hi, wild guess, but why not use the `DOI` Field like that:

```BibTeX
doi={10.1016/j.jbi.2019.103303},
```

**Comment by borisveytsman** [comment]
ok, I'll close this
