### ISSUE TITLE
tweak to header and content typeface sizes...

### ISSUE THREAD

**Issue by stephennspencer** [borisveytsman/acmart#390]
The content of the "CCS Concepts" and "Additional Key Words and Phrases" sections of a formatted journal article uses a larger typeface size than the headers of these sections. 

Proposal: render the content in the same typeface size as the header.
![Screen Shot 2020-05-05 at 3 58 40 PM](https://user-images.githubusercontent.com/22179327/81124176-a7aedb00-8ee9-11ea-820c-b2eed29c9d4d.png)

**Comment by borisveytsman** [comment]
Which format is this?  I do not see this effect in my samples...

**Comment by stephennspencer** [comment]
I will try to provide a test case.
