### ISSUE TITLE
redefined symbol error in v1.70 - \Bbbk

### ISSUE THREAD

**Issue by stephennspencer** [borisveytsman/acmart#395]
When using v1.70, adding the "amssymb" package generates the following error:

...
[testcase.txt](https://github.com/borisveytsman/acmart/files/4652129/testcase.txt)

\usepackage{amssymb}
...

/usr/local/texlive/2020/texmf-dist/tex/latex/amsfonts/amssymb.sty:261: LaTeX Error: Command `\Bbbk' already defined

l.261 ...ol{\Bbbk}.       {\mathord}{AMSb}{"7C}

(Using TeXShop v4.44, and TeXLive 2020.)

**Comment by borisveytsman** [comment]
You should not add this package since it is included in `acmart` by default.  

I will update the documentation

**Comment by csetzer** [comment]
'acmart' loads '/usr/share/texlive/texmf-dist/tex/latex/newtx/newtxmath.sty'  and I found the following post
[https://tex.stackexchange.com/questions/564075/can-newtxmath-be-used-with-amssymb-in-pdflatex](url)
which says:
   "Can `newtxmath` be used with `amssymb` in PDFLaTeX?"

   Answer:  "The literal answer to what you asked is: yes, but you don’t want to. As egreg brought up in the comments, newtxmath defines every symbol that amssymb does, designed to match Times. The amssymb symbols are designed to go with Computer Modern"

So the solution is not to include `amssymb.sty`
