### ISSUE TITLE
Switch from libertine to libertinus

### ISSUE THREAD

**Issue by Blaisorblade** [borisveytsman/acmart#398]
Libertinus improves on Libertine in many ways:
- supports Unicode-math/XeTeX/LuaTeX better (https://github.com/borisveytsman/acmart/issues/255#issuecomment-605318513)
- is nowadays compatible with pdflatex (via https://ctan.org/pkg/libertinus and https://ctan.org/pkg/libertinus-type1).
- fixes many libertine bugs in output, kerning, etc.
- is a healthy [GitHub](https://github.com/alerque/libertinus) project, with a public issue tracker, multiple contributors, is more responsive to bug reports...

**Comment by Blaisorblade** [comment]
The latest straw was the horrible kerning in $\Gamma,$, the correct output would require sth. like $\Gamma \mkern-2mu ,$!

**Comment by borisveytsman** [comment]
We need to discuss this with ACM publishing people

**Comment by rionda** [comment]
Could this switch also somehow enable the use of unicode-math?

**Comment by Blaisorblade** [comment]
At a glance it sounds likely — Libertinus supports OTF/XeTeX/LuaTeX (https://ctan.org/pkg/libertinus-otf), and Libertinus-OTF docs mention unicode-math (page 2 on https://ftp.tu-chemnitz.de/pub/tex/fonts/libertinus-otf/doc/libertinus-otf-doc.pdf). Judging from my OP, Libertinus supported XeTeX first, and only later added support for PDFTeX.

**Comment by Blaisorblade** [comment]
I revised the OP to collect all arguments for the switch.

**Comment by borisveytsman** [comment]
@craig-rodkin:  I can make samples with improved fonts.  Would ACM publishing people consider making a switch?

-B

**Comment by Craig-Rodkin** [comment]
Hi Boris,

The font change from Libertine to Libertinus has been on the table for a while, but did not have a way to move it forward. We now have a group of volunteers who will review and approve the changes. Please move forward and create the samples for me to forward to the group of volunteers for review and possible adoption. thanks

**Comment by luileito** [comment]
Maybe related: With the latest `texlive-full` installation (2019.20200218-1) and `fonts-linuxlibertine` (5.3.0-4) I can't see the summation symbol (`+`) in the generated PDF (using pdflatex for compilation).

I see the following warning in the log file:
```
Missing character: There is no \CF in font ntxsy!
```
If I remove the `newtxmath` package from `acmart.cls` then everything looks fine, though the equations are rendered in plain TeX style.

Hopefully Libertinus will solve this issue, too.

**Comment by zackw** [comment]
I get a bunch of font-related PDF/A validation errors with libertinus that didn't happen with the existing acmart font choices, e.g.
```xml
<rule specification="ISO 19005-2:2011" clause="6.2.11.5" testNumber="1"
      status="failed" passedChecks="0" failedChecks="6">
  <description>For every font embedded in a conforming file and used
    for rendering, the glyph width information in the font dictionary
    and in the embedded font program shall be consistent.</description>
  <check status="failed">
    <context>
       root/document[0]/pages[11](575 0 obj PDPage)
       /contentStream[0](576 0 obj PDContentStream)/operators[723]
       /usedGlyphs[0](NRSLNG+LibertinusMono-Regular 46 0  0)
    </context><context>
      root/document[0]/pages[7](447 0 obj PDPage)
      /contentStream[0](448 0 obj PDContentStream)/operators[862]
      /usedGlyphs[8](VLVSGB+LibertinusSans-Italic 115 0  0)
    </context><context>
      root/document[0]/pages[0](6 0 obj PDPage)
      /contentStream[0](24 0 obj PDContentStream)/operators[714]
      /usedGlyphs[7](ENRMFQ+LibertinusSans-Bold 87 0  0)
    </context><context>
      root/document[0]/pages[11](575 0 obj PDPage)
      /contentStream[0](576 0 obj PDContentStream)/operators[723]
      /usedGlyphs[1](NRSLNG+LibertinusMono-Regular 99 0  0)
    </context><context>
      root/document[0]/pages[10](544 0 obj PDPage)
      /contentStream[0](545 0 obj PDContentStream)/operators[964]
      /usedGlyphs[0](TRDYWN+LibertinusMono-Bold 116 0  0)
    </context><context>
      root/document[0]/pages[6](360 0 obj PDPage)
      /contentStream[0](361 0 obj PDContentStream)/operators[752]
      /usedGlyphs[3](ZOXRJL+LibertinusMono-Oblique 45 0  0)
    </context>
  </check>
</rule>
```

(excerpt of veraPDF report for a paper I happen to be working on today, after adding `\usepackage{libertinus}` to the preamble, lightly edited for readability)

This is probably a bug in the fonts themselves but I figured you should be aware of the problem when deciding whether and when to change acmart.cls.
