### ISSUE TITLE
Declaring a new theorem that uses same counter as the acmthm?

### ISSUE THREAD

**Issue by fsaad** [borisveytsman/acmart#399]
When using `acmart.cls`, is it possible to define new theorems in the user's source file that use the `theorem` counter?  For example, including the following in the source file fails:
```latex
\theoremstyle{acmdefinition}
\newtheorem{remark}[theorem]{Remark}
```

with the error
```
LaTeX Error: No counter 'theorem' defined. [\newtheorem{remark}[theorem]{Remark}]
```

My guess is that the failure occurs because `acmart.cls` uses `\AtEndPreamble` to define the `acmthm` styles:
https://github.com/borisveytsman/acmart/blob/f61c0ae22d0c98a561dec6484796d996563579bf/acmart.dtx#L6974-L7001

Is there a way to add new theorems that share the `theorem` counter without modifying the `.cls` file or redefining theorem/lemma/conjecture/etc. again in the user's source file?

**Comment by fsaad** [comment]
Related perhaps:
- https://github.com/borisveytsman/acmart/issues/138
- https://github.com/borisveytsman/acmart/issues/196
- https://github.com/borisveytsman/acmart/pull/210

**Comment by borisveytsman** [comment]
Either putting the commands after `\begin{document}` or inside `AtEndPreamble` like

```
\AtEndPreamble{%
\theoremstyle{acmdefinition}
\newtheorem{remark}[theorem]{Remark}}

```
works

**Comment by benediktahrens** [comment]
It would be great if this was documented in the manual for `acmart`. Specifically, it would fit well into Section "2.7 Theorems".

**Comment by borisveytsman** [comment]
Ok, let's update documentation
