### ISSUE TITLE
class option `draft` does not mark overfull lines

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#4]

**Comment by borisveytsman** [comment]
To tell the truth, draft option is not very useful since microtype package works differently in the draft and final mode.  Added it nevertheless.

**Comment by ayman** [comment]
I think the purpose of draft is not to look for overfull but to allow for things like margin notes.

**Comment by borisveytsman** [comment]
Aha.  I intend for this the option 'review=true' (the option 'draft' is overused by other packages, so better to leave it alone).

Right now this option only prints the line counting ruler (to enable communications like 'See error on page 3, line 5').  However, if there is an interest, I can put there the editorial system I developed for Res Philosophica (see section 2.3.2 in the manual at http://www.ctan.org/pkg/resphilosophica).

**Comment by borisveytsman** [comment]
P. S.  Note that in this case I will need to put larger paper sizes in the review mode, otherwise there is no space for the comments...

**Comment by ayman** [comment]
Just to follow up on a correction, we had a "chi_draft" option set not a "draft" one for the same collision reasons @borisveytsman mentioned.

**Comment by borisveytsman** [comment]
It would help if editors would formulate requirements for the review option.  Since it does not change the final typesetting (with review=false), we can add features to it even when the class is in the production mode.

**Comment by MatthewFluet** [comment]
For SIGPLAN (and I would guess for most conference proceeding), there is no editor per se and individual reviewers only look at generated PDFs; that is, feedback to the author is never incorporated into source files.  So, with `review=true`, page numbers and line numbers are both very helpful; margin notes wouldn't be particularly helpful for conferences.
