### ISSUE TITLE
fontenc with T5 breaks fonts

### ISSUE THREAD

**Issue by samth** [borisveytsman/acmart#401]
If I include `\usepackage[T1,T5]{fontenc}` in an acmart document, it breaks the default fonts, causing them to revert to computer modern and no monospaced font. I'd like to be able to include Vietnamese text in my document (for a co-author's name) but I'm unable to get anything to work with the correct fonts for acmart.

(Note that using XeTeX works, but is not allowed in some contexts, such as arXiv.)

cc @dvanhorn

**Comment by samth** [comment]
Here's a reduced example. As is, it compiles correctly with `pdflatex` but uses the wrong fonts. If you take out the two `\usepackage` lines, then the fonts are correct, but the `\author` line labeled "does not work" doesn't work (has a LaTeX error). 

```
\documentclass[acmsmall,screen,10pt]{acmart}
% these two lines enable the accented characters
\usepackage[vietnamese]{babel}
\usepackage[T1,T5]{fontenc}
\begin{document}
\title{TITLE}
%\author{Nguyn} % works
\author{Nguyễn} % does not work

\begin{abstract}
  xxx
\end{abstract}
\maketitle
\end{document}
```

**Comment by borisveytsman** [comment]
It looks like Type1 version of Linux Libertine does not have T5 encoding set up.  Fortunately, you can typeset your document with XeTeX.

**Comment by samth** [comment]
Sorry that I missed this follow-up but this is not sufficient. XeTeX works great, but some situations prohibit it, as I said in my initial comment.

**Comment by samth** [comment]
Can you please reopen this issue? It continues to be a problem.

**Comment by borisveytsman** [comment]
Now accented characters work with unicode engines and acmart
