### ISSUE TITLE
Color of hyperlinks

### ISSUE THREAD

**Issue by vsahil** [borisveytsman/acmart#409]
I am using Acmart sty file for a paper. Here is the document class: `\documentclass[sigconf,anonymous,review]{acmart}`. I am adding a href (using `hyperref` package) like `\href{http://www.sharelatex.com}{Something 
Linky}`. The printed text in the PDF (Something Linky) is not colored, it is simple black like other normal text. How can I get it colored? Here is the hypersetup I am using:

`\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
    breaklinks=true
}`

**Comment by borisveytsman** [comment]
You need `\documentclass[sigconf,anonymous,review, screen]{acmart}`

In screen mode links are colored.
