### ISSUE TITLE
screen colors mandatory?

### ISSUE THREAD

**Issue by rosstex** [borisveytsman/acmart#411]
The acmart documentation implies that we can choose colors:

``
While printed ACM publications are usually black and white, screen mode allows the use of colors. The ACM classes pre-define several colors according to [7]: ACMBlue, ACMYellow, ACMOrange, ACMRed, ACMLightBlue, ACMGreen, ACMPurple and ACMDarkBlue. You can use them in color assignments.
``

But the .cls overwrites any other color schemes:
```
\AtEndPreamble{%
  \if@ACM@screen
    \hypersetup{colorlinks,
      linkcolor=ACMPurple,
      citecolor=ACMPurple,
      urlcolor=ACMDarkBlue,
      filecolor=ACMDarkBlue}
    \else
    \hypersetup{hidelinks}
...
```

So are DarkBlue and Purple the only allowed colors currently?

**Comment by borisveytsman** [comment]
The color scheme in *links* is mandatory.  However, you may choose other colors  from the scheme for figures and other graphic elements.

**Comment by pourdamghani** [comment]
Hi @borisveytsman ,

Thank you a lot for all of your answers and efforts. I really appreciate that.

I'm aware of the [2016 thread](https://github.com/borisveytsman/acmart/issues/1) on the fact that "ACM Senior Editors" has proposed ACMPurple for cite color.
However, the original  ACM Green color that you proposed is a better option, and in general, giving flexibility to authors might be nicer. 
I understand that this was an ACM choice, and ACM can decide how their template should look, but I think resurfacing this decision after seven years might be worthy, especially as other "famous" templates allow for the color change now :)

Update: I have finally found your answer about this in another thread on how we can change colors to set our own. Thanks :)
