### ISSUE TITLE
Reconsider: ORCIDs are not displayed

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#416]
This is a follow-up on issue #337.

Other publishers put a little green label next to the author name which has a hyperlink to the ORCID URL of the author.

Example: https://link.springer.com/content/pdf/10.1007%2F978-3-030-53291-8_10.pdf

I propose to do something similar for ACMART.

**Comment by borisveytsman** [comment]
Closed by commit c022e91073f14dbc7f8a3bead5997dbc236e5027
