### ISSUE TITLE
Change citation color

### ISSUE THREAD

**Issue by shadrackkibet** [borisveytsman/acmart#417]
How can I change my citation colour? e.g [1] when I use `\cite{}` it uses the default black colour. I would like to use a different colour preferably orange.

**Comment by borisveytsman** [comment]
Normally you do not want to do this, because the look of the document is set up by ACM requirements.   However, if you **really** want this, use `\AtEndPreamble{\hypersetup{colorlinks, citecolor=orange}}` in the preamble
