### ISSUE TITLE
tabularx missing

### ISSUE THREAD

**Issue by sven-mayer** [borisveytsman/acmart#419]
According to the official ACM explanation on whitelisted packages tabularx should be included in the acmart template, see: https://www.acm.org/publications/taps/accepted-latex-packages However, it seems to be missing. Is there any chance to add the package to the project?

Thanks

**Comment by borisveytsman** [comment]
Sorry for the misunderstanding.  Whitelisting means you *may* include the package in your paper, but it does not imply it is included by default.

**Comment by sven-mayer** [comment]
@borisveytsman I’m yes I understand that but tabularx is specifically mentioned in the section “Please note that the following packages are included in the "acmart" package” - I would assume this means it should be included directly, not?
