### ISSUE TITLE
A simple hello world doesn't compile anymore

### ISSUE THREAD

**Issue by zoharl3** [borisveytsman/acmart#421]
You broke something in the current version. The following used to work in version 2020/01/11 v1.67:

```
\documentclass{acmart}
%\documentclass{article}

\begin{document}
hello world
\end{document}

```

**Comment by krono** [comment]
Can you give a little bit more context? For example, what do you mean by “broke”? Does it complie, do you see any errors?

**Comment by zoharl3** [comment]
It used to compile, now it doesn't:

```
! Undefined control sequence.
\@acmBooktitle ...ceedings of \acmConference@name
                                                  \ifx \acmConference@name \...
l.7 \end{document}

?
```

**Comment by albertnetymk** [comment]
https://ctan.org/pkg/acmart?lang=en still hosts the buggy version 1.75; maybe updating it there as well?

**Comment by borisveytsman** [comment]
Released new version
