### ISSUE TITLE
ACM Documentation discrepancy on provided packages

### ISSUE THREAD

**Issue by krono** [borisveytsman/acmart#422]
The follwing packages [are documented as “included in the "acmart" package”](https://www.acm.org/publications/taps/accepted-latex-packages):

 * `amsmath`
 * `array`
 * `booktabs`
 * `caption`
 * `fancyvrb`
 * `graphicx`
 * `hypdoc`
 * `libertine`
 * `longtable`
 * `newtxmath`
 * `tabularx`
 * `zi4`

The following packages are actually loaded by acmart:
 * `amsmath` (via AMSART)
 * `booktabs`  
    ```
     acmart.dtx:2453:\RequirePackage{booktabs}
    ```
 * `caption`  
    ```
     acmart.dtx:3369:\RequirePackage{caption, float}
    ```
 * `graphicx`:  
    ```
     acmart.dtx:2932:\RequirePackage{graphicx}
    ```
 * `libertine`  
    ```
    acmart.dtx:3244:    \RequirePackage[tt=false]{libertine}
    acmart.dtx:3249:      \RequirePackage[tt=false]{libertine}
    acmart.dtx:3252:       \RequirePackage[tt=false, type1=true]{libertine}
    ```
 * `newtxmath`  
    ```
    acmart.dtx:3244:    \RequirePackage[tt=false]{libertine}
    acmart.dtx:3248:      \RequirePackage[libertine]{newtxmath}
    acmart.dtx:3249:      \RequirePackage[tt=false]{libertine}
    acmart.dtx:3252:       \RequirePackage[tt=false, type1=true]{libertine}
    ```
* `zi4`  
    ```
    acmart.dtx:3253:       \RequirePackage[varqu]{zi4}
    ```

The following packages are *not* loaded by either acmart or amsart:
 * `array`
 * `fancyvrb`
 * `hypdoc`
 * `longtable`
 * `tabularx` (see #419)

Should the page at ACM be updated or are these inteded to be included? (cc @Craig-Rodkin)

**Comment by Barlium** [comment]
@krono I can confirm that the aforementioned packages are not loaded automatically if including acmart. I ran into the same problem with the _longtable_ and _caption_ packages not being loaded if including the acmart package. 

I believe that there is a misunderstanding, I think that you **_may_** include said packages (in like 'they are accepted by the TAPS system), however they are not loaded directly if using acmart.

**Comment by tadd** [comment]
I just ran into this problem. What kind of work was done on last week's "completed" above? I couldn't find the corresponding commit, and [the ACM page description](https://authors.acm.org/proceedings/production-information/accepted-latex-packages#:~:text=do%20not%20include) remains intact.

Do I/We need to contact one of [`@hq.acm.org` people](https://authors.acm.org/contact-us)?

**Comment by Craig-Rodkin** [comment]
Hi @krono and @tadd,

Thank you for pointing this out. I'll have the ACM webpage updated shortly. Keeping this ticket closed.

**Comment by tadd** [comment]
@Craig-Rodkin  Thank you for the mention. Unfortunately, we can confirm that `\RequirePackage` has obviously been used more than 7 times in [`amsart.cls`](https://svn.tug.org:8369/texlive/trunk/Master/texmf-dist/tex/latex/acmart/acmart.cls?pathrev=73261&view=markup).

Here is my result of `sed -nr '/RequirePackage/s/.*\{(.*)\}.*/\1/p' acmart.cls|sort -u` with some editing. This should be a more accurate list.

* babel
* balance
* booktabs
* caption
* cmap
* comment
* draftwatermark
* environ
* etoolbox
* fancyhdr
* float
* fontenc
* framed
* geometry
* graphicx
* hyperref
* hyperxmp
* iftex
* libertine
* manyfoot
* microtype
* natbib
* newtxmath
* pbalance
* refcount
* setspace
* totpages
* unicode-math
* xcolor
* xkeyval
* xstring
* zi4
* zref-savepos
* zref-user

Is it possible to correct the "do not include" list?
In that case, the accepted list containing some of the above should also be modified.
