### ISSUE TITLE
Recommended affiliation annotations for a pseudonymous author?

### ISSUE THREAD

**Issue by zackw** [borisveytsman/acmart#424]
I'm preparing the camera-ready version of an article for an ACM conference. One of the authors wishes to be identified only by a pseudonym, and to not reveal any contact or affiliation information.  With acmart 1.75, `\affiliation{}` now triggers a hard error (due to the lack of any country information).  Is there a recommended construct to use to make the package (and the editors) happy?

**Comment by borisveytsman** [comment]
`\country{Withdrawn}` or `\country{Somewhere on Earth}` would not trigger an error.  Please discuss this option with the editors.
