### ISSUE TITLE
don't load hyperref from class file, or failing that, load hyperxmp before hyperref

### ISSUE THREAD

**Issue by zackw** [borisveytsman/acmart#425]
acmart.cls loads the hyperxmp package after the hyperref package.  This means hyperref does not recognize hyperxmp's additional options as package options, and this in turn means it is impossible to set the PDF/A conformance level, because those options are silently ignored if used in `\hypersetup`.

My recommended fix for this would be to *not load hyperref or hyperxmp* from the class file, but instead say that authors must load both of them themselves, with code like

``` tex
\usepackage{hyperxmp}
\usepackage[...]{hyperref}
\usepackage{cleverref}
\usepackage{bookmark}
```

after all other `\usepackage` invocations; this would avoid the various problems with loading hyperref too early that are described in the hyperref manual.  acmart.cls could use `\PassOptionsToPackage` to set options for hyperref.

I appreciate there are reasons why you might prefer not to do that, in which case please at least apply this patch:

``` diff
diff --git a/acmart.cls b/acmart.cls
index 1135130..ae6ab1f 100644
--- a/acmart.cls
+++ b/acmart.cls
@@ -489,6 +489,7 @@
 \def\@makefnmark{\hbox{\@textsuperscript{\normalfont\@thefnmark}}}
 \let\@footnotemark@nolink\@footnotemark
 \let\@footnotetext@nolink\@footnotetext
+\RequirePackage{hyperxmp}
 \RequirePackage[bookmarksnumbered,unicode]{hyperref}
 \pdfstringdefDisableCommands{%
   \def\addtocounter#1#2{}%
@@ -526,7 +527,6 @@
   \fi
   \hypersetup{pdflang={en},
     pdfdisplaydoctitle}}
-\RequirePackage{hyperxmp}
 \if@ACM@natbib
   \let\citeN\cite
   \let\cite\citep
```

so that I can use `\PassOptionsToPackage` prior to `\documentclass` to set the PDF/A conformance level. I have verified that this construct succeeds in annotating a PDF as PDF/A level 2u conformant if the above patch is applied:

```tex
\pdfminorversion=7
\PassOptionsToPackage{
  final,
  pdfa,
  pdfapart=2,
  pdfaconformance=u,
  pdftex
}{hyperref}
\documentclass[sigconf]{acmart}
...
```

You might also want to consider adding `pdfa,pdfapart=2,pdfaconformance=u` to the options passed to hyperref by acmart.  PDF-A level 2u is a better default than 1a or 1b nowadays, since it handles text in any language supported by Unicode.

**Comment by krono** [comment]
I was under the impression that `hyperxmp` should be best loaded after `hyperref`. Is this no longer true?
Also, the following should work with either load order:

```
\PassOptionsToPackage{pdfa}{hyperref}
\AtBeginDocument{hyperxmp}{\hypersetup{pdfapart=2, pdfaconformance=u}}
```

**Comment by zackw** [comment]
@krono The hyperxmp documentation says it must be loaded "anywhere before the hyperref PDF options are specified". In the context of acmart, that translates to "before hyperref  is loaded" because acmart loads hyperref with options.

I don't know if the pdfa... options are *supposed* to work in `\hypersetup`, but I do know that in my testing (with acmart, and with `hyperxmp 2020/11/22 v5.9`, `hyperref 2020-05-15 v7.00e`, pdftex, and generally TeX Live 2020.20210202 as packaged by Debian) they *don't* work.  They are silently ignored in `\hypersetup`.

**Comment by borisveytsman** [comment]
Hmmm.  @spakin, what is your advice?

**Comment by spakin** [comment]
> Hmmm. @spakin, what is your advice?

I believe that `pdfa` does need to be passed to `hyperref` at load time.  The other PDF/A-related options can be used in an ordinary `\hypersetup`, not necessarily delayed to the `\begin{document}`.  The following works for me with `acmart` bbe09344a6928a9c277978e99705637c6fbf16f0 and an up-to-date TeX Live 2020 (`hyperref 2021-02-10 v7.00` and `hyperxmp 2020/11/22 v5.9`):

```LaTeX
\PassOptionsToPackage{pdfa}{hyperref}
\documentclass[sigconf]{acmart}
\hypersetup{pdfapart=2, pdfaconformance=u}
```

and that strikes me as a not-too-onerous solution.

I don't believe it matters in which order `acmart` loads `hyperref` and `hyperxmp`.  The `unicode` option is the only one that gives me pause, but I *think* `hyperxmp` doesn't check for Unicode usage until after package load time, anyway.

**Comment by borisveytsman** [comment]
Thanks!

**Comment by jS5t3r** [comment]
Before '\documentclass', I added '\DocumentMetadata{}' solved for me

**Comment by ulysses4ever** [comment]
@jS5t3r have you tried to update acmart.cls to the latest version? It should fix the problem without any magic commands.
