### ISSUE TITLE
"ACM reference format is mandatory for papers over one page." even when it is chosen

### ISSUE THREAD

**Issue by k4rtik** [borisveytsman/acmart#431]
Hi

I am using TeX Live 2021 and seeing this warning even when I have the line 
```
\bibliographystyle{ACM-Reference-Format}
```
in my document. ~~The warning doesn't appear on Overleaf which still uses TeX Live 2020.~~

EDIT: actually it appears on Overleaf too, it is just not highlighted in the interface.

**Comment by k4rtik** [comment]
It turns out, there is a line in the log:
```
Class acmart Info: Suppressing bibformat on input line 3.
```
which may be the source of this warning. The input line includes the option `printacmref=false` toggling which makes the warning go away.

I think the warning is misleading.

**Comment by stephennspencer** [comment]
The warning has nothing to do with the references, per se. It is warning that the "ACM Reference Format" block of text is being suppressed. Are you, perhaps, issuing this command in your LaTeX source: \settopmatter{printacmref=false} ?

**Comment by borisveytsman** [comment]
I probably should add the line "Please use bibformat=true option to the warning"

**Comment by stephennspencer** [comment]
I don't use TeX Live 2021 (yet), nor do I know anything about a "bibformat=true" option - that's not something listed in the LaTeX class documentation file. The original poster hasn't yet commented as to whether they are attempting to suppress the "ACM Reference Format" block.

That said, I was not aware that this was optional for articles of any length, even single-page documents. I am aware that the CCS and keywords are optional for one- and two-page documents, but nothing more.

**Comment by k4rtik** [comment]
I am using the recommended template from [SIGPLAN for double-blind reviewing](http://www.sigplan.org/sites/default/files/acmart/current/acmart-pacmpl-template.tex) that does have the `printacmref=false` as a class option:

```
%% For double-blind review submission, w/o CCS and ACM Reference (max submission space)
\documentclass[acmsmall,review,anonymous]{acmart}\settopmatter{printfolios=true,printccs=false,printacmref=false}
```

My point is that the warning suggests to the user that they are not using the ACM-Reference-Format bibstyle, but that's not what is triggering the warning.

I am not sure what `bibformat=true` this does.

**Comment by MatthewFluet** [comment]
Note that those SIGPLAN templates are mostly deprecated; they are no longer linked from http://sigplan.org/Resources/Author/.  They may well be out of date with respect to the most recent acmart.

**Comment by k4rtik** [comment]
Either way, the warning is misleading if all it is triggered by is `printacmref=false`.

**Comment by borisveytsman** [comment]
I've added a clearer warning

**Comment by andreasabel** [comment]
I think this warning should not be raised in `review` or `anonymous` modes, but I open a new issue for this.
- #551
