### ISSUE TITLE
ACM-Reference-Format: Article citation slightly uncommon?

### ISSUE THREAD

**Issue by dbeyer** [borisveytsman/acmart#432]
I have two questions about the formatting of journal articles by the ACM-Reference-Format:

1. Normally, for volume 20 and number 4, references are using "20(4)". But here it is printed as "20, 4".
    I like the convention with the parentheses a bit better because is seems to be more common and
    there are also article numbers and pages appended by comma.

2. The year is printed twice, once after the authors and once after the volume and number.
    Isn't this redundant?

I just want to find out if it was explicitly decided to be like that or if it is by incidence like that and should be corrected.

**Comment by borisveytsman** [comment]
I think @craig-rodkin knows better.  AFAIK, both these formatting decisions were made explicitly long ago.  In particular, the doubling of year was discussed several times in my memory, and ACM editors always insisted on the way it is done now.

**Comment by Craig-Rodkin** [comment]
Hi Dirk and Boris,

This has been discussed numerous times in the past and the formatting will not change. thanks

**Comment by rionda** [comment]
But can we *please* get a *reason* why the year gets printed twice? Like, why is it useful to repeat this information? Is there historic precedent (and why do we need to follow it?)?

Honestly, I find that the transparency that @borisveytsman is offering by having this public repo is all but hindered by ACM's behavior of deciding the format behind what appear to be closed doors and giving no reasoning behind the choices that are made.

**Comment by Craig-Rodkin** [comment]
Hi,

The decision to include the year twice was made long before I was brought into the project. The paper and/or email trail is not available either as the decision was made decades ago.. 

Last year the ACM publications board took up a discussion brought forth by 2 SIGs to change the reference formats and the outcome was not to change the reference formats in any way.

**Comment by rionda** [comment]
Thanks for the reply. What was the reason for not changing, possibly even specifically about this replication of the year? 
Are minutes of these meetings available?

**Comment by Craig-Rodkin** [comment]
minutes are not available to the public. 

All I can say for now is that ACM will be taking a different approach to displaying references in the future.

**Comment by rionda** [comment]
Thus confirming, twice in a single reply, the complete lack of transparency in these decisions.

**Comment by rionda** [comment]
(Side note: I'm not "the public", I'm a member of ACM, but clearly not even members can know what ACM decides for them and why.)

**Comment by Craig-Rodkin** [comment]
I'm sorry, but board minutes are not publicly available, they never have been. 

The communications about future ACM Digital Library development are usually posted in the ACM Blue Diamond newsletter. Others are published in the Atypon Literatum update newsletters. Both publicly available.  Once we finalize implementation and schedule details, we will publish the details in Blue Diamond.

**Comment by rionda** [comment]
The past lack of transparency is not a justification for the current lack of transparency.

Developments usually are announced without *reasons* for the choices. Why do we have the year repeated twice? We will never know, but we are stuck with it. Or perhaps we aren't stuck with it because of future developments. Can we know? Not until it gets announced. Can we know why it will be changed and what is the reasoning behind the new format? Given the past, I bet not. Is there *any* phase of request for comments from the public/members? *Obviously* not. 

This is not good service to ACM members, authors, and the scientific community at large.
