### ISSUE TITLE
`authorversion` option seems to be broken in 1.78

### ISSUE THREAD

**Issue by delsner** [borisveytsman/acmart#434]
When adding the `authorversion` option in the most recent `acmart` version (1.78), I get the following error: 
```
pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pdfstartlink. \end{document}
```
This happened to me after upgrading from 1.77 so it seems to be a recent regression.
Do you have any advice on what I could change to fix this issue?
Thank you.

**Comment by borisveytsman** [comment]
Could you provide a minimal working example?
