### ISSUE TITLE
Does acmart have plans to support ror.org IDs?

### ISSUE THREAD

**Issue by kmccurley** [borisveytsman/acmart#442]
The purpose of ror.org is to assign persistent IDs to research institutions in the same way that ORCID IDs are assigned to individual researchers. They now have quote comprehensive coverage (at this count, 441,000 organizations including companies, universities, and institutes). Their data is openly available for download, and hopefully will provide a way to disambiguate strings like "University of California - Berkeley" or "UC Berkeley" or "Univ. of Calif., Berkeley".

When an author is declared for a paper in acmart, there is the capability to declare \affiliation with a string name, address, city, country, etc. I believe they should also be able to declare \ror{...} inside an affiliation to uniquely identify it. Do you have any plan to support something like this?

**Comment by borisveytsman** [comment]
This is a very interesting idea.  @craig-rodkin, are there any plans for this?

**Comment by Craig-Rodkin** [comment]
We are currently reviewing multiple organizer persistent organization ID solutions to use across all ACM interests. Once the decision is made, we will look to implement in the templates and other ACM systems.
