### ISSUE TITLE
Footnotes in minipages are inevitably centered

### ISSUE THREAD

**Issue by LinqLover** [borisveytsman/acmart#449]
MWE:

```tex
\documentclass{acmart}

\begin{document}
    \begin{table}[h!]
	\begin{minipage}{10cm}
		This is a test.\footnote{This is a footnote.}
  	\end{minipage}
    \end{table}
\end{document}
```

![image](https://user-images.githubusercontent.com/38782922/135697874-10effe0a-5052-4b13-b3fb-327cd1b6a2ee.png)

Without the acmart style, this example would look like this:

![image](https://user-images.githubusercontent.com/38782922/135697894-388e3386-5fae-42d1-a7e1-5f213f7db416.png)

I don't think this is intended behavior - but if it is, it should at least be changeable. There have been multiple reports of people trying to align their minipage footnotes in a conventional left-aligned manner:

- https://latex.org/forum/viewtopic.php?t=32967
- ~~https://latex.org/forum/viewtopic.php?t=19069~~
- https://tex.stackexchange.com/q/512129/221054
- And I am experiencing the same problem right now, too. :-)

Would it be possible to change this template so that footnotes in minipages are left-aligned? Or ideally, could you maybe provide a hacked but fast snippet to patch this in my own paper? Thanks in advance!

**Comment by borisveytsman** [comment]
This is the intended behavior since 2016.  The file says:  `
```
% \begin{macro}{\@mpfootnotetext}
% \changes{v1.13}{2016/06/06}{Made minipage footnotes centered}
%   We want the footnotes in minipages centered:
```

I think this behavior was requested by ACM designers.  I do not recommend you to change it in your own paper, but if you insist, here you are (again, I do not guarantee the conference committee or journal editor will like it):

```
\makeatletter
\long\def\@mpfootnotetext#1{%
  \global\setbox\@mpfootins\vbox{%
    \unvbox\@mpfootins
    \reset@font\footnotesize
    \hsize\columnwidth
    \@parboxrestore
    \protected@edef\@currentlabel
         {\csname p@mpfootnote\endcsname\@thefnmark}%
    \color@begingroup%\centering - commented out centering footnotes
      \@makefntext{%
        \rule\z@\footnotesep\ignorespaces#1\@finalstrut\strutbox}%
    \color@endgroup}}
\makeatother
```

**Comment by LinqLover** [comment]
Thank you very much for your answer!
