### ISSUE TITLE
bibliography - eprint field printed as "arxiv:" 

### ISSUE THREAD

**Issue by rionda** [borisveytsman/acmart#452]
It seems that the `eprint` field in a BibTeX `inproceedings` or `inbook` entry is printed as "arxiv:" followed by the content of the field. This seems a suboptimal default.

Specifying a `archiveprefix`  in the entry does not seem to have any effect.

SIAM, for example,  gives BibTeXs of some of its artcles with the above format. E.g., from https://epubs.siam.org/doi/10.1137/1.9781611972795.67 I got

```
@inbook{doi:10.1137/1.9781611972795.67,
	author = {Hanhij{\"a}rvi, Sami and Garriga, Gemma C. and Puolam{\"a}ki, Kai},
	booktitle = {Proceedings of the 2009 SIAM International Conference on Data Mining (SDM)},
	doi = {10.1137/1.9781611972795.67},
	eprint = {https://epubs.siam.org/doi/pdf/10.1137/1.9781611972795.67},
	pages = {780-791},
	title = {Randomization Techniques for Graphs},
	url = {https://epubs.siam.org/doi/abs/10.1137/1.9781611972795.67}}
```

**Comment by k4rtik** [comment]
I think in this example SIAM is just using the `eprint` field wrongly. It almost always refers to some sort of unique article identifier and almost never a URL. As a user, it makes sense to delete that field in your copy of the bibentry.

SIAM doesn't need to provide a URL field either as the DOI serves the same page. (For them, it may make sense to provide the value of eprint field in the URL field, if they want to provide direct links to PDFs.)

**Comment by borisveytsman** [comment]
I added recognition of eprintprefix to the code

**Comment by k4rtik** [comment]
Hi @borisveytsman, it seems with this change you lowercased the default  (if I am understanding the syntax correctly) prefix to "arxiv" vs the recommended 'arXiv'. Would it be possible to change that too?

**Comment by borisveytsman** [comment]
> Hi @borisveytsman, it seems with this change you lowercased the default (if I am understanding the syntax correctly) prefix to "arxiv" vs the recommended 'arXiv'. Would it be possible to change that too?

ok
