### ISSUE TITLE
Possible to turn off suppressing URL when DOI is also mentioned?

### ISSUE THREAD

**Issue by k4rtik** [borisveytsman/acmart#453]
There are often cases when the URL provides a little more information than the DOI, such as a project homepage or link to the GitHub repo relevant to a paper. The current style file disables printing URL if DOI is mentioned [since 2011](https://github.com/borisveytsman/acmart/blob/1704c8bf7eee92a1515ff755f5118b6a22bb1f8e/ACM-Reference-Format.bst#L736).

It will be nice to provide a toggle to disable this suppression.

**Comment by krono** [comment]
Note that specifically ACM bibtex entries contain virtually the same info in the URL as in the DOI. 
Therefore disabling this makes sense.

what would a toogle look like?

**Comment by k4rtik** [comment]
I agree, indeed they do (I personally think it's redundant with most modern bib styles).

A toggle would perhaps be an option that can be passed to acmart class, such as `overrideURLwDOI` which will have true by default. Having the choice to disable it will allow those of us who carefully curate our bibentries to show URL along with DOI.

**Comment by borisveytsman** [comment]
I think it is better to set up toggle on the level of bib entries.  Perhaps you want to print URL only for some entries, where you want to show non-canonical link too (maybe a preprint version).

Added this option

**Comment by k4rtik** [comment]
Thanks @borisveytsman

I like this solution. I wish there was also a separator such as a label (smallcapped "URL:") between a DOI and a distinct URL, for example, here:

<img width="595" alt="Screen Shot 2021-11-28 at 9 54 25 AM" src="https://user-images.githubusercontent.com/374340/143775589-16858e91-8953-4541-9193-bfccd0d21718.png">

This issue exists for listing of both arXiv and URL before this change:

<img width="594" alt="Screen Shot 2021-11-28 at 9 52 40 AM" src="https://user-images.githubusercontent.com/374340/143775542-008bd35b-5491-4970-ae35-ef70a9981098.png">

I understand the ACM guidelines may not allow an extra label before the URL, so I am content with this change.
