### ISSUE TITLE
Adding Creative Commons Licenses

### ISSUE THREAD

**Issue by sven-mayer** [borisveytsman/acmart#457]
While authors can pay for a lisense such as  CC BY-SA, this license will only be added later in the process using TAPS. However, when not going through TAPS currently there is no easy way to add a license like ccbysa. Other license types, however, such as ic2w3www are available.  

Thus, could we include CC BY, CC BY-SA, and CC BY-SA-NC (all three are also supported by ACM to be paid for).

**Comment by sven-mayer** [comment]
Unfortunately, there are legal issues ACM can not offer adding Creative Commons Licenses to their template. Thus, I will report to forking this repo and add it myself.

**Comment by borisveytsman** [comment]
ACM decided to allow CC licensing, so I can implement it now

**Comment by samth** [comment]
Hooray!

**Comment by rionda** [comment]
I cannot believe this has happened. Hooray indeed!

**Comment by haukesand** [comment]
Great, cc licenses work! 
Is there a way to disable the error message? I want to submit to arXiv and still use the \acmConference to show that a paper was submitted as a workshop paper. 
acmengage still throws an error and nonacm disables this.

Or vice versa is there a way to use nonacm and print the acm conference?

**Comment by oaken-source** [comment]
> Great, cc licenses work! Is there a way to disable the error message? I want to submit to arXiv and still use the \acmConference to show that a paper was submitted as a workshop paper. acmengage still throws an error and nonacm disables this.
> 
> Or vice versa is there a way to use nonacm and print the acm conference?

did you ever find out how to do this?

**Comment by mhenze** [comment]
> > Great, cc licenses work! Is there a way to disable the error message? I want to submit to arXiv and still use the \acmConference to show that a paper was submitted as a workshop paper. acmengage still throws an error and nonacm disables this.
> > Or vice versa is there a way to use nonacm and print the acm conference?
> 
> did you ever find out how to do this?

This is very likely not the intended way, but nevertheless

```
\makeatletter
\def\@ACM@copyright@check@cc{}
\makeatother
\setcopyright{cc}
```
