### ISSUE TITLE
Missing Author and Keywords metadata in produced PDF file

### ISSUE THREAD

**Issue by huwan** [borisveytsman/acmart#464]
When using sample-sigconf.tex with the latest (v1.83) acmart LaTeX template and TexLive 2021, the author and keywords metadata of the produced PDF file are missing, as shown in the attached figure. I also tried to compile with old versions of acmart (e.g., v1.77) and TeXLive 2020, but still got the same results. I also checked the provided sample pdfs in the acmart-primary.zip downloaded from [ACM website](https://www.acm.org/publications/proceedings-template), these metadata fields are missing, too.

![missing-metadata-fields](https://user-images.githubusercontent.com/1451009/161536704-3f55be41-ff65-463d-96d1-a4aa75423099.png)

**Comment by borisveytsman** [comment]
Seems to work in the current version

**Comment by shhyou** [comment]
I'm could not find the author metadata in the PDF, but I'm not sure what might have went wrong in the process. I downloaded v2.12, use `make` to generate `acmart.cls`, and then run `pdflatex sample-sigplan.pdf`. Here is the output of `pdfinfo`:

```
$ pdfinfo sample-sigplan.pdf
Title:           The Name of the Title Is Hope
Subject:         -  Do Not Use This Code  ->  Generate the Correct Terms for Your Paper.Generate the Correct Terms for Your Paper.Generate the Correct Terms for Your Paper.Generate the Correct Terms for Your Paper.
Creator:         LaTeX with acmart 2024/12/28 v2.12 Typesetting articles for the Association for Computing Machinery and hyperref 2024-01-20 v7.01h Hypertext links for LaTeX
Producer:        pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) kpathsea version 6.4.0
CreationDate:    Fri Feb 14 14:12:00 2025 CST
ModDate:         Fri Feb 14 14:12:00 2025 CST
Custom Metadata: yes
Metadata Stream: yes
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           7
Encrypted:       no
Page size:       612 x 792 pts (letter)
Page rot:        0
File size:       1056333 bytes
Optimized:       no
PDF version:     1.5
```
How can I add the author metadata to the PDF?
