### ISSUE TITLE
Bibtex to bbl issues 1.83

### ISSUE THREAD

**Issue by mew2057** [borisveytsman/acmart#465]
I just updated my acmart.cls to `1.83`, and my bibtex entries are broken when converted to `.bbl`. I was previously on`1.80` and the following entry was interpreted fine:

```
@misc{geocaching_2022,
	title = {Geocaching - {The} {Official} {Global} {GPS} {Cache} {Hunt} {Site}},
	url = {http://www.geocaching.com/},
	abstract = {There are millions of geocaches worldwide, just waiting for you to find them. There are probably even some within walking distance of where you are right now. Visit Geocaching.com to see just how many geocaches are nearby and to learn how to start finding them.},
	language = {en},
	urldate = {2022-02-08},
	journal = {Geocaching},
	author = {Geocaching},
}
```

However, now when I use the same entry in `1.83` I get the following error in Overleaf:

![image](https://user-images.githubusercontent.com/1195452/162525204-f73cfe93-5cc1-440b-b634-27263963ae89.png)

This is not the only entry that does this and it generally appears to fail on the `_` character in my bibtex entries. Any thoughts?

**Comment by borisveytsman** [comment]
In the absence of year `acmart` tries to construct the label from the key, and fails.  Adding `year=2022` to the bib entry solves the problem.
