### ISSUE TITLE
manuscript doesnt allow authorversion

### ISSUE THREAD

**Issue by cmacdonald** [borisveytsman/acmart#468]
If we are in manuscript mode, then authorversion has no impact. Why is this?

```tex
    \if@ACM@manuscript
      Manuscript submitted to ACM\\
    \else
      \if@ACM@authorversion
```

**Comment by Rajjat** [comment]
Hi, Did you able to resolve this issue?

**Comment by borisveytsman** [comment]
This is intentional.  Manuscript is something you submit to ACM.  Author version is something you send to your colleagues, but are not submitting to ACM
