### ISSUE TITLE
Q: Whare to find Microsoft Word templates?

### ISSUE THREAD

**Issue by yilabs** [borisveytsman/acmart#469]
Hi,

I come here by following the link from:

https://2022.splashcon.org/track/splash-2022-oopsla

The PACMPL templates used for SPLASH (Microsoft Word and LaTeX) can be found at the [SIGPLAN author information page](http://www.sigplan.org/Resources/Author/).

but I cannot find the Microsoft Word templates, can we also host the Word templates here?

Thanks.

**Comment by smokhov** [comment]
FWIW, a question like this is answered here: https://www.acm.org/publications/proceedings-template
