### ISSUE TITLE
ACM in-text citation style

### ISSUE THREAD

**Issue by michaeldorner** [borisveytsman/acmart#471]
According to the [ACM guidelines on citation style][1]:

> When a citation is part of a sentence, the name of the author is NOT enclosed in brackets, but the year is: "So we see that Burando et al. [1999]..."

However, `\citet{author2022}` creates `Author et al. [1]` instead of `Author et al. [2022`]. Am I misunderstanding or using `\citet` wrong?

  [1]: https://www.acm.org/publications/authors/reference-formatting

**Comment by rionda** [comment]
I wonder whether the guidelines are wrong, and they should mention the number of the reference, not the year. 
@Craig-Rodkin should know.

Personally, I would find a style that mixes citation numbers and years within square brackets to be very confusing. E.g., what if I cite a Roman work from 14 A.D. but I cite more than 14 works in my paper...seeing [14] would be a bit confusing, no?
Or, less realistically, what about a paper which cites more than 1900 works but then cites a work from the 1800s: what work does [18xx] refer to?

If the style in the guidelines is really what one should follow, the BibTeX style file(s?) should be updated so using `\citet` achieves the above (and I'm not entirely sure it is easy). But really, this style would be very weird, ugly, and confusing.

**Comment by michaeldorner** [comment]
Oh I totally agree that the „new“ reference style is very confusing. :-) It is just that the referenced website says different.

**Comment by rionda** [comment]
@borisveytsman why was this issue marked as completed?

**Comment by addisoncrump** [comment]
I have to believe that the citation guide has a typo. There's no way that the year is intended IMO; maybe this is conflicting because of SIGGRAPH-style citations?
