### ISSUE TITLE
Incompatible with `inputenc` using `utf8x`

### ISSUE THREAD

**Issue by L-TChen** [borisveytsman/acmart#473]
The following tex
```
\documentclass{acmart}
\usepackage[utf8x]{inputenc}
\begin{document}
\end{document}
```
triggers the following error
```
(/usr/local/texlive/2022basic/texmf-dist/tex/latex/libertine/T1LinuxLibertineT-
TLF.fd)) (/usr/local/texlive/2022basic/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2022basic/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2022basic/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2022basic/texmf-dist/tex/latex/ucs/data/uni-global.def))
! Argument of � has an extra }.
<inserted text>
                \par
l.3 \begin{document}

?
```
under Tex Live 2022 (pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)). Loading `ucs` alone is fine, though.

It worked fine at least in March when we submitted a manuscript; after a recent update (which I cannot recall) of Tex Live it broke. 

The option `utf8x` is required by `lhs2Tex`, a program transforming code to tex file, when processing a language called Agda. The usage of Agda is apparently popular in some ACM conferences like ICFP and POPL. 

Can you spot the bug and try to fix it?

**Comment by u-fischer** [comment]
It is not a bug of the class but was an incompability between the ucs package and hyperref. It has been resolved and the example no longer errors but be aware that as mentioned in the log it has been basically disabled, so you could also simply delete the line:

~~~~
Package ucs Info: utf8x disabled, assuming standard utf8 processing
(ucs)             load ucs package to force utf8x processing.
~~~~

**Comment by L-TChen** [comment]
Right, I see the ticket https://github.com/latex3/latex2e/issues/833. I will see what can be done with `lhs2TeX`.
