### ISSUE TITLE
Line numbering and searching PDFs

### ISSUE THREAD

**Issue by henningpohl** [borisveytsman/acmart#477]
I'm opening this issue to start a discussion around whether the red line numbering in review versions should be searchable or not. Right now they are and that has been annoying me a few times. This is primarily an issue when trying to find places where a given reference has been used. If I search for paper 11, for example, my PDF viewer will also return all line numbers ending in 11. Not ideal. But on the other hand, I get that sometimes people might want to have the line numbers searchable as well when reviewing. So there likely isn't an ideal solution here. 

If line numbers should be visible, but not searchable, an easy way to do that would be via the [accsupp](https://www.ctan.org/pkg/accsupp) package. Instead of:
`\loop{\color{red}\scriptsize\the\ACM@linecount}\\` ([L7445](https://github.com/borisveytsman/acmart/blob/bd9b46415f1b35738b69472acf3904bdeb9d6569/acmart.dtx#L7445))
this would then be:
`\loop{\BeginAccSupp{method=escape,ActualText=}\color{red}\scriptsize\the\ACM@linecount\EndAccSupp{}}\\`

**Comment by bennn** [comment]
hyperref's backref option is my favorite way to find references. I wish it was on by default.
(For now, I always make a file `hyperref.cfg` with one line inside: `\hypersetup{backref}`.)

**Comment by ulysses4ever** [comment]
@bennn cool workaround! Unfortunately, doesn't apply if I deal with someone else's PDF, which I do most of the time. Having this option on by default does sound reasonable but even then I'd expect making lines number non-searchable would improve quality of live (once in a while I do search for specific numbers).
