### ISSUE TITLE
acmsmall on an A4 page

### ISSUE THREAD

**Issue by jose** [borisveytsman/acmart#478]
Hi,

Quick question, why is `a4paper` ignored when I set it as `\documentclass[acmsmall,a4paper]{acmart}`?

```
LaTeX Warning: Unused global option(s):
    [a4paper].
```

Would it be correct to achieve that with the following?
```
\documentclass[acmsmall]{acmart}
\geometry{paperwidth=8.3in, paperheight=11.7in}
```

--
Best,
Jose

**Comment by borisveytsman** [comment]
ACM does not print papers on a4paper, so this option is ignored
