### ISSUE TITLE
acmsmall's margins

### ISSUE THREAD

**Issue by jose** [borisveytsman/acmart#479]
Hi,

What's the proper way to set acmsmall's margins size?  I've tried the following
```
\documentclass[acmsmall]{acmart}
\geometry{margin=1in}
```
which seems to correctly set left and right-margin to 1in, but top and bottom-margin remain larger than 1in.  Any help would be appreciated.

--
Best,
Jose

**Comment by stephennspencer** [comment]
The "acmart" template sets the margins - one should not have to set the margins 'manually.'
