### ISSUE TITLE
`\grantsponsor` causes text overlap

### ISSUE THREAD

**Issue by Iiridayn** [borisveytsman/acmart#482]
`\grantsponsor` appears to delete the next two characters following it.

MWE:

```
\documentclass[sigconf]{acmart}
\begin{document}
\begin{acks}
We thank \grantsponsor{mwe1}{sponsor} for money.

We thank \grantsponsor{mwe2}{sponsor} for money.

We thank \grantsponsor{mwe3}{sponsor}~~~for money.

We thank sponsor for money.
\end{acks}
\end{document}
```

You'll note the first two eat 2 characters, while the 3rd eats two spaces and appears fine. The last is what it looks like before using the `\grantsponsor` command. Also has the same issue in manuscript mode, haven't tested others.

**Comment by borisveytsman** [comment]
The command `\grantsponsor` has THREE mandatory arguments, the third being the url.  If URL is absent, use just `{}`

`
We thank \grantsponsor{mwe1}{sponsor}{https://sponsor.com} for money.

We thank \grantsponsor{mwe1}{sponsor}{} for money.
`
