### ISSUE TITLE
\tag causes warning about duplicate labels

### ISSUE THREAD

**Issue by tamstorf** [borisveytsman/acmart#483]
When compiling with pdflatex, the following example cause a pdfTeX warning : 

\documentclass{acmart}

\begin{document}
\begin{equation}
x \tag{foo}
\end{equation}
\begin{equation}
y \tag{bar}
\end{equation}
\end{document}

In particular it says 

pdfTeX warning (ext4): destination with the same identifier (name{equation.0.1}
) has been already used, duplicate ignored
<argument> ...shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...
l.12 \end{document}
                   ] (./foo.aux) )

By comparison, if I change the documentclass to article and add the amsmath package (in order to get the \tag command), then it compiles without any warning. 

\documentclass{article}
\usepackage{amsmath}

\begin{document}
\begin{equation}
x \tag{foo}
\end{equation}
\begin{equation}
y \tag{bar}
\end{equation}
\end{document}

**Comment by borisveytsman** [comment]
This warning can be safely ignored
