### ISSUE TITLE
Force a certain number of authors per row in acmart

### ISSUE THREAD

**Issue by Malloc26** [borisveytsman/acmart#488]
Is there a way to force  a certain number of authors per row in acmart? I am aware there is this command: `\settopmatter{authorsperrow=4}`; however, I would like to force the first row to only contain 2 authors, then the rest to contain 3. 

For example, I currently have this:
![image](https://user-images.githubusercontent.com/18623808/222290207-dcd56aca-8e17-4a62-a4bc-071d3a086509.png)

And when I add a "blank" author to force the first line to two authors, I get:
![image](https://user-images.githubusercontent.com/18623808/222290333-6bc4dbbd-58e0-4934-905e-8d4b4218fb3e.png)

Is there a way to better center that first row? Or to just force two authors into that first line?

**Comment by borisveytsman** [comment]
This would be against the design of ACM front page
