### ISSUE TITLE
bug in "acks" environment?

### ISSUE THREAD

**Issue by stephennspencer** [borisveytsman/acmart#492]
An author provided me with this issue: putting the comment character - % - after either \begin{acks} or \end{acks} will cause the file not to build. 

Minimum example:

\documentclass[sigconf]{acmart}

\begin{document}

\title{An Example.}

\author{John Mayer}
\affiliation{
 \institution{Dead and Company}
 \country{USA}}
\email{johnmayer@gmail.com}

\maketitle

\section{Introduction}

Lorem ipsum.

\begin{acks} %
%\section*{Acknowledgements}
The acknowledgment section starts... now.
\end{acks} %

\end{document}

**Comment by borisveytsman** [comment]
This is due to the fact that we want to exclude acks in anonymous mode.  So `acks` is a very special environment.  

I need to update the docs to reflect this.
