### ISSUE TITLE
Please add support for `tikz` package

### ISSUE THREAD

**Issue by LinqLover** [borisveytsman/acmart#499]
I think tikz is used really commonly. The current workaround is to manually convert our tikz figures into separate PDFs first, but it would be great if this step would not be necessary.

**Comment by smokhov** [comment]
There are related issues to tikz that cropped up before: #437 and #436 that may or may not be of help.

**Comment by borisveytsman** [comment]
TikZ by itself is supported by the class, for example,

```
\documentclass[sigconf]{amsart}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \draw[-latex](0,0) -- (1,1) -- (1,2);
\end{tikzpicture}
\end{document}
```

However, whether the current processing company can work with TikZ, is a separate question.  I would recommend to save the images as pdf and include them in the resuly
