### ISSUE TITLE
Warnings from Fancyhdr

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#5]
It can be confusing to users if the default behavior includes warnings, especially ones that suggest that their document will be rendered with inconsistent layout.

```
Package Fancyhdr Warning: \headheight is too small (8.0pt): 
 Make it at least 11.0pt.
 We now make it that large for the rest of the document.
 This may cause the page layout to be inconsistent, however.
```

**Comment by MatthewFluet** [comment]
Indeed, it seems that the footer line is shifted down starting on the second page.

**Comment by borisveytsman** [comment]
Thanks.  Corrected.

**Comment by rionda** [comment]
@borisveytsman : I don't think 12pt=1pc is enough. I'm now getting 
```
Package Fancyhdr Warning: \headheight is too small (12.0pt): 
 Make it at least 12.93494pt.
 We now make it that large for the rest of the document.
 This may cause the page layout to be inconsistent, however.
```
just because I have an "E" with a grave accent in my title. I'm using "acmsmall,review" as the package option.

I wonder whether the default should be the height of the "tallest" character (including accent).

(btw, the commit that solved this issue was 62e439b49bb698c18e0a79dee439ba9edbc11fe2)

**Comment by borisveytsman** [comment]
I wonder whether to make it uniform 13pt?

**Comment by rionda** [comment]
Maybe. That would solve it for me. The problem most likely only exist for accented capital letters, which should be rare.

**Comment by MatthewFluet** [comment]
A problem with a uniform 13pt height, I would think, is that using `11pt` or `12pt` class options would likely result in an overfull header.  (And larger body text fonts are something that is becoming more attractive with electronic only proceedings/journals, where page limits are needed to keep down publication costs.)

**Comment by borisveytsman** [comment]
I am worried about math in titles.  It can include sums or integrals (hope nobody uses fractions in titiles...)
