### ISSUE TITLE
Uninitialized journal metadata

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#50]
When `\@acmMonth` or `\@acmArticleSeq` are uninitialized by a document using
a journal format (e.g., `acmsmall`), typesetting stops with an uninformative:
```
  ! Missing number, treated as zero.
```

This might happen when an author transitions a conference paper to a
journal submission.

**Comment by MatthewFluet** [comment]
I guess I was wrong with my initial issue description; there is still an uninformative:
```
! Missing number, treated as zero.
```
when `\@acmArticle` is uninitialized (i.e., when `\acmArticle` is not used in the document).

**Comment by borisveytsman** [comment]
Ok, changed other defaults.  Should work now (hopefully)
