### ISSUE TITLE
`\grantsponsor` example suggests global SponsorID while it is just a user-chosen ID

### ISSUE THREAD

**Issue by andreasabel** [borisveytsman/acmart#500]
From the example given for `\grantsponsor` I got the impression that I have to hunt for a global ID for my grant provider:
https://github.com/borisveytsman/acmart/blob/9e0908c679723dfbfd911de6b8a1ed0b28d123b5/acmart.dtx#L1626-L1633
However it has been clarified in the fix of #71 that this is just an ID the user can choose themselves:
https://github.com/borisveytsman/acmart/blob/9e0908c679723dfbfd911de6b8a1ed0b28d123b5/acmart.dtx#L1615-L1618
It would be clearer (esp. to the sloppy reader) if the example was updated to use a ID that _looks_ user-chosen (like `my-sponsor`).  It currently looks global (`GS501100001809`).

Re:
- #71

**Comment by andreasabel** [comment]
Thanks!

**Comment by vesalvojdani** [comment]
This fix updated the grant sponsor ID, but the next grantnums still refer to the old value (`\grantnum{GS501100001809}{61273304}`). These should match, right? Also, the "my-grant" prefix seems to imply one has to add the grant IDs here, but if I understand correctly, it's the other way around, so why not use "my-sponsor-GS501100001809" as suggested (or simply "my-sponsor-nsfc")?
