### ISSUE TITLE
Different behavior of \setlength in preamble in acmart documentclass

### ISSUE THREAD

**Issue by sfzhu93** [borisveytsman/acmart#501]
```latex
\documentclass[acmsmall,review,anonymous,screen]{acmart}
% \documentclass{article}

\newlength{\myproofrightwidth}
\setlength{\myproofrightwidth}{0.3\linewidth} % line 1

\newcommand\rightside[1]
{\penalty-1 \mbox{~}\hfill%
 \begin{minipage}[t]{\myproofrightwidth}%
    by #1%
 \end{minipage}}

\begin{document}

\setlength{\myproofrightwidth}{0.3\linewidth} % line 2: necessary for acmart
left text \rightside{\the\linewidth}

\end{document}
```
In this code snippet, setting `\myproofrightwidth` in preamble has a different behavior from other document classes, such as `article` or `ieeetran`. If line 2 is commented out, the right side prints 0.0pt. However, this behavior is different from `article`. In `article`, the right side correctly prints the line width as a non-zero value. In `acmart`, you have to set up the length again at the beginning of the document to behave the same as in other document classes.

overleaf document for the above code snippet: https://www.overleaf.com/read/ybmyxnydwjff

This bug makes some of the packages to behave differently, e.g., using the \BY command in [pfsteps](https://users.cs.northwestern.edu/~jesse/code/latex/pfsteps/pfsteps.pdf). The snippet also comes from a use case of `pfsteps`.

**Comment by borisveytsman** [comment]
I am not sure this is a bug.  `amsart` has the same behavior -- actually `acmart` inherits this behavior from `amsart`.  A class may, if it chooses, redefine `\linewidth` at the beginning of document, especially if the authors tend to abuse preamble.
