### ISSUE TITLE
\vspace warning with glossaries

### ISSUE THREAD

**Issue by edwintorok** [borisveytsman/acmart#502]
If I have more than one glossary entry then I get a vspace warning from acmart.
Minimal example:
```
\documentclass{acmart}
\usepackage{glossaries}
\newacronym{AST}{AST}{Abstract Syntax Tree}
\newacronym{GC}{GC}{Garbage Collector}
\makeglossaries
\begin{document}
\gls{AST}
\gls{GC}
\printglossaries
\end{document}
```

Then run `pdflatex mwe && makeglossaries -c -d . mwe && pdflatex mwe` and it prints (the more glossary entries you have the more warnings it will print):
```

Class acmart Warning: \vspace should only be used to provide space above/below
surrounding objects on input line 5.
```

Relevant versions: `acmart 2023/03/30 v1.90`, `glossaries 2022/11/03 v4.52 (NLCT)`, Fedora 38 with TexLive 2022.

The generated mwe.gls looks like this, I don't see a `\vspace` there unless it is implicit in the expansion of these commands:
```
\glossarysection[\glossarytoctitle]{\glossarytitle}\glossarypreamble
\begin{theglossary}\glossaryheader
\glsgroupheading{A}\relax \glsresetentrylist %
\glossentry{AST}{\glossaryentrynumbers{\relax
		\setentrycounter[]{page}\glsnumberformat{1}}}\glsgroupskip
\glsgroupheading{G}\relax \glsresetentrylist %
\glossentry{GC}{\glossaryentrynumbers{\relax
		\setentrycounter[]{page}\glsnumberformat{1}}}%
\end{theglossary}\glossarypostamble
```

**Comment by borisveytsman** [comment]
Package `glossary` defines vertical space between glossary groups, which may clash with ACM visual design
