### ISSUE TITLE
Feature request: better support for author CC version

### ISSUE THREAD

**Issue by PeterSewell** [borisveytsman/acmart#515]
For a camera-ready accepted open access paper, the authors chose some CC licence.  The ACM version (for whatever reason) has the rightsretained text without that licence.  That leaves the authors to typeset a version with the CC licence for their own use, for which `acmart` currently suggests using `nonacm`, `cc`, and `\setcctype`.  However, that (a) removes the footer with the journal volume etc, (b) removes the ACM Reference Format, and (c) still includes the `\@acmArticle\if@ACM@printfolios:` in the page numbers.  The first two aspects of `nonacm` are appropriate for pre-acceptance preprints, but for the author CC final version it would be useful to have an `acmauthorversion` option that got all those right.   (In my case this was for acmsmall, for PACM PL/POPL).

**Comment by PeterSewell** [comment]
This is still a problem in v2.08

**Comment by PeterSewell** [comment]
Moreover, it's important that the CC version end up with the same pagination as the ACM version, otherwise confusion will ensue.  Really, the ACM version should just include the CC license statement, and then (a) it would be clear to all readers, and (b) there would be no need for this time-wasting faffing about.

**Comment by borisveytsman** [comment]
This is now supported by ACM
