### ISSUE TITLE
Bug: \acmArticleSeq{} does not show Article Number in the black folio after upgrading to version 2.00

### ISSUE THREAD

**Issue by M-Colley** [borisveytsman/acmart#516]
Hello there, after upgrading to version 2.00, the template "acmlarge" does not show the black folio (black rectangle with article number on the right side) anymore. 

Here are the settings used:

```
\setcopyright{rightsretained}
\acmJournal{IMWUT}
\acmYear{2022} \acmVolume{X} \acmNumber{X} \acmArticle{49} \acmMonth{6}\acmDOI{XX/XXX}

% for positioning the acm article number
\acmArticleSeq{5}

```

I believe this was deleted here: 

https://github.com/borisveytsman/acmart/commit/fbf3b35465a48c0803447a32c2b15b1f0c002a98

"folioblob"

**Comment by dbeyer** [comment]
@M-Colley I believe this was a design decision by ACM and this behavior is desired.

**Comment by borisveytsman** [comment]
Yes, this is intentional
