### ISSUE TITLE
Generated ACM Reference format does not match ACM DL (for conference proceedings papers)

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#52]
For a recent paper of mine (http://dl.acm.org/citation.cfm?doid=2746325.2746327), the ACM Reference format given by the ACM DL (see "Export Formats:" in sidebar of above page) is:

> Connor Adsit and Matthew Fluet. 2014. An Efficient Type- and Control-Flow Analysis for System F. In *Proceedings of the 26nd 2014 International Symposium on Implementation and Application of Functional Languages* (IFL '14), Sam Tobin-Hochstadt (Ed.). ACM, New York, NY, USA, , Article 3 , 14 pages. DOI=http://dx.doi.org/10.1145/2746325.2746327

When printing the bib entry for this paper (see "Export Formats:" in sidebar of above page) using `ACM-Reference-Format-Journals.bst`, the displayed format is:

> Connor Adsit and Matthew Fluet. 2014. An Effcient Type- and Control-Flow Analysis for System F. In *Proceedings of the 26nd 2014 International Symposium on Implementation and Application of Functional Languages (IFL ’14)*. ACM, New York, NY, USA, Article 3, 14 pages. DOI:http://dx.doi.org/10.1145/2746325.2746327

However, when I recreate the paper using `acmart.cls`, the displayed ACM Reference format is:

> Connor Adsit and Matthew Fluet. 2014. An Efficient Type- and Control-Flow Analysis for System F. *IFL’14, Boston, MA, USA, October 01–03, 2014*.
> DOI: http://dx.doi.org/10.1145/2746325.2746327

Although full article number and page number information may not be available at the time of camera-ready submission, a reference format should at least encourage the use of "In Proceedings of <full conference name>".

**Comment by borisveytsman** [comment]
Fixed
