### ISSUE TITLE
ACM Template cannot use acknowledgements (acks)

### ISSUE THREAD

**Issue by LouHerGetUp** [borisveytsman/acmart#532]
In the ACM Journals Primary Article Template, I added the following code before the reference, 
```
\begin{acks}
To Robert, for the bagels and explaining CMYK and color spaces.
\end{acks}
```
however, the content in the Acknowledgments is not displayed and no errors are reported.  I am very confused! This issue is very important to me, thanks for your help!

**Comment by stephennspencer** [comment]
Can you please provide a minimal example that would build and show this behavior?

**Comment by krono** [comment]
Have you double blind  mode activiated? that would not show acks, if I remember correctly…

**Comment by LouHerGetUp** [comment]
> Have you double blind mode activiated? that would not show acks, if I remember correctly…

Yes, you're right! Thank you very much. You've helped me a lot!

**Comment by LouHerGetUp** [comment]
> Can you please provide a minimal example that would build and show this behavior?

Thank you for your help! My problem has been solved!
