### ISSUE TITLE
Paragraph are interpreted as subsubsections in Table of Contents (TOC), even though they should not be.

### ISSUE THREAD

**Issue by shamefulCake1** [borisveytsman/acmart#534]
MWE:

Standard LaTeX "article":
```
\documentclass{article}
\setcounter{tocdepth}{3}
%\setcounter{secnumdepth}{4}
\begin{document}
\tableofcontents

\section{section}
\subsection{subsection}
\subsubsection{subsubsection}
\paragraph{paragraph}
Hello, World!
\end{document}
```

Result:
![image](https://github.com/borisveytsman/acmart/assets/154489130/0a3e89c0-9485-4438-9331-c90eafe6fc6f)

This is what is expected.

I can  enumerate paragraphs if I want:

```
\documentclass{article}
\setcounter{tocdepth}{3}
\setcounter{secnumdepth}{4}
\begin{document}
\tableofcontents

\section{section}
\subsection{subsection}
\subsubsection{subsubsection}
\paragraph{paragraph}
Hello, World!
\end{document}
```

![image](https://github.com/borisveytsman/acmart/assets/154489130/3175270a-4f4a-4664-9a1c-00ee7f503598)

Again, this is expected, sometimes I want to enumerate paragraphs.

Acmart:

```
\documentclass[format=acmsmall]{acmart}
%\documentclass{article}
\setcounter{tocdepth}{3}
%\setcounter{secnumdepth}{4}
\begin{document}
\tableofcontents

\section{section}
\subsection{subsection}
\subsubsection{subsubsection}
\paragraph{paragraph}
Hello, World!
\end{document}
```

Result:

![image](https://github.com/borisveytsman/acmart/assets/154489130/0a957fd7-7e3f-411c-8920-fbc7f4e32396)

This is wrong, /paragraph/ should not be in the TOC, because `tocdepth` is set to 3. But maybe in `acmart` paragraphs are level-3 too, just as subsubsections?

With deeper secnumdepth:

```
\documentclass[format=acmsmall]{acmart}
%\documentclass{article}
\setcounter{tocdepth}{3}
\setcounter{secnumdepth}{4}
\begin{document}
\tableofcontents

\section{section}
\subsection{subsection}
\subsubsection{subsubsection}
\paragraph{paragraph}
Hello, World!
\end{document}
```

This compiles with errors.
It does add numbers to paragraphs (as expected), so it does recognise paragraphs as level-4 headings, not level-3, and nevertheless adds them to ToC, even though `tocdepth` is 3.

There is the resulting pdf, but again, it compiled with errors, so is probably not usable beyond an MWE:

![image](https://github.com/borisveytsman/acmart/assets/154489130/1b2dee5d-fad8-4b74-b8f1-22eced3c5d9e)

**Comment by borisveytsman** [comment]
Fixed recently
