### ISSUE TITLE
How to get rid of mirror margins (ie. dissimilar margins between odd and even pages)

### ISSUE THREAD

**Issue by ulyngs** [borisveytsman/acmart#537]
The following produces PDF output with 'mirror margins', i.e. dissimilar margins between even and odd pages, which is suitable only for double-sided physical printing where it makes room for binding holes:

`\documentclass[manuscript]{acmart}`

**Expected behaviour**: setting the 'screen' option should produce a PDF where margins are identical on even and odd pages.

**Actual behaviour**: Setting the 'screen' option doesn't change margin settings; the PDF still has dissimilar margins between even and odd pages:

`\documentclass[manuscript, screen]{acmart}`

<img width="874" alt="image" src="https://github.com/user-attachments/assets/5039e931-11ab-4d7c-a2ee-5b130e4a60e0">

<br>

**Comment by borisveytsman** [comment]
Right now ACM prefers twoside formatting.  Putting `\PassOptionsToPackage{twoside=false}{geometry}` before `\documentclass` suppresses this behavior.
