### ISSUE TITLE
Package hyperxmp Error: hyperref must be loaded before hyperxmp.

### ISSUE THREAD

**Issue by jjang3** [borisveytsman/acmart#541]
Hello, `acmart.cls` included in the [ASPLOS 2025 conference](https://www.asplos-conference.org/asplos2025/cfp/) ([Here is the download link](https://www.asplos-conference.org/wp-content/uploads/2024/01/asplos25-templates.zip)) results in the error following:
```
! Package hyperxmp Error: hyperref must be loaded before hyperxmp.

See the hyperxmp package documentation for explanation.
Type  H <return>  for immediate help.
```

Steps to reproduce:
1. `wget https://www.asplos-conference.org/wp-content/uploads/2024/01/asplos25-templates.zip`
2. `unzip asplos25-templates.zip`
3. `cd asplos25-templates && make`

`acmart.cls` included in the template seems to be version 1.90a.

If I remove the included `acmart.cls` from the zip file, `make` works as expected.

Thank you in advance; Please let me know if you need any additional information.

**Comment by borisveytsman** [comment]
The current version of acmart is 2.09;  when I put the current acmart.cls in the directory, everything comiles.  

I wrote to the organizers


> I am the maintainer of the acmart class.  Unfortunately, the version
> of acmart.cls included in
> https://www.asplos-conference.org/wp-content/uploads/2024/01/asplos25-templates.zip
> is obsolete.  This leads to problems, see, for examle,
> https://github.com/borisveytsman/acmart/issues/541
> 
> Please put there a new version from
> https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip
