### ISSUE TITLE
Todo notes raises vspace warnings

### ISSUE THREAD

**Issue by debarshi-ch** [borisveytsman/acmart#543]
When using the package 'Todo', it raises vspace warnings even with required margin lengths set as `\setlength{\marginparwidth}{2cm}`.

For example:

> Class acmart Warning: \vspace should only be used to provide space above/below surrounding objects on input line 37.

**Comment by borisveytsman** [comment]
You probably do not want todo notes in the final version.  The warnings in the draft may be safely igonored
