### ISSUE TITLE
Paper title in headers for proceedings papers

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#55]
Commit b2b1091 / v1.13 integrated some formatting changes requested by ACM; among them were additional information in headers.  Currently, the headers for proceedings have conference info and authors for both even and odd pages.  In particular, the headers never include the paper title.  AFAIK, prior proceedings formats have not had headers with this information.  If headers are being added, then it seems useful to include the paper title somewhere (on odd pages seems consistent with the journal formats).  Certainly when reviewing a stack of anonymized submissions, the "Anon." author information in the header provides no identifying information and when flipping through a printed proceedings, I think that paper title would be more helpful.

Depending on the requirements from ACM, I would think that paper title and authors in the header and conference info in the footer would provide all of the information on each page, though I think that the conference info is extraneous in most contexts.

**Comment by borisveytsman** [comment]
I am fine with this suggestion, but did you ask ACM editors?

**Comment by MatthewFluet** [comment]
No; the commit did not identify whom at ACM originated the request.
