### ISSUE TITLE
List formatting

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#56]
Commit aef0057 reduced left margins for lists.  The original margins may have been a little large, but the new margins seem too small.  In particular, when a list begins after the first line of an indented paragraph, then the list labels hang to the left of the preceding text; this looks bad (to me).

Another aspect inherited from `amsart` is that the left margin and label width are adjusted according to the width of the largest label in an `enumerate`, but used by both `itemize` and `enumerate`.  The third-level, which uses lower-case roman numerals in `enumerate` gets very large spacing.  Again it looks bad (to me) that nested `itemize` environments do not get equal increases in left margin/label width when the labels at the different levels are (nearly) the same width.

**Comment by borisveytsman** [comment]
As to margins:  the space for SIGS is at premium.  Frank Mittelbach suggested this change as one of the ways for tighter typesetting.

I can look at itemize lists.

**Comment by MatthewFluet** [comment]
Regarding margins: Sure, there are lots of ways to fit more text onto the page, but the "cost" of having content stand out in a list is that it takes up a little more space.  In any case, it just seems rather cramped to me to have virtually no left margin with lists, especially when following the first line of an indented paragraph.

**Comment by borisveytsman** [comment]
The same margin for itemize and enumerate has an advantage of having heterogenous lists aligned.  I'd keep if for now
