### ISSUE TITLE
what happened to "badge" in a previous version?

### ISSUE THREAD

**Issue by jowens** [borisveytsman/acmart#59]
I had

```
\acmBadgeR[http://ctuning.org/ae/ppopp2016.html]{img/ae-logo}
```

but that's not obviously in the latest .cls file (or in the documentation). What's the new replacement for adding a badge/logo to the first page of, say, a conference paper?

**Comment by borisveytsman** [comment]
It is there both in the documentation and .cls file

Are you sure you are looking in the latest version?

**Comment by jowens** [comment]
Probably not. Stay tuned!

**Comment by jowens** [comment]
My bad. Sorry. False alarm.
