### ISSUE TITLE
notes on bibliography style (ACM-Reference-Format.bst)

### ISSUE THREAD

**Issue by jowens** [borisveytsman/acmart#60]
1. I note that journals (`@article`) have months in the bibliography but conference articles (`@inproceedings`) do not. Deliberate?
2. `numpages` seems to override `pages`. I have a bibtex entry with`
   pages         = {12:1--12:10},
   articleno     = 12,
   numpages      = 10,`
   and it typesets as "Article 12, 10 pages." I guess I feel like if I did not have `pages` then certainly how it's done is correct, but if I do have `pages`, maybe `pages` should take preference? Of course there are tons of bib entries in digital libraries that don't actually have page numbers and so by default, they just start at one, so you have an entire conference with 100 papers all starting at page 1. (IEEE, I'm looking at you.)
3. The bib style appears to typeset paper titles in the case they're actually written rather than changing all titles to sentence case. While this makes logical sense, it's counter to how most bib styles I've seen do things. (Siggraph, for instance, sentence-cases paper titles.)
4. Can you put an arXiv paper into a sample bib somewhere and typeset it in one of the examples? In particular, could you ensure that the "default" bib linked from an arXiv page – e.g., http://dblp.uni-trier.de/rec/bibtex/journals/corr/KepnerABBFGHKLM16 from http://arxiv.org/abs/1606.05790 – typesets nicely? I don't have too much of a preference as to how it should look, but citing arXiv is so horribly inconsistent that you can add some helpful consistency here.

**Comment by borisveytsman** [comment]
I think that items 1, 2 and 3 are out of my control:  they are set by the ACM editors' requirements.  I wonder whether you could talk to Craig and Bernie directly?  I would love to have bib consistent, but it is for them to choose.

As to 4:  there are two things here:  (1) arxiv field for other entries (an article published in a journal with a preprint in arxiv), and (2) arxiv entry type for arxiv-only publications.  You mean both, right?

By the way, could you please make issues atomic: one item - one issue?  It is easier this way:  if an issue contains several items, some tend to fell through cracks.

**Comment by jowens** [comment]
As to 4: I would tend to think that if an article was in a peer-reviewed place (like a journal) and also in arXiv, I'd tend to cite the journal only. In this issue, I was thinking your (2), an arXiv entry type for arXiv-only publications. I say this because there is just horrible inconsistency across the board in terms of how arXiv preprints are cited (in no small part because there isn't a `@preprint` item that's suitable for arXiv).

**Comment by Blaisorblade** [comment]
@borisveytsman Based on https://www.acm.org/publications/authors/reference-formatting, it seems titles of conference papers should appear in sentence case (though the example "Predicate Path expression" is really confusing, had to cross-check my Turabian to make sense of it) and that the BST file should produce that:

> By using your BibTeX (.bib) file with the appropriate .bst file (ACM Reference Format) your references should require minimum editing.

I'm not sure where else to ask: I don't know if that link is the correct reference, who Craig or Bernie are (if they are [here](http://www.acm.org/key-people/staff/staff-r) I have a guess) or whether I am supposed to write them (and I don't presume so).

**Comment by rionda** [comment]
(why is "Predicate Path expression" even correct? The PDF from ACM DL has "Predicate Path Expression" as title, and the ACM DL page lists it as "Predicate path expression" ?).

**Comment by Blaisorblade** [comment]
> why is "Predicate Path expression" even correct?

I also wondered a bit—no clue either.

Why I guess that should be sentence case: Turabian claims books/journal names/etc. (the hierarchically "bigger" unit) go in italic and title case, while paper names and such (the hierarchically "smaller" unit) go in roman and sentence case—which has a logic (maybe you all knew, I confess I didn't).

**Comment by rionda** [comment]
Perhaps @Craig-Rodkin may comment about this issue?

**Comment by borisveytsman** [comment]
Right now I keep the original capitalization for both journal articles and conference proceedings in the bibliography.  It is a trivial change to move to the sentence case - if ACM agrees to do it,

**Comment by Craig-Rodkin** [comment]
When this 1979 proceedings article was published, there must have been less oversight over capitalization of articles. It is not trivial for ACM to go back and change the data for published articles. 

Boris it makes sense to make the change provided that proper nouns go untouched. Leaving Init Cap is less damaging than losing the correct capitalization in proper nouns.

**Comment by rionda** [comment]
@Craig-Rodkin : Thank you for your answer. 
Perhaps the page https://www.acm.org/publications/authors/reference-formatting should give an example of a proceedings article with a more up-to-date and consistent capitalization across PDF, ACM DL page, and anything else.

**Comment by Craig-Rodkin** [comment]
Thanks. I’m having the whole page reviewed.

Regards,

-Craig

Craig Rodkin
Publications Operations Manager
Association for Computing Machinery
rodkin@hq.acm.org<mailto:rodkin@hq.acm.org>
http://member.acm.org/~rodkin

Explore Association for Computing Machinery's AUTHOR-IZER SERVICE:  http://www.acm.org/publications/acm-author-izer-service<http://www.acm.org/publications/acm-author-izer-service>

**Comment by jowens** [comment]
@Craig-Rodkin It would be great to have BibTeX entries along with the citations on that page, and also (please!) an arXiV article there.

**Comment by rionda** [comment]
@Craig-Rodkin, also, could you please comment on items 1 and 2 in @jowens' original message (months and numpages/pages)?

Thank you.

**Comment by Craig-Rodkin** [comment]
Hi John,

I will have an arXiv example added

rionda - I will look into #1 & 2. Though resident expert just retired, so it will take a bit longer to investigate.

**Comment by Craig-Rodkin** [comment]
Regarding #1 @month is optional and I'm investigating the rational to omit the data

Regarding #2 

It is ACM's style to output paginated and enumerated articles differently:

For a paginated article in a journal:

[1] Patricia S. Abril and Robert Plant. 2007. The patent holder's dilemma: Buy, sell, or troll? Commun. ACM 50, 1 (Jan. 2007), 36-44. DOI:http://dx.doi.org/10.1145/1188913.1188915

For an enumerated article in a journal:

[1] Sarah Cohen, Werner Nutt, and Yehoshua Sagic. 2007. Deciding equivalances among conjunctive aggregate queries. J. ACM 54, 2, Article 5 (April 2007), 50 pages. DOI:http://dx.doi.org/10.1145/1219092.1219093

**Comment by Craig-Rodkin** [comment]
Almost missed the  "It would be great to have BibTeX entries" request. I'll have these added to the page ASAP.

**Comment by jowens** [comment]
@Craig-Rodkin Checking in on the last part (BibTeX entries).

**Comment by jowens** [comment]
@Craig-Rodkin, politely but persistently, can I check on the BibTeX entries?

**Comment by Craig-Rodkin** [comment]
Hi John, Please forgive the delayed response. The ACM journals manager has tasked staff to get this done. However, I'm not sure of the schedule. I will let you know when we have added the BibTeX and arXiv sample entries.

**Comment by jowens** [comment]
Thanks for keeping on this!

**Comment by jowens** [comment]
@Craig-Rodkin Still a great idea!

**Comment by jowens** [comment]
@Craig-Rodkin Idea continues to be great!

**Comment by Craig-Rodkin** [comment]
Hi John, I'll investigate why the samples have not been provided. thanks for the reminder.

**Comment by Craig-Rodkin** [comment]
Hi John,

The page is finally live. My apologies for the delay. 

Please review http://www.acm.org/publications/authors/bibtex-formatting

Please note that the fonts are a little bit off due to cutting and pasting. I'm looking for an in-house expert to clean the page up a bit. 

Authors can get to this page from http://www.acm.org/publications/proceedings-template. The link is within the Reference format section of the page.

**Comment by rionda** [comment]
Perhaps this issue can now be closed?
