### ISSUE TITLE
Typo in acmart.pdf

### ISSUE THREAD

**Issue by koallen** [borisveytsman/acmart#64]
Note: This refers to the version available on ACM website.

In section 2.10, in description for `\citestyle`, it reads

    the authoryear format acmauthoryear or the numeric format acmnumeric using 
    the command \sitestyle

It should be

    the authoryear format acmauthoryear or the numeric format acmnumeric using 
    the command \citestyle

**Comment by borisveytsman** [comment]
Thanks
