### ISSUE TITLE
New fonts?

### ISSUE THREAD

**Issue by rionda** [borisveytsman/acmart#66]
This may be an issue with documentation:

On line 2142 of acmart.dtx, it says: "Use Times throughout". 
I'm not sure what the intention of this sentence was, but if the new fonts are installed, those are used, and they are not "Times" (which I would associate with \usepackage{times}), but rather, inconsolata and libertine.

Also, I was wondering about the choice of fonts. Can you explain why inconsolata and libertine where chosen? Previous ACM format used computer modern (if I remember correctly) and this seems a "big" change.

Thanks.

**Comment by borisveytsman** [comment]
Thanks for your report!  I will update the documentation.

About the choice of fonts: previously ACM used Times for many (most) of its publications.  In the process of consolidation it was decided to use uniform fonts across the publication list.  After  research and deliberations the senior staff of ACM chose libertine as the body fonts as the most clear and legible and having the "right look and feel".

**Comment by rionda** [comment]
Thanks you!
