### ISSUE TITLE
Hyperref warning

### ISSUE THREAD

**Issue by rionda** [borisveytsman/acmart#67]
The command

```
\ccsdesc[500]{something~something}
```

causes warnings in hyperref (even for "valid" values of something~something):

```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\to' on input line 156.
```

One can test this even with the `sample-siggconf.tex` example file.

A possible solution may be to use \textrightarrow from the textcomp package (http://tex.stackexchange.com/questions/229289/arrow-in-text-mode#229290)

I haven't tested this.

**Comment by rionda** [comment]
See pull request for possible solution.

**Comment by rionda** [comment]
I wasn't sure whether the version number needed to be increased (and the consequent comment on README.md), so I didn't do it in my pull request.

**Comment by borisveytsman** [comment]
Don't worry: I'll jump the version number when uploading to CTAN (I might need to close a couple of other issues first)
