### ISSUE TITLE
natbib=false leaves \citationstyle undefined

### ISSUE THREAD

**Issue by gvdgdo** [borisveytsman/acmart#68]
when one uses the `natbib=false` option, the command `\citationstyle` is left undefined: line 268 of `acmart.cls`.  (line 250 in the pdf of the manual). 

The issue of the `\citestyle{acmnumeric}` should be inside the `\if@ACM@natbib` block (lines 159-238 in the pdf of the manual)

**Comment by borisveytsman** [comment]
thanks!
