### ISSUE TITLE
long title will overlap with the conference info  on TOP BAR in recto pages

### ISSUE THREAD

**Issue by lipiji** [borisveytsman/acmart#73]
rt

**Comment by MatthewFluet** [comment]
That's why the `\title` command takes an optional "short title" argument.

**Comment by magsilva** [comment]
Instead of forcing authors to provide a short title, could we modify the header to allow more than one line, avoiding the overlap of the conference information? I've seen that some Word documents for an ACM conference that employed this workaround.
