### ISSUE TITLE
Suppress copyright block with review=true

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#8]
An article under review has no journal/conference, DOI, ISBN, publication rights, etc.  Don't require/display such information for a paper under review.

As an alternative, reserve `review=true` for the line numbering and introduce a new `preprint` option which would suppress the copyright block (and be required to enable `review=true`).

**Comment by borisveytsman** [comment]
Sometimes review mode may be used for final copyediting and corrections, so I'd like to preserve the copyright block there.  Also, I think a submitted paper has journal and conference information.

Maybe format=manuscript is what you mean?

**Comment by borisveytsman** [comment]
Besides, if you leave the fields empty, this will not produce any error messages.

**Comment by MatthewFluet** [comment]
Certainly not `format=manuscript` for conference submissions --- page limits make it dangerous to consider such radical format changes from submission to final.

I (personally) think it presumptive to include conference information in a submission; I don't expect that a reviewer will be unsure about the conference to which the paper was submitted.

**Comment by MatthewFluet** [comment]
Leaving all of the copyright/permission block related fields empty defaults to the `acmcopyright` behavior, which does not seem like the right behavior (copyright of my submission is not transferred to ACM).

**Comment by borisveytsman** [comment]
\setcopyright{none} is probably what you want

**Comment by ayman** [comment]
For reference we had a similar issue at SIGCHI.   Some authors were putting a certain 'mark' in the setcopyright block that was, in effect, revealing the two papers came from the same author during the review process. 

See: https://github.com/sigchi/Document-Formats/issues/66 for details.

**Comment by borisveytsman** [comment]
Canned permission blocks may help anonymization to a certain extent.  However, if the author, for example, uses 'cagov' mode, it might be a giveaway: how many Canadian government officials you might have.  Should I put a special copyright verbiage in anonymous mode?

In the anonymous mode I suppress not only the authors' names and affiliations, but also any title and author notes.  I do not have a separate interface for acknowledgements if they are in the body;  do you think I might add some way to suppress certain blocks of text in this mode?

**Comment by borisveytsman** [comment]
After discussion with the ACM editors it was decided that the copyright block in the review version reflects the copyright of the final product rather than of the manuscript.
