### ISSUE TITLE
Where is the .cls file?

### ISSUE THREAD

**Issue by fanchyna** [borisveytsman/acmart#83]
I download it to my macbook air and try to compile it using LaTex typeset in TexShop, but it could not find the acmart.cls file? I tried different typesets but none of them worked. Where is the cls file? Or is it compiled in a different way?

**Comment by borisveytsman** [comment]
1.  MacTeX currently includes acmart, so you do not need to download anything.  Just update your installation.  You probably need to update the installation anyway to get the fonts.

2.  If you do want the development version, download acmart.ins and acmart.dtx and run

latex acmart.ins

**Comment by fanchyna** [comment]
I ran latex acmart.ins and generated the .cls file. I can compile and generate the PDF file now. The font is not a problem for me. I am using TexShop 3.61. Thanks!

**Comment by borisveytsman** [comment]
Ok, I am closing the issue

**Comment by MakarovIA** [comment]
What is the solution for sharelatex users - no acmart.cls was updated in their system...
Why not include it in archive?

**Comment by bennn** [comment]
You can download a copy from sigplan.org: http://www.sigplan.org/sites/default/files/acmart/current/acmart.cls

**Comment by borisveytsman** [comment]
@MakarovIA Sharelatex quickly installs the version from CTAN, which has .cls file.  If you have problems, let me know

**Comment by MakarovIA** [comment]
I have a trouble following http://www.sheridanprinting.com/typedept/mm.htm#L instructions for acmart, which produce copyright block with errors in missing date, double "ISBN" word and wrong DOI URL
https://www.overleaf.com/10518186rxgwvmgwtfrb
If you could help me to solve the issue, I will be very grateful.

**Comment by borisveytsman** [comment]
Corrected.  Удачи!

**Comment by MakarovIA** [comment]
Thank you. Спасибо!

**Comment by ligianistor** [comment]
I keep getting "! Undefined control sequence.
\abstract ->\Collect@Body 
                          \@saveabstract 
l.63 \begin{abstract}" 
When I use the new acmart template with \documentclass[sigplan,screen]{acmart} it can't compile \begin{abstract}. I have the latest packages of miktex and I've tried both on linux and windows.

**Comment by ligianistor** [comment]
Actually after I generated the acmart.cls, I got this error:
! Missing \endcsname inserted.
<to be read again> 
                   \relax 
l.2399 \newtheorem{theorem}{Theorem}[section]

I went and I deleted the \newtheorem lines from the cls class and then the compilation got a bit further, but now I am having the problem with the abstract that I described above.

**Comment by borisveytsman** [comment]
Could you send me your log file?

**Comment by ligianistor** [comment]
I have attached it.
Thanks

**Comment by borisveytsman** [comment]
I do not see it.  Please visit https://github.com/borisveytsman/acmart/issues/83 and attach the file

**Comment by ligianistor** [comment]
[main.txt](https://github.com/borisveytsman/acmart/files/1261148/main.txt)
Attached. I had to rename it to main.txt

**Comment by borisveytsman** [comment]
Thanks!

Here is an important clue:

```
(./environ.sty
 -------- ks environ loaded (2000.08.26) ————//- 
```

1.  You use the copy of the environ.sty in your working directory rather than the system one.

2.  This copy is really outdated:  the current one is

`\ProvidesPackage{environ}[2014/05/04 v0.3 A new way to define environments]`

Please delete this copy and check your system has the current one.

**Comment by ligianistor** [comment]
Yes, that was the problem, thanks!

**Comment by ligianistor** [comment]
Another problem:

 The font of your paper should be corrected.
  With the new template, Linux Biolinum should be used as sans serif font
for the title, for headers,
  for headings, and for captions of figures and tables.
  Linux Libertine should be used as serif font for all other content.
  Some packages change the font of the template. Please see the help page
that is linked on the instructions page for hints.

I have no idea what is wrong now? This template has so many problems.

**Comment by krono** [comment]
@ligianistor please open a new issue for that. Also, please include the log file so we see what's wrong

**Comment by ligianistor** [comment]
it says that the libertine package is not installed, in the log. I just
need to put the libertine.sty file in my workspace?

**Comment by krono** [comment]
No, also please open a new issue.

**Comment by m-bilgic** [comment]
Using MiKTeX version 2.9.700. Windows 10. Installed the acmart package using the  MiKTeX package manager; updated the package database. Using \documentclass[sigconf]{acmart} in my tex file. Error: 

> ! LaTeX Error: File `acmart.cls' not found.
