### ISSUE TITLE
Affiliation: Institution disambiguation

### ISSUE THREAD

**Issue by krono** [borisveytsman/acmart#84]
For several institutes that are adjunct to an university, it can be necessary to state _both_ the institute and the university. Also, they might have their own departments.

Which of the following is preferred?

1. Separation with `\\`

    ```LaTeX
    \affiliation{%
      \department{Department of Lunar Studies}
      \institution{John Doe Institute,\\ University of San Serriffe}
      \country{San Serriffe}}
    ```
2. Separation with `\par` (Won't work but consistent with how `\institution` works right now)

    ```LaTeX
    \affiliation{%
      \department{Departmen of Lunar Studies}
      \institution{John Doe Institute,\par University of San Serriffe}
      \country{San Serriffe}}
    ```
3. Separate `\institution`

    ```LaTeX
    \affiliation{%
      \department{Departmen of Lunar Studies}
      \institution{John Doe Institute}
      \institution{University of San Serriffe}
      \country{San Serriffe}}
    ```

Alternatively, introduce a new `\institute` (might be confusing, admittedly)

```LaTeX
\affiliation{%
  \department{Departmen of Lunar Studies}
  \institute{John Doe Institute}
  \institution{University of San Serriffe}
  \country{San Serriffe}}
```

**Comment by borisveytsman** [comment]
I asked Aptara who requested the field.

My preferred solution would be to introduce the hierarchy of departments:

\affiliation{%
\department[0]{Department of Lunar Studies} % 0 is the default
\department[1]{John Doe Institute} % higher than the default [0]
\institution{University of San Serriffe}
\country{San Serriffe}}

**Comment by krono** [comment]
Thank you!
