### ISSUE TITLE
[bst] DOI stripping does not consider https

### ISSUE THREAD

**Issue by krono** [borisveytsman/acmart#85]
The code in `strip.doi` tries to eliminate any resolver prefix from DOIs but does so by substringmatching on "http://"

```BibTeX
  doi #1 #3 substring$ "10." =
    { doi }
    {
      doi #1 #7 substring$ "http://" =
        {
```

However, the current display [recommendation for DOIs by CrossRef is to use "https://doi.org/…" as resolver](https://www.crossref.org/blog/linking-dois-using-https-the-background-to-our-new-guidelines/), so those will be more common now.

**Comment by borisveytsman** [comment]
Thanks - will take care of this
