### ISSUE TITLE
Strange font substitution with `mathcomp`

### ISSUE THREAD

**Issue by krono** [borisveytsman/acmart#88]
When I use the `mathcomp` package with `acmart`, I get a complaint about font substitution that seems odd:

```
LaTeX Font Warning: Font shape `TS1/cmr/m/n' in size <5.5> not available
(Font)              size <5> substituted on input line 4.
```

This does not happen with `article` or `amsart`

MWE:
```LaTeX
\documentclass[sigconf]{acmart}
\usepackage{mathcomp}
\begin{document}
\author{b}\title{a}
\maketitle
\end{document}
```

**Comment by krono** [comment]
Ok, nevermind, passing `rmdefault` to mathcomp fixes this.

Maybe add
```LaTeX
\PassOptionsToPackage{rmdefault}{mathcomp}
```
to `acmart.dtx`/`cls`, so people don't fall in that trap?

**Comment by borisveytsman** [comment]
Thanks

A line like this can be interpreted as a recommendation to use mathcomp, cannot it?

**Comment by krono** [comment]
Well, or as a precaution should someone want to load it…

Problem is, that without this option, `mathcomp` wants to influence CMR, which is wrong in `acmart`'s case anyway.

An example: in this class, I want to make sure that the `listings` package always will be used with `final`, even when people specify `draft`. This is not a recommendation to use `listings`, but just a precaution:
<https://github.com/HPI-SWA-Lab/hpitr/blob/master/hpitr.dtx#L446>
