### ISSUE TITLE
Generating an author's version

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#9]
The [ACM Copyright Policy](http://www.acm.org/publications/policies/copyright_policy#Retained) allows an author to use their work (e.g., posting on their homepage), but requires a statement "substantially similar" to the following "in connection with any use by the Owner".

 ```© {Owner/Author | ACM} {Year}. This is the author's version of the work. It is posted here for your personal use. Not for redistribution. The definitive Version of Record was published in {Source Publication}, http://dx.doi.org/10.1145/{number}.```

It should be easy to generate such a version, say with a `\setcopyright{authorversion}` or some such.  Note that the choice of "Owner/Author" or "ACM" as the copyright holder depends on the actual eRights chosen for the paper, so a single `authorversion` option is not sufficient.

**Comment by borisveytsman** [comment]
Hmm.  I forwarded this to Craig - I guess any change in this part should be bounced off ACM lawyers...

**Comment by MatthewFluet** [comment]
I suppose one option is for an author's version to place the required statement in the header, leaving the copyright/permission block as is.  Since it part of the ACM Copyright Policy, I always assumed that the statement adds to or replaces the standard copyright/permission block, but I suppose it need not.

**Comment by borisveytsman** [comment]
Ok, added the option
