### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 474: invalid start byte

### ISSUE THREAD

**Issue by domoritz** [borisveytsman/acmart#90]
With a clean checkout and running make on master, I get the following error:

```
Including 'printonly' comment. Straight input of comment.cut. (./comment.cut)
Excluding 'screenonly' comment. Processing 'acks' comment.
Comment 'acks' writing to comment.cut. Straight input of comment.cut.
(./comment.cut) (./sample-acmtog.bbl
Traceback (most recent call last):
  File "/usr/local/Cellar/grc/1.10_1/libexec/bin/grcat", line 180, in <module>
    line = freadline()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 474: invalid start byte
```

**Comment by borisveytsman** [comment]
I am not sure I understand what you are doing here.  You seem to call python and grcat - certainly not a part of a normal TeX process.  Could you please elaborate?

**Comment by domoritz** [comment]
I tried to run `make all` and the script starts running until it get's to the error above. The complete log is [here](http://pastebin.com/raw/XS9TuK9e). I was hoping that the log would help you to resolve errors that others may have in the future. 

I am using Python 2.7.13 and Python 3.6.0. 

Btw, after I figured out that I can get the `acmart.cls` with `make acmart.cls`, I was pleasantly surprised about how easy it is to create papers with the ACM template now. Thank you for putting the effort into this!

**Comment by borisveytsman** [comment]
Thanks for your kind words, but I still do not understand how this makefile would call python...

What does "make -n all" say?

**Comment by borisveytsman** [comment]
After some thoughts I think I found out what happens

My scripts call grep.  Evidently your system uses a python script with similar functionality instead.  Evidently the grep emulator does not reproduce the original grep.

**Comment by domoritz** [comment]
Oh wow. The problem was completely on my side. I have [grc](https://github.com/pengwynn/grc) installed and it broke on the make output. 

Everything works fine when I run make in a bash session without grc. 

Sorry for flagging this here.
