### ISSUE TITLE
Need T1 encoding for libertine

### ISSUE THREAD

**Issue by borisveytsman** [borisveytsman/acmart#91]
Looks like OT1 with libertine is broken:  http://tex.stackexchange.com/questions/353646/how-to-enter-a-polish-l-in-acmart-document-class

**Comment by eg9** [comment]
Indeed! OT1 encoded fonts are supposed to have `lslashslash` in slot 32, but Libertine hasn't it. I see no real way to fix it without changing font encoding or borrowing the glyph from another font, which would be a mess anyway.

**Comment by borisveytsman** [comment]
I wrote  Bob Tennent about this.  Probably should change to T1 meanwhile
