### ISSUE TITLE
Margin notes go off end of page

### ISSUE THREAD

**Issue by LeifAndersen** [borisveytsman/acmart#94]
Just a heads up that margin notes seem to go off the end of the page.

For example, if I have the following file:

```
\documentclass[format=acmlarge]{acmart}

\title{Hello}
\author{World}

\begin{document}
\begin{abstract}
Hello, this is an abstract
\end{abstract}
\maketitle

\section{First part}

This is the first section, it says some stuff. This stuff may or may not be interesting, it kind of depends.
\marginpar{Here is a margin note, it also says some stuff that may or may not be interesting.}

\end{document}
```

I get a margin note that looks like this:

![screen shot 2017-02-20 at 11 27 50 am](https://cloud.githubusercontent.com/assets/285926/23133612/b715dafa-f75f-11e6-8c87-e9fddcb1aa98.png)

**Comment by LeifAndersen** [comment]
It looks like adding `\setlength\marginparwidth{2cm}` to any paper that uses this class fixes it, but it seems like the class itself should fix it.

**Comment by borisveytsman** [comment]
Sigchi-a uses margin notes.  Other formats do not, so I did not test margin notes for them.  I see their use for manuscript preparation, however...
