### ISSUE TITLE
\\ and \footnote in title breaks the reference citation format

### ISSUE THREAD

**Issue by borisveytsman** [borisveytsman/acmart#96]
Rasit Eskicioglu found that `\title{aaa \\ bbb} ` breaks reference citation format.  The same with foonotes in title

**Comment by MatthewFluet** [comment]
Regarding the latter, shouldn't `\titlenote` be used (rather than `\footnote` within the title)?

**Comment by borisveytsman** [comment]
Yes, `\titlenote` should be used there.  `\footnote` messes with the metadata extraction tools, and thus should not be used inside title or author.

What I am  thinking about is whether make `\footnote` produce fatal error in this situation.  I'd rather do it, but then I envision angry authors who never bothered to read the manual or read the error message...
