### ISSUE TITLE
how to completely suppress conference information with acmart

### ISSUE THREAD

**Issue by monperrus** [borisveytsman/acmart#97]
My paper uses acmart and I want to upload a version on Arxiv.
`\setcopyright{none}` suppresses the copyright but not the conference information (name, location, etc).

What's the option to  completely suppress the conference information block?

Thanks.

**Comment by borisveytsman** [comment]
I think setting the format to `manuscript`, as in `\documentclass[manuscript]{acmart}` is the way to upload an arXiv version.  Conference format is really for the conference proceedings only.  However, if you insist on using the conference format,  you can try `\acmConference{}{}{}`.  This still gets a dot where the conference should be, so I would recommend manuscript anyway,

**Comment by monperrus** [comment]
Thanks. However, `\documentclass[manuscript]{acmart}` is a single column version. What about a double-column option without copyright and  conference information block?

**Comment by borisveytsman** [comment]
`acmtog`

**Comment by monperrus** [comment]
not realy, acmtog results in

on first page:

> VV, NNN, Article AA (MM YYYY),
> 11 pages.
> DOI: 10.1145/nnnnnnn.nnnnnnn

> YYYY. XXXX-XX/YYYY/MM-ARTAA $15.00
> DOI: 10.1145/nnnnnnn.nnnnnnn


on all pages

> , Vol. VV, No. NNN, Article AA. Publication date: MM YYYY.

**Comment by borisveytsman** [comment]
You can suppress bibliography on the first page using `\settopmatter{printacmref=false}`.  You can suppress footers by setting in the preamble
`\fancyfoot{}` and after `\maketitle` issuing `\thispagestyle{empty}`

**Comment by borisveytsman** [comment]
I guess this can be closed now

**Comment by mcoblenz** [comment]
It looks like the "nonacm" option does the job now.

**Comment by maramassi** [comment]
> It looks like the "nonacm" option does the job now.

Where have you added the nonacm? I am facing the same issue and I can't figure out how to remove the conference infomration

**Comment by maramassi** [comment]
Adding **"\pagestyle{empty}"** after \maketitle removes it

**Comment by rothnie** [comment]
> Adding `\pagestyle{empty}` after `\maketitle` removes it
> Note that adding `\thispagestyle{empty}` did not remove it on overleaf

This worked for me! Thanks

**Comment by patrickbruyn12** [comment]
@maramassi great! I was looking for a long time for this solution.

**Comment by mcoblenz** [comment]
> > It looks like the "nonacm" option does the job now.
> 
> Where have you added the nonacm? I am facing the same issue and I can't figure out how to remove the conference infomration

For example, if you want two-column format but no conference information, you can use this:

`\documentclass[sigconf,nonacm]{acmart}`

**Comment by YunlianMoon** [comment]
but have some prblems when use `\documentclass[sigconf,nonacm,review=true]{acmart}`
